MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.car.CCarJasonAgent Class Reference
de.tu_clausthal.in.mec.object.car.CCarJasonAgent Class Reference
agent car
Classes
class CTrafficStorage
private class for definined a belief storage to use "traffic content information"
Public Member Functions
CCarJasonAgent (final ArrayList< Pair< EdgeIteratorState, Integer >> p_route, final int p_speed, final int p_maxspeed, final int p_acceleration, final int p_deceleration, final double p_lingerprobability, final String p_objectname, final String p_agent) throws Exception
ctor
CCarJasonAgent (final ArrayList< Pair< EdgeIteratorState, Integer >> p_route, final int p_speed, final int p_maxspeed, final int p_acceleration, final int p_deceleration, final double p_lingerprobability, final String p_objectname, final Set< String > p_agent) throws Exception
CPath getReceiverPath ()
returns the path of the object
final Map< String, Object > inspect ()
returns a map to inspect current data of the car
void receiveMessage (final Set< IMessage > p_messages)
receives all messages, each message is unique
final void release ()
release function to remove object *
void step (final int p_currentstep, final ILayer p_layer) throws Exception
step method
Public Member Functions inherited from de.tu_clausthal.in.mec.object.car.CDefaultCar
CDefaultCar (final ArrayList< Pair< EdgeIteratorState, Integer >> p_route, final int p_speed, final int p_maxspeed, final int p_acceleration, final int p_deceleration, final double p_lingerprobability) throws IllegalArgumentException
ctor to create the initial values
final int getAcceleration ()
define an individual acceleration
final int getCurrentSpeed ()
returns the current speed of the car
final int getDeceleration ()
define an individual deceleration
final EdgeIteratorState getEdge ()
get current edge object on the graph
final GeoPosition getGeoposition ()
returns the current geo position of the car
final double getLingerProbability ()
returns a probability for lingering
final int getMaximumSpeed ()
returns the maximum speed of the car
final Map< Double, ICar > getPredecessor ()
returns the current predecessor of the car and the distance
final Map< Double, ICar > getPredecessor (final int p_count)
final boolean hasEndReached ()
boolean method, that returns true, if the car has reached its end
Map< String, Object > inspect ()
returns a map to inspect current data of the car
final void onClick (final MouseEvent p_event, final JXMapViewer p_viewer)
final void paint (final Graphics2D p_graphic, final COSMViewer p_viewer, final int p_width, final int p_height)
void release ()
release function to remove object *
final void setCurrentSpeed (final int p_speed)
void step (final int p_currentstep, final ILayer p_layer) throws Exception
step method
Public Member Functions inherited from de.tu_clausthal.in.mec.ui.IInspectorDefault
Map< String, Object > inspect ()
returns a map to inspect current data of the car
Public Member Functions inherited from de.tu_clausthal.in.mec.ui.IUIListener
IUIListener ()
ctor to registerObject component on the viewer
final void mouseClicked (final MouseEvent p_event)
final void mouseEntered (final MouseEvent p_event)
final void mouseExited (final MouseEvent p_event)
final void mousePressed (final MouseEvent p_event)
final void mouseReleased (final MouseEvent p_event)
void onClick (final MouseEvent p_event, final JXMapViewer p_viewer)
click method which is called by a click on the object
void release ()
release of the event handler
Public Member Functions inherited from de.tu_clausthal.in.mec.object.car.ICar
Map< Double, ICar > getPredecessor (int p_count)
returns the current predecessor of the car and the distance
void setCurrentSpeed (int p_speed) throws IllegalArgumentException
sets the current speed of the care
Private Member Functions
void bind (final String p_asl) throws Exception
binds an agent with the name
Map< Double, Map< String,
Object > > getPredecessorWithName (final int p_count)
returns the predecessor with name for communication
Private Attributes
final CCarJasonAgentLayer m_agentlayer = CSimulation.getInstance().getWorld().<CCarJasonAgentLayer>getTyped("Jason Car Agents")
reference to the agent layer
final Set
< de.tu_clausthal.in.mec.object.mas.jason.CAgent > m_agents = new HashSet<>()
agent object *
final Map< String, Object > m_inspect
inspector map
final CPath m_objectpath
internal receiver path
int m_seenpredecessors = 2
number of predecessors that can be seen by the agents
final IBeliefBase< Literal > m_trafficbeliefbase = new CBeliefBase<>(new CTrafficStorage())
agent traffic environment belief base
Additional Inherited Members
Protected Member Functions inherited from de.tu_clausthal.in.mec.object.car.CDefaultCar
final Triple
< EdgeIteratorState, Integer,
GeoPosition > getCurrentPosition ()
returns a triple of the current edge id, cell position and geoposition
Protected Member Functions inherited from de.tu_clausthal.in.mec.ui.IUIListener
final double iconscale (final JXMapViewer p_viewer)
returns the normalized zoom level
final int iconsize (final JXMapViewer p_viewer)
returns the icon size
Protected Attributes inherited from de.tu_clausthal.in.mec.object.car.CDefaultCar
final CCarLayer m_layer = CSimulation.getInstance().getWorld().<CCarLayer>getTyped("Cars")
reference to the graph
final int m_maxspeed
maximum speed definition in km/h
final ArrayList< Pair
< EdgeIteratorState, Integer > > m_route
cell structure of the route
int m_routeindex
current position on the route
Integer m_speed
current speed in km/h (use boxed-type because MAS can modify value)
Static Protected Attributes inherited from de.tu_clausthal.in.mec.ui.IUIListener
static final int c_maxzoom = 9
maximum zoom value *
static final int c_miniconsize = 3
minimum icon size *
Detailed Description
Note
the agent gets the following traffic-beliefs during runtime:
predecessor that show the predecessor vehicles and can be manipulated with the belief seenpredecessors
start-/endposition defines the start and the end geo position of the route
currentposition defines the current geo position and the edge information e.g. name and length of the edge, and the routesample shows the current route sampling information
inconsistency defines the inconsistency value of each agent
drived defines the history drived-time and -distance of the vehicle
Bug:
refactor ctor (reduce parameter)
Definition at line 67 of file CCarJasonAgent.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CCarJasonAgent (final ArrayList< Pair< EdgeIteratorState, Integer >> p_route, final int p_speed, final int p_maxspeed, final int p_acceleration, final int p_deceleration, final double p_lingerprobability, final String p_objectname, final String p_agent) throws Exception
Parameters
p_route driving route
p_speed initial speed
p_maxspeed maximum speed
p_acceleration acceleration
p_deceleration decceleration
p_lingerprobability linger probability
p_objectname name of the object within the simulation
p_agent ASL / agent name *
Exceptions
JasonException throws on Jason error
Definition at line 115 of file CCarJasonAgent.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.getPredecessorWithName().
de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CCarJasonAgent (final ArrayList< Pair< EdgeIteratorState, Integer >> p_route, final int p_speed, final int p_maxspeed, final int p_acceleration, final int p_deceleration, final double p_lingerprobability, final String p_objectname, final Set< String > p_agent) throws Exception
Parameters
p_route driving route
p_speed initial speed
p_maxspeed maximum speed
p_acceleration acceleration
p_deceleration decceleration
p_lingerprobability linger probability
p_objectname name of the object within the simulation
p_agent set with ASL / agent name
Exceptions
JasonException throws on Jason error
Definition at line 140 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), and de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_objectpath.
Member Function Documentation
void de.tu_clausthal.in.mec.object.car.CCarJasonAgent.bind (final String p_asl) throws Exception private
Parameters
p_asl ASL / agent name
Exceptions
JasonException throws on Jason error
Definition at line 197 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_trafficbeliefbase.
Map<Double, Map<String, Object> > de.tu_clausthal.in.mec.object.car.CCarJasonAgent.getPredecessorWithName (final int p_count) private
Parameters
p_count number of predecessors
Returns
map with distance and map with name and can communicate
Definition at line 218 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CCarJasonAgent(), de.tu_clausthal.in.mec.common.CCommon.getMap(), and de.tu_clausthal.in.mec.object.car.ICar.getPredecessor().
CPath de.tu_clausthal.in.mec.object.car.CCarJasonAgent.getReceiverPath ()
Returns
path
Implements de.tu_clausthal.in.mec.runtime.message.IReceiver.
Definition at line 151 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_objectpath.
final Map<String, Object> de.tu_clausthal.in.mec.object.car.CCarJasonAgent.inspect ()
Returns
map with name and value
Implements de.tu_clausthal.in.mec.ui.IInspector.
Definition at line 163 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_inspect.
void de.tu_clausthal.in.mec.object.car.CCarJasonAgent.receiveMessage (final Set< IMessage > p_messages)
Parameters
p_messages set of messages
Implements de.tu_clausthal.in.mec.runtime.message.IReceiver.
Definition at line 157 of file CCarJasonAgent.java.
final void de.tu_clausthal.in.mec.object.car.CCarJasonAgent.release ()
Implements de.tu_clausthal.in.mec.runtime.ISteppable.
Definition at line 170 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_agents.
void de.tu_clausthal.in.mec.object.car.CCarJasonAgent.step (final int p_currentstep, final ILayer p_layer) throws Exception
Parameters
p_currentstep current step value
p_layer layer on which is the object push or null
Implements de.tu_clausthal.in.mec.runtime.IVoidSteppable.
Definition at line 182 of file CCarJasonAgent.java.
References de.tu_clausthal.in.mec.object.car.CDefaultCar.m_maxspeed, and de.tu_clausthal.in.mec.object.car.CDefaultCar.m_speed.
Member Data Documentation
final CCarJasonAgentLayer de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_agentlayer = CSimulation.getInstance().getWorld().<CCarJasonAgentLayer>getTyped("Jason Car Agents") private
Definition at line 100 of file CCarJasonAgent.java.
final Set<de.tu_clausthal.in.mec.object.mas.jason.CAgent> de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_agents = new HashSet<>() private
Definition at line 77 of file CCarJasonAgent.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.release(), and de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CTrafficStorage.updating().
final Map<String, Object> de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_inspect private
Initial value:
= new HashMap<String, Object>()
    {{
        putAll( CCarJasonAgent.super.inspect() );
    }}
Definition at line 82 of file CCarJasonAgent.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.inspect().
final CPath de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_objectpath private
Definition at line 90 of file CCarJasonAgent.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CCarJasonAgent(), and de.tu_clausthal.in.mec.object.car.CCarJasonAgent.getReceiverPath().
int de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_seenpredecessors = 2 private
Definition at line 72 of file CCarJasonAgent.java.
final IBeliefBase<Literal> de.tu_clausthal.in.mec.object.car.CCarJasonAgent.m_trafficbeliefbase = new CBeliefBase<>(new CTrafficStorage()) private
Definition at line 95 of file CCarJasonAgent.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.bind().