MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.COSMViewer Class Reference
de.tu_clausthal.in.mec.ui.COSMViewer Class Reference
openstreetmap viewer class - must be a singleton because we would to use only one instance with a global access
Inherits JXMapViewer.
Classes
class CLinePainter
routing painter class
enum EClickableLayer
enum clickable layer
Public Member Functions
COSMViewer ()
ctor with loading configuration defaults and listener definition
final CompoundPainter<?> getCompoundPainter ()
returns the compounend painter
final EClickableLayer getCurrentClickableLayer ()
returns the current active layer
final GeoPosition getViewpointGeoPosition (final Point p_point)
returns the geoposition of a mouse position
void paintFadeLine (final List< Triple< Pair< GeoPosition, GeoPosition >, Color, Stroke >> p_line)
sets a new route
final void resetConfiguration ()
resets the view *
final void setConfiguration ()
stores the current configuration
Private Member Functions
Map< String, Object > web_static_listClickableLayer ()
UI method - returns list of clickable layer names and its state.
void web_static_setClickableLayer (final Map< String, Object > p_data)
UI method - sets the current clickable layer.
Private Attributes
EClickableLayer m_clickablelayer = EClickableLayer.Source
clickable layer
final CLinePainter m_linepainter = new CLinePainter()
route painter
CompoundPainter< JXMapViewer > m_painter = new CompoundPainter<>()
compounend painter
Detailed Description
See Also
https://github.com/msteiger/jxmapviewer2
https://today.java.net/pub/a/today/2007/10/30/building-maps-into-swing-app-with-jxmapviewer.html
Definition at line 60 of file COSMViewer.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.COSMViewer.COSMViewer ()
Definition at line 78 of file COSMViewer.java.
References de.tu_clausthal.in.mec.CConfiguration.getInstance().
Member Function Documentation
final CompoundPainter<?> de.tu_clausthal.in.mec.ui.COSMViewer.getCompoundPainter ()
Returns
painter
Definition at line 111 of file COSMViewer.java.
final EClickableLayer de.tu_clausthal.in.mec.ui.COSMViewer.getCurrentClickableLayer ()
Returns
layer
Definition at line 121 of file COSMViewer.java.
Referenced by de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseClicked(), and de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseMoved().
final GeoPosition de.tu_clausthal.in.mec.ui.COSMViewer.getViewpointGeoPosition (final Point p_point)
Parameters
p_point point
Returns
geoposition
Definition at line 132 of file COSMViewer.java.
Referenced by de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseClicked().
void de.tu_clausthal.in.mec.ui.COSMViewer.paintFadeLine (final List< Triple< Pair< GeoPosition, GeoPosition >, Color, Stroke >> p_line)
Parameters
p_line route list
Definition at line 143 of file COSMViewer.java.
final void de.tu_clausthal.in.mec.ui.COSMViewer.resetConfiguration ()
Definition at line 151 of file COSMViewer.java.
final void de.tu_clausthal.in.mec.ui.COSMViewer.setConfiguration ()
Definition at line 161 of file COSMViewer.java.
Map<String, Object> de.tu_clausthal.in.mec.ui.COSMViewer.web_static_listClickableLayer () private
Returns
map with layer list
Definition at line 172 of file COSMViewer.java.
void de.tu_clausthal.in.mec.ui.COSMViewer.web_static_setClickableLayer (final Map< String, Object > p_data) private
Definition at line 184 of file COSMViewer.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Member Data Documentation
EClickableLayer de.tu_clausthal.in.mec.ui.COSMViewer.m_clickablelayer = EClickableLayer.Source private
Definition at line 65 of file COSMViewer.java.
final CLinePainter de.tu_clausthal.in.mec.ui.COSMViewer.m_linepainter = new CLinePainter() private
Definition at line 69 of file COSMViewer.java.
CompoundPainter<JXMapViewer> de.tu_clausthal.in.mec.ui.COSMViewer.m_painter = new CompoundPainter<>() private
Definition at line 73 of file COSMViewer.java.