MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer Class Reference
de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer Class Reference
class of the link and layout markdown renderer
Inherits LinkRenderer.
Classes
enum EHTMLType
enum to define return type of the HTML document *
Public Member Functions
CMarkdownRenderer ()
ctor
CMarkdownRenderer (final EHTMLType p_htmltype, final String p_baseuri, final String p_cssuri)
ctor
CMarkdownRenderer (final EHTMLType p_htmltype)
ctor
CMarkdownRenderer (final EHTMLType p_htmltype, final String p_baseuri)
ctor
final String getHTML (final PegDownProcessor p_processor, final URL p_file) throws IOException
creates HTML content from a markdown document
final String getMimeType ()
return mimetype
final Rendering render (final ExpLinkNode p_node, final String p_text)
final Rendering render (final ExpImageNode p_node, final String p_text)
final Rendering render (final WikiLinkNode p_node)
Private Member Functions
String getHTMLDocument (final PegDownProcessor p_processor, final URL p_file) throws IOException
creates a full HTML document from a markdown document
String getHTMLFragment (final PegDownProcessor p_processor, final URL p_file) throws IOException
creates a HTML fragment from a markdown document
String getURL (final String p_url)
returns a URI with base URI
String getWikipediaLink (final String p_language, final String p_search) throws UnsupportedEncodingException
create Wikipedia link
boolean isURL (final String p_url)
checks if a string is an URL
Private Attributes
final String m_baseuri
string with base URI
final String m_cssuri
string with optional CSS URI *
final EHTMLType m_htmltype
rendering enum
Detailed Description
Definition at line 47 of file CMarkdownRenderer.java.
Class Documentation
enum de::tu_clausthal::in::mec::ui::web::CMarkdownRenderer::EHTMLType
Definition at line 294 of file CMarkdownRenderer.java.
Class Members
Document value of a full HTML document *
Fragment value of a HTML fragment *
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer ()
Definition at line 66 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.EHTMLType.Fragment.
de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer (final EHTMLType p_htmltype, final String p_baseuri, final String p_cssuri)
Parameters
p_htmltype type of the HTML result
p_baseuri base URI
p_cssuri CSS URI
Definition at line 78 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_baseuri, de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_cssuri, and de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_htmltype.
de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer (final EHTMLType p_htmltype)
Parameters
p_htmltype type of the HTML result
Definition at line 90 of file CMarkdownRenderer.java.
de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer (final EHTMLType p_htmltype, final String p_baseuri)
Parameters
p_htmltype type of the HTML result
p_baseuri base URI
Definition at line 101 of file CMarkdownRenderer.java.
Member Function Documentation
final String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getHTML (final PegDownProcessor p_processor, final URL p_file) throws IOException
Parameters
p_processor markdown processor
p_file URL of the file
Returns
HTML content
Definition at line 113 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_htmltype.
String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getHTMLDocument (final PegDownProcessor p_processor, final URL p_file) throws IOException private
Parameters
p_processor markdown processor
p_file URL of the file
Returns
full HTML document
Definition at line 228 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_cssuri.
String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getHTMLFragment (final PegDownProcessor p_processor, final URL p_file) throws IOException private
Parameters
p_processor markdown processor
p_file URL of the file
Returns
HTML fragment
Definition at line 244 of file CMarkdownRenderer.java.
final String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getMimeType ()
Returns
string with mimetype
Definition at line 132 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_htmltype.
String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getURL (final String p_url) private
Parameters
p_url input URL
Returns
URL with base URI
Definition at line 255 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_baseuri.
Referenced by de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render().
String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getWikipediaLink (final String p_language, final String p_search) throws UnsupportedEncodingException private
Parameters
p_language language prefix
p_search search content
Returns
full URL
Definition at line 267 of file CMarkdownRenderer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render().
boolean de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.isURL (final String p_url) private
Parameters
p_url string with URL
Returns
boolean for URL existance
Definition at line 278 of file CMarkdownRenderer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render().
final Rendering de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render (final ExpLinkNode p_node, final String p_text)
Definition at line 147 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getURL(), and de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.isURL().
final Rendering de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render (final ExpImageNode p_node, final String p_text)
Definition at line 161 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.isURL().
final Rendering de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render (final WikiLinkNode p_node)
Definition at line 175 of file CMarkdownRenderer.java.
References de.tu_clausthal.in.mec.CConfiguration.getInstance(), and de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getWikipediaLink().
Member Data Documentation
final String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_baseuri private
Definition at line 52 of file CMarkdownRenderer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer(), and de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getURL().
final String de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_cssuri private
Definition at line 56 of file CMarkdownRenderer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer(), and de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getHTMLDocument().
final EHTMLType de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.m_htmltype private
Definition at line 60 of file CMarkdownRenderer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.CMarkdownRenderer(), de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getHTML(), and de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.getMimeType().