MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.car.graph.CGraphHopper Class Reference
de.tu_clausthal.in.mec.object.car.graph.CGraphHopper Class Reference
class for create a graph structure of OSM data, the class downloads the data and creates edges and verticies
Inherits GraphHopper.
Classes
enum EWeight
enum with weighting
Public Member Functions
CGraphHopper (final int p_cellsize)
ctor
CGraphHopper (final String p_encoding, final int p_cellsize)
ctor
final synchronized void addEdgeListener (final IAction< ICar,?> p_listener)
adds an edge listener
final synchronized void clear ()
clears all edges
Weighting createWeighting (final WeightingMap p_map, final FlagEncoder p_encoder)
final boolean existWeight (final EWeight p_weight)
checks if a weight object exists
final int getClosestEdge (final GeoPosition p_position)
returns the closest edge(s) of a geo position
final int getClosestNode (final GeoPosition p_position)
returns the ID of the closest node
final CEdge< ICar,?> getEdge (final EdgeIteratorState p_edgestate)
returns the linkage between edge and car
final Collection< CEdge< ICar,?> > getEdgeCollection ()
returns the edge collection
final EdgeIteratorState getEdgeIterator (final int p_edgeid)
returns an iterator state of an edge
final double getEdgeSpeed (final EdgeIteratorState p_edge)
returns the max.
final int getNumberOfObjects ()
number of cars
final ArrayList< Pair
< EdgeIteratorState, Integer > > getRouteCells (final List< EdgeIteratorState > p_route)
creates the full path of cells with the edge value
final List< List
< EdgeIteratorState > > getRoutes (final GeoPosition p_start, final GeoPosition p_end)
creates a list of list of edge between two geopositions
final List< List
< EdgeIteratorState > > getRoutes (final GeoPosition p_start, final GeoPosition p_end, final int p_maxroutes)
creates a list of list of edge between two geopositions
final List< List
< EdgeIteratorState > > getRoutes (final GeoPosition p_start, final GeoPosition p_end, final String p_weighting)
creates a list of list of edge between two geopositions
final List< List
< EdgeIteratorState > > getRoutes (final GeoPosition p_start, final GeoPosition p_end, final EWeight p_weighting, final int p_maxroutes)
creates a list of list of edge between two geopositions
final< T extends Weighting > T getWeight (final EWeight p_weight)
returns a weight object by name
Static Public Member Functions
static void deleteGraph (final String p_url)
deletes a graph by URL
Private Member Functions
void downloadGraphAndLoad (final String p_url, final File p_directory)
download graph and run converting
final File downloadOSMData (final String p_url)
downloads the OSM data
Static Private Member Functions
static String getCurrentGraph ()
gets the current graph with its download URL from the configuration
static File getGraphLocation (final String p_url)
returns the full path of a graph location
Private Attributes
final int m_cellsize
cell size for sampling
final Map< Integer, CEdge
< ICar,?> > m_edgecell = new ConcurrentHashMap<>()
map with edge-cell connection
final Set< IAction< ICar,?> > m_edgelister = new HashSet<>()
set with listerner of the edges
final Map< EWeight, Weighting > m_weights = new HashMap<>()
map with additional weights
Static Private Attributes
static final String c_defaultflagencoding = "CAR"
Detailed Description
Todo:
remove ICar interface
See Also
http://graphhopper.com/
Definition at line 70 of file CGraphHopper.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper (final int p_cellsize)
Parameters
p_cellsize cellsize in meter for sampling
Definition at line 98 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.c_defaultflagencoding.
de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper (final String p_encoding, final int p_cellsize)
Parameters
p_encoding flag encoder name
p_cellsize cellsize in meter for sampling
See Also
https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
Definition at line 110 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.EWeight.Default, de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getCurrentGraph(), de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getGraphLocation(), de.tu_clausthal.in.mec.CConfiguration.getInstance(), de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_cellsize, and de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_weights.
Member Function Documentation
final synchronized void de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.addEdgeListener (final IAction< ICar,?> p_listener)
Note
listener object will be set at the edge instantiation process
Definition at line 161 of file CGraphHopper.java.
final synchronized void de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.clear ()
Definition at line 169 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_edgecell.
Weighting de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.createWeighting (final WeightingMap p_map, final FlagEncoder p_encoder)
Definition at line 176 of file CGraphHopper.java.
static void de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.deleteGraph (final String p_url) static
Parameters
p_url URL
Definition at line 409 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getGraphLocation().
Referenced by de.tu_clausthal.in.mec.CConfiguration.web_static_deletegraph().
void de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.downloadGraphAndLoad (final String p_url, final File p_directory) private
Parameters
p_url download URL
p_directory directory in which the graph data is stored
Definition at line 430 of file CGraphHopper.java.
final File de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.downloadOSMData (final String p_url) private
Parameters
p_url URL for downloading as string
Returns
download file with full path
Definition at line 469 of file CGraphHopper.java.
final boolean de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.existWeight (final EWeight p_weight)
Parameters
p_weight weight
Returns
existance
Definition at line 212 of file CGraphHopper.java.
final int de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getClosestEdge (final GeoPosition p_position)
Parameters
p_position geo position
Returns
ID of the edge
Definition at line 223 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdge().
final int de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getClosestNode (final GeoPosition p_position)
Parameters
p_position geo position
Returns
ID of the node
Definition at line 235 of file CGraphHopper.java.
static String de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getCurrentGraph () static private
Returns
string URL
Definition at line 445 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper().
final CEdge<ICar, ?> de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdge (final EdgeIteratorState p_edgestate)
Parameters
p_edgestate edge object
Returns
linkage object
Note
listener object will be set at the edge instantiation process
Definition at line 249 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_cellsize, and de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_edgelister.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getClosestEdge().
final Collection<CEdge<ICar, ?> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdgeCollection ()
Returns
collection
Definition at line 419 of file CGraphHopper.java.
final EdgeIteratorState de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdgeIterator (final int p_edgeid)
Parameters
p_edgeid edge ID
Returns
iterator
Definition at line 267 of file CGraphHopper.java.
final double de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdgeSpeed (final EdgeIteratorState p_edge)
speed of an edge
Parameters
p_edge edge ID
Returns
speed
Definition at line 278 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.c_defaultflagencoding.
static File de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getGraphLocation (final String p_url) static private
Parameters
p_url download URL
Returns
graph path location
Definition at line 456 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.common.CCommon.getHash().
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper(), and de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.deleteGraph().
final int de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getNumberOfObjects ()
Returns
number of cars on the graph
Definition at line 291 of file CGraphHopper.java.
final ArrayList<Pair<EdgeIteratorState, Integer> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRouteCells (final List< EdgeIteratorState > p_route)
Parameters
p_route edge list
Returns
list with pair of edge and cell position
Definition at line 302 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.waypoint.factory.ICarFactory.generateRouteCells().
final List<List<EdgeIteratorState> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRoutes (final GeoPosition p_start, final GeoPosition p_end)
Parameters
p_start start geoposition
p_end end geoposition
Returns
list of list of edges
Definition at line 322 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.EWeight.Default.
final List<List<EdgeIteratorState> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRoutes (final GeoPosition p_start, final GeoPosition p_end, final int p_maxroutes)
Parameters
p_start start geoposition
p_end end geoposition
p_maxroutes max. number of paths
Returns
list of list of edges
Definition at line 335 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.EWeight.Default.
final List<List<EdgeIteratorState> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRoutes (final GeoPosition p_start, final GeoPosition p_end, final String p_weighting)
Parameters
p_start start geoposition
p_end end geoposition
p_weighting weigtning name
Returns
list of list of edges
Definition at line 348 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.EWeight.Default.
final List<List<EdgeIteratorState> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRoutes (final GeoPosition p_start, final GeoPosition p_end, final EWeight p_weighting, final int p_maxroutes)
Parameters
p_start start geoposition
p_end end geoposition
p_weighting weigting name
p_maxroutes max. number of paths
Returns
list of list of edges
Definition at line 362 of file CGraphHopper.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.EWeight.Default, de.tu_clausthal.in.mec.CLogger.error(), and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
final<T extends Weighting> T de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getWeight (final EWeight p_weight)
Parameters
p_weight weight
Returns
weight object
Template Parameters
T type of the weight object
Definition at line 201 of file CGraphHopper.java.
Member Data Documentation
final String de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.c_defaultflagencoding = "CAR" static private
Definition at line 72 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper(), and de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdgeSpeed().
final int de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_cellsize private
Definition at line 76 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper(), and de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdge().
final Map<Integer, CEdge<ICar, ?> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_edgecell = new ConcurrentHashMap<>() private
Definition at line 80 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.clear().
final Set<IAction<ICar, ?> > de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_edgelister = new HashSet<>() private
Definition at line 84 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getEdge().
final Map<EWeight, Weighting> de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.m_weights = new HashMap<>() private
Note
alle names must be in lower-case
Definition at line 90 of file CGraphHopper.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper().