MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CWaypointEnvironment Class Reference
de.tu_clausthal.in.mec.ui.CWaypointEnvironment Class Reference
ui bundle which is responsible for the waypoint-tool settings
Classes
enum EFactory
enum for factories
enum EGenerator
generator enum
enum EWaypoint
enum for waypoints
Public Member Functions
CWaypointEnvironment ()
ctor to define the waypoint environment
final void setWaypoint (final GeoPosition p_position)
creates a waypoint
Private Member Functions
AbstractRealDistribution createDistribution (final CNameHashMap.CImmutable p_object)
creates from a map object an distribution object
final Map< String, String > web_static_labelmainmenu ()
returns all static label information for main menu
final Map< String, String > web_static_labelpresetwizard ()
returns all static label information for wizard
final Map< String, Object > web_static_listdistribution ()
list all possible distribution types
final Map< String, Map< String,
Object > > web_static_listfactory ()
list all possible factory types
final Map< String, String > web_static_listgenerator ()
list all possible generator types
final Map< String, String > web_static_listwaypoint ()
list all possible waypoint types
final Map< String, String > web_static_listweight ()
list all possible routing weights
final void web_static_set (final Map< String, Object > p_data)
creates the current settings of
Private Attributes
final Map< String, Object > m_currentsettings = new HashMap<>()
map with objects, which are created by the UI call
Static Private Attributes
static final Map< String, Object > c_distribution
map with distribution names
static final Map< String, Map
< String, Object > > c_factory
map with factory names
static final Map< String, String > c_generator
map with name and ID
static final Map< String, String > c_labelmainmenu
static label for main menu UI
static final Map< String, String > c_labelpresetwizard
static label for preset wizard UI
static final Map< String, String > c_waypoint
map with name and ID
static final Map< String, String > c_weights
map with name and ID
Detailed Description
Definition at line 53 of file CWaypointEnvironment.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.CWaypointEnvironment.CWaypointEnvironment ()
Definition at line 192 of file CWaypointEnvironment.java.
Member Function Documentation
AbstractRealDistribution de.tu_clausthal.in.mec.ui.CWaypointEnvironment.createDistribution (final CNameHashMap.CImmutable p_object) private
Parameters
p_object map object
Returns
distribution object
Definition at line 226 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_set().
final void de.tu_clausthal.in.mec.ui.CWaypointEnvironment.setWaypoint (final GeoPosition p_position)
Parameters
p_position geoposition of the waypoint
Definition at line 203 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.ui.CWaypointEnvironment.m_currentsettings.
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_labelmainmenu () private
Returns
map with static labels
Definition at line 239 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_labelmainmenu.
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_labelpresetwizard () private
Returns
map with static labels
Definition at line 249 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_labelpresetwizard.
final Map<String, Object> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listdistribution () private
Returns
map with names of distribution and IDs
Definition at line 259 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_distribution.
final Map<String, Map<String, Object> > de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listfactory () private
Returns
map with language name and map of ID and required-agent-program flag
Definition at line 269 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_factory.
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listgenerator () private
Returns
map with language name and ID
Definition at line 279 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_generator.
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listwaypoint () private
Returns
map with language name and ID
Definition at line 299 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_waypoint.
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listweight () private
Returns
map with language name and ID
Definition at line 289 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_weights.
final void de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_set (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 309 of file CWaypointEnvironment.java.
References de.tu_clausthal.in.mec.ui.CWaypointEnvironment.createDistribution().
Member Data Documentation
final Map<String, Object> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_distribution static private
Initial value:
= new HashMap<String, Object>()
    {{
        for ( final EDistribution l_distribution : EDistribution.values() )
            put(
                    l_distribution.toString(), new HashMap()
                    {{
                        put( "firstmomentum", CCommon.getMap( "label", l_distribution.getFirstMomentum(), "used", l_distribution.hasFirstMomentum() ) );
                        put(
                                "secondmomentum", CCommon.getMap(
                                        "label", l_distribution.getSecondMomentum(), "used", l_distribution.hasSecondMomentum()
                                )
                        );
                        put( "id", l_distribution.name() );
                    }}
            );
    }}
Definition at line 58 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listdistribution().
final Map<String, Map<String, Object> > de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_factory static private
Initial value:
= new HashMap<String, Map<String, Object>>()
    {{
        for ( final EFactory l_factory : EFactory.values() )
            put(
                    l_factory.toString(), new HashMap()
                    {{
                        put( "requireagent", l_factory.getRequireAgent() );
                        put( "id", l_factory.name() );
                    }}
            );
    }}
Definition at line 78 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listfactory().
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_generator static private
Initial value:
= new HashMap<String, String>()
    {{
        for ( final EGenerator l_generator : EGenerator.values() )
            put( l_generator.toString(), l_generator.name() );
    }}
Definition at line 92 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listgenerator().
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_labelmainmenu static private
Initial value:
= new HashMap<String, String>()
    {{
        put( "name", CCommon.getResourceString( CWaypointEnvironment.class, "ui_waypoint_name" ) );
        put( "id_newpreset", CCommon.getResourceString( CWaypointEnvironment.class, "ui_mainmenu_id_newpreset" ) );
        put( "id_listpreset", CCommon.getResourceString( CWaypointEnvironment.class, "ui_mainmenu_id_listpreset" ) );
    }}
Definition at line 108 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_labelmainmenu().
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_labelpresetwizard static private
Definition at line 117 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_labelpresetwizard().
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_waypoint static private
Initial value:
= new HashMap<String, String>()
    {{
        for ( final EWaypoint l_waypoint : EWaypoint.values() )
            put( l_waypoint.toString(), l_waypoint.name() );
    }}
Definition at line 178 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listwaypoint().
final Map<String, String> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.c_weights static private
Initial value:
= new HashMap<String, String>()
    {{
        for ( final CGraphHopper.EWeight l_weight : CGraphHopper.EWeight.values() )
            put( l_weight.toString(), l_weight.name() );
    }}
Definition at line 100 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.web_static_listweight().
final Map<String, Object> de.tu_clausthal.in.mec.ui.CWaypointEnvironment.m_currentsettings = new HashMap<>() private
Definition at line 186 of file CWaypointEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CWaypointEnvironment.setWaypoint().