MecSim - Traffic Simulation: de.tu_clausthal.in.mec.runtime.message.CMessageSystem Class Reference
de.tu_clausthal.in.mec.runtime.message.CMessageSystem Class Reference
message handler class
Classes
interface IActionListener
observer interface *
Public Member Functions
final void addActionListener (final IActionListener p_listener)
adds a listener
final synchronized void pushMessage (final CPath p_receiverpath, final IMessage<?> p_message)
pushs a message to the queue
final synchronized void register (final CPath p_path, final IParticipant p_receiver)
register a new participant
final void release ()
release function to remove object *
final void removeListener (final IActionListener p_listener)
removes a listener
final void step (final int p_currentstep, final ILayer p_layer) throws Exception
step method
final synchronized void unregister (final CPath p_path, final IParticipant p_receiver)
unregister a participant
Private Member Functions
void incrementMessageFlow (final CPath p_row, final CPath p_colum)
increments the message flow
void web_dynamic_flow (final CWebSocket.EAction p_action, final CWebSocket.CCommunicator p_communicator, final CWebSocket.CFrame p_frame)
UI method - message counting information.
Private Attributes
final CSocketStorage m_communicator = new CSocketStorage()
set with all communicators
final Set< IActionListener > m_listener = new HashSet<>()
event listener *
final CAdjacencyMatrix< CPath,
Integer > m_messageflow = new CAdjacencyMatrix<>("source", "target")
message counter
final CTreeNode< Pair< Set
< IParticipant >, Set
< IMessage > > > m_root = new CTreeNode(this.toString())
tree structure of all objects (root-node is equal to this object)
Detailed Description
Definition at line 46 of file CMessageSystem.java.
Member Function Documentation
final void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.addActionListener (final IActionListener p_listener)
Parameters
p_listener listener
Definition at line 70 of file CMessageSystem.java.
void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.incrementMessageFlow (final CPath p_row, final CPath p_colum) private
Parameters
p_row row value of the adjacency matrix
p_colum column value of the adjacency matrix
Definition at line 215 of file CMessageSystem.java.
References de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_messageflow.
Referenced by de.tu_clausthal.in.mec.runtime.message.CMessageSystem.pushMessage().
final synchronized void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.pushMessage (final CPath p_receiverpath, final IMessage<?> p_message)
Parameters
p_receiverpath receiver
p_message message
Definition at line 81 of file CMessageSystem.java.
References de.tu_clausthal.in.mec.runtime.message.CMessageSystem.incrementMessageFlow(), de.tu_clausthal.in.mec.common.CPath.isEmpty(), de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_listener, and de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_root.
final synchronized void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.register (final CPath p_path, final IParticipant p_receiver)
Parameters
p_path path of the receiver
p_receiver participant
Definition at line 131 of file CMessageSystem.java.
References de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_listener.
final void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.release ()
Implements de.tu_clausthal.in.mec.runtime.ISteppable.
Definition at line 151 of file CMessageSystem.java.
final void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.removeListener (final IActionListener p_listener)
Parameters
p_listener listener
Definition at line 161 of file CMessageSystem.java.
final void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.step (final int p_currentstep, final ILayer p_layer) throws Exception
Parameters
p_currentstep current step value
p_layer layer on which is the object push or null
Implements de.tu_clausthal.in.mec.runtime.IVoidSteppable.
Definition at line 167 of file CMessageSystem.java.
References de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_messageflow, and de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_root.
final synchronized void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.unregister (final CPath p_path, final IParticipant p_receiver)
Parameters
p_path path of the receiver
p_receiver participant
Definition at line 192 of file CMessageSystem.java.
References de.tu_clausthal.in.mec.common.CPath.isEmpty(), and de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_listener.
void de.tu_clausthal.in.mec.runtime.message.CMessageSystem.web_dynamic_flow (final CWebSocket.EAction p_action, final CWebSocket.CCommunicator p_communicator, final CWebSocket.CFrame p_frame) private
Definition at line 227 of file CMessageSystem.java.
Member Data Documentation
final CSocketStorage de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_communicator = new CSocketStorage() private
Definition at line 51 of file CMessageSystem.java.
final Set<IActionListener> de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_listener = new HashSet<>() private
Definition at line 55 of file CMessageSystem.java.
Referenced by de.tu_clausthal.in.mec.runtime.message.CMessageSystem.pushMessage(), de.tu_clausthal.in.mec.runtime.message.CMessageSystem.register(), and de.tu_clausthal.in.mec.runtime.message.CMessageSystem.unregister().
final CAdjacencyMatrix<CPath, Integer> de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_messageflow = new CAdjacencyMatrix<>("source", "target") private
Definition at line 59 of file CMessageSystem.java.
Referenced by de.tu_clausthal.in.mec.runtime.message.CMessageSystem.incrementMessageFlow(), and de.tu_clausthal.in.mec.runtime.message.CMessageSystem.step().
final CTreeNode<Pair<Set<IParticipant>, Set<IMessage> > > de.tu_clausthal.in.mec.runtime.message.CMessageSystem.m_root = new CTreeNode(this.toString()) private
Definition at line 63 of file CMessageSystem.java.
Referenced by de.tu_clausthal.in.mec.runtime.message.CMessageSystem.pushMessage(), and de.tu_clausthal.in.mec.runtime.message.CMessageSystem.step().