MecSim - Traffic Simulation: de.tu_clausthal.in.mec.runtime.message.CNames Class Reference
de.tu_clausthal.in.mec.runtime.message.CNames Class Reference
create a global message name structure
Static Public Member Functions
static CPath getName (final Object p_object, final String p_name)
creates a full name
static CPath getName (final Object p_object)
creates a full name
Static Protected Member Functions
static CPath getGroup (final Object p_object)
creates the group path
Detailed Description
Definition at line 36 of file CNames.java.
Member Function Documentation
static CPath de.tu_clausthal.in.mec.runtime.message.CNames.getGroup (final Object p_object) static protected
Parameters
p_object object
Returns
group path
Definition at line 70 of file CNames.java.
Referenced by de.tu_clausthal.in.mec.runtime.message.CNames.getName().
static CPath de.tu_clausthal.in.mec.runtime.message.CNames.getName (final Object p_object, final String p_name) static
Parameters
p_object object
p_name name
Returns
fqn path
Definition at line 46 of file CNames.java.
References de.tu_clausthal.in.mec.runtime.message.CNames.getGroup().
Referenced by de.tu_clausthal.in.mec.runtime.message.CNames.getName().
static CPath de.tu_clausthal.in.mec.runtime.message.CNames.getName (final Object p_object) static
Parameters
p_object object
Returns
fqn path
Definition at line 59 of file CNames.java.
References de.tu_clausthal.in.mec.runtime.message.CNames.getName().