MecSim - Traffic Simulation: de.tu_clausthal.in.mec.CMain Class Reference
de.tu_clausthal.in.mec.CMain Class Reference
main class of the application
Static Public Member Functions
static void main (final String[] p_args)
main program
Private Member Functions
CMain ()
private ctor - avoid instantiation
Detailed Description
Definition at line 45 of file CMain.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.CMain.CMain () private
Definition at line 50 of file CMain.java.
Member Function Documentation
static void de.tu_clausthal.in.mec.CMain.main (final String[] p_args) static
Parameters
p_args commandline arguments
Definition at line 59 of file CMain.java.
References de.tu_clausthal.in.mec.runtime.benchmark.CSummary.getInstance(), de.tu_clausthal.in.mec.CConfiguration.getInstance(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.ui.CUI.main(), de.tu_clausthal.in.mec.CLogger.out(), and de.tu_clausthal.in.mec.common.CCommon.startupchecks().