MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.analysis.IDatabase Class Reference
de.tu_clausthal.in.mec.object.analysis.IDatabase Class Reference abstract
class for writing data into a database
Classes
class CWorker
worker class to push data to the database *
Public Member Functions
IDatabase ()
ctor - context initialization
final int getCalculationIndex ()
Protected Member Functions
final void createTable (final String p_tablename, final String[] p_fields, final String p_alter)
creates the table structure
final void createTable (final String p_tablename, final String[] p_fields, final String[] p_alter)
creates the table structure
final String getTableName (final String p_tablename)
returns the full table name
Static Protected Member Functions
static boolean isConnectable ()
check if database is connectable
Static Protected Attributes
static final BasicDataSource c_datasource
datasource connection pool (static context)
Private Attributes
final boolean m_connectable = isConnectable()
flag to set connectivity
final String m_tableprefix = Optional.ofNullable(CConfiguration.getInstance().get().<String>get("database/tableprefix")).orElse("")
table prefix
Detailed Description
Note
JDBC driver is needed
See Also
http://commons.apache.org/proper/commons-dbcp/
Definition at line 46 of file IDatabase.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.analysis.IDatabase.IDatabase ()
Definition at line 74 of file IDatabase.java.
References de.tu_clausthal.in.mec.object.analysis.IDatabase.m_connectable.
Member Function Documentation
final void de.tu_clausthal.in.mec.object.analysis.IDatabase.createTable (final String p_tablename, final String[] p_fields, final String p_alter) protected
Parameters
p_tablename table name
p_fields field list
p_alter optional table alter command
Definition at line 108 of file IDatabase.java.
final void de.tu_clausthal.in.mec.object.analysis.IDatabase.createTable (final String p_tablename, final String[] p_fields, final String[] p_alter) protected
Parameters
p_tablename table name
p_fields field list
p_alter optional table alter commands
Definition at line 121 of file IDatabase.java.
References de.tu_clausthal.in.mec.object.analysis.IDatabase.c_datasource, and de.tu_clausthal.in.mec.CLogger.info().
final int de.tu_clausthal.in.mec.object.analysis.IDatabase.getCalculationIndex ()
Definition at line 80 of file IDatabase.java.
final String de.tu_clausthal.in.mec.object.analysis.IDatabase.getTableName (final String p_tablename) protected
Parameters
p_tablename table name
Returns
full table name
Definition at line 157 of file IDatabase.java.
References de.tu_clausthal.in.mec.object.analysis.IDatabase.m_tableprefix.
Referenced by de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.createInsertStatement().
static boolean de.tu_clausthal.in.mec.object.analysis.IDatabase.isConnectable () static protected
Returns
boolean of connectivity
Definition at line 90 of file IDatabase.java.
Member Data Documentation
final BasicDataSource de.tu_clausthal.in.mec.object.analysis.IDatabase.c_datasource static protected
Initial value:
= new BasicDataSource()
    {{
        if ( isConnectable() )
        {
            setDriverClassName( CConfiguration.getInstance().get().<String>get( "database/driver" ) );
            setUrl( CConfiguration.getInstance().get().<String>get( "database/url" ) );
            setUsername( CConfiguration.getInstance().get().<String>get( "database/username" ) );
            setPassword( CConfiguration.getInstance().get().<String>get( "database/password" ) );
            setPoolPreparedStatements( true );
        }
    }}
Definition at line 51 of file IDatabase.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.IDatabase.createTable().
final boolean de.tu_clausthal.in.mec.object.analysis.IDatabase.m_connectable = isConnectable() private
Definition at line 65 of file IDatabase.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.IDatabase.IDatabase().
final String de.tu_clausthal.in.mec.object.analysis.IDatabase.m_tableprefix = Optional.ofNullable(CConfiguration.getInstance().get().<String>get("database/tableprefix")).orElse("") private
Definition at line 69 of file IDatabase.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.IDatabase.getTableName().