MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CUI Class Reference
de.tu_clausthal.in.mec.ui.CUI Class Reference
JavaFX application.
Inherits Application.
Public Member Functions
final void add (final String p_title, final Node p_node)
adds a new tab to the UI
final< T extends Node > T get (final String p_name)
returns a tab / node
final void start (final Stage p_stage) throws Exception
Static Public Member Functions
static void main (final String[] p_args)
main-wrapper method
Private Member Functions
PopOver createPopOver (final String p_title, final Node p_node)
creates a new pop window
Tab createTab (final String p_title, final Node p_node)
creates a new tab - adds the tab to the global tab pane
void stageInitialization (final Stage p_stage)
state initialization
void stageLayoutInitialization (final Stage p_stage)
stage layout initialization
Private Attributes
final Map< String, Node > m_content = new HashMap<>()
map with name and content
final EventHandler< WindowEvent > m_popuphiddenevent
hidden event handler
Stage m_stage
main stage *
final EventHandler< Event > m_tabcloseevent
tab close handler
final TabPane m_tabpane = new TabPane()
tab list *
final Map< Node, Pair< PopOver,
Tab > > m_widget = new HashMap<>()
map with nodes (of tab content) and pair of dockables and tab
Detailed Description
Bug:
undock structure does not work correctly
See Also
https://arnaudnouard.wordpress.com/2013/02/02/undecorator-add-a-better-look-to-your-javafx-stages-part-i/
http://docs.oracle.com/javafx/2/layout/style_css.htm#CHDHIGCA
Definition at line 58 of file CUI.java.
Member Function Documentation
final void de.tu_clausthal.in.mec.ui.CUI.add (final String p_title, final Node p_node)
Parameters
p_title name of the node
p_node node
Definition at line 127 of file CUI.java.
References de.tu_clausthal.in.mec.ui.CUI.createTab(), de.tu_clausthal.in.mec.ui.CUI.m_content, and de.tu_clausthal.in.mec.ui.CUI.m_widget.
Referenced by de.tu_clausthal.in.mec.ui.CUI.createTab().
PopOver de.tu_clausthal.in.mec.ui.CUI.createPopOver (final String p_title, final Node p_node) private
Parameters
p_title title
p_node node
Returns
popup
Definition at line 166 of file CUI.java.
References de.tu_clausthal.in.mec.ui.CUI.m_popuphiddenevent.
Tab de.tu_clausthal.in.mec.ui.CUI.createTab (final String p_title, final Node p_node) private
Parameters
p_title title
p_node node
Returns
tab
Definition at line 187 of file CUI.java.
References de.tu_clausthal.in.mec.ui.CUI.add(), and de.tu_clausthal.in.mec.ui.CUI.m_tabcloseevent.
Referenced by de.tu_clausthal.in.mec.ui.CUI.add().
final<T extends Node> T de.tu_clausthal.in.mec.ui.CUI.get (final String p_name)
Parameters
p_name name of the tab
Returns
node or null
Template Parameters
T node type
Definition at line 145 of file CUI.java.
static void de.tu_clausthal.in.mec.ui.CUI.main (final String[] p_args) static
Parameters
p_args start arguments
Definition at line 116 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.CMain.main().
void de.tu_clausthal.in.mec.ui.CUI.stageInitialization (final Stage p_stage) private
Parameters
p_stage main stage
Definition at line 206 of file CUI.java.
References de.tu_clausthal.in.mec.ui.CUI.m_stage.
void de.tu_clausthal.in.mec.ui.CUI.stageLayoutInitialization (final Stage p_stage) private
Parameters
p_stage main stage
Definition at line 240 of file CUI.java.
References de.tu_clausthal.in.mec.ui.CUI.m_tabpane.
final void de.tu_clausthal.in.mec.ui.CUI.start (final Stage p_stage) throws Exception
Definition at line 151 of file CUI.java.
Member Data Documentation
final Map<String, Node> de.tu_clausthal.in.mec.ui.CUI.m_content = new HashMap<>() private
Definition at line 63 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.ui.CUI.add().
final EventHandler<WindowEvent> de.tu_clausthal.in.mec.ui.CUI.m_popuphiddenevent private
Initial value:
= new EventHandler<WindowEvent>()
    {
        @Override
        public void handle( final WindowEvent p_event )
        {
            p_event.consume();
            final Node l_node = ( (PopOver) p_event.getSource() ).getContentNode();
            if ( !m_widget.containsKey( l_node ) )
                return;
            m_tabpane.getTabs().add( m_widget.get( l_node ).getValue() );
        }
    }
Definition at line 79 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.ui.CUI.createPopOver().
Stage de.tu_clausthal.in.mec.ui.CUI.m_stage private
Definition at line 67 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.ui.CUI.stageInitialization().
final EventHandler<Event> de.tu_clausthal.in.mec.ui.CUI.m_tabcloseevent private
Initial value:
= new EventHandler<Event>()
    {
        @Override
        public void handle( final Event p_event )
        {
            p_event.consume();
            final Tab l_tab = (Tab) p_event.getSource();
            if ( !m_widget.containsKey( l_tab.getContent() ) )
                return;
            m_widget.get( l_tab.getContent() ).getKey().show( m_stage );
        }
    }
Definition at line 96 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.ui.CUI.createTab().
final TabPane de.tu_clausthal.in.mec.ui.CUI.m_tabpane = new TabPane() private
Definition at line 71 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.ui.CUI.stageLayoutInitialization().
final Map<Node, Pair<PopOver, Tab> > de.tu_clausthal.in.mec.ui.CUI.m_widget = new HashMap<>() private
Definition at line 75 of file CUI.java.
Referenced by de.tu_clausthal.in.mec.ui.CUI.add().