MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase Class Reference
de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase Class Reference
beliefbase which wraps all Jason structures
Inherits BeliefBase, and IGenerator< Literal >.
Public Member Functions
CTreeBeliefBase ()
ctor
boolean abolish (final PredicateIndicator p_predict)
void add (final CPath p_path, final IBeliefBaseMask< Literal > p_mask)
adds a mask to the beliefbase
boolean add (final Literal p_literal)
boolean add (final int p_index, final Literal p_literal)
void bind (final String p_bindname, final Object p_bind)
bind an object to the binding-beliefbase
void clear ()
BeliefBase clone ()
Literal contains (final Literal p_literal)
IBeliefBaseMask< Literal > createBeliefbase (final String p_name)
void generateTreeStructure (final Literal p_literal, final boolean p_addliteral)
adds a literal and its belief structure to the agent beliefbase
Iterator< Literal > getAll ()
Element getAsDOM (final Document p_document)
Iterator< Literal > getCandidateBeliefs (final PredicateIndicator p_predict)
Iterator< Literal > getCandidateBeliefs (final Literal p_literal, final Unifier p_unify)
Iterator< Literal > getPercepts ()
Iterator< Literal > getRelevant (final Literal p_literal)
IBeliefBaseMask< Literal > getRootMask ()
returns the root mask
void init (final Agent ag, final String[] args)
Iterator< Literal > iterator ()
void remove (final CPath p_path)
removes an item from the bliefbase
boolean remove (final Literal p_literal)
void setMessageBeliefbase (final Agent p_agent, final String p_agentnameseparator)
set agent to the beliefbase for message system, can be set once
void setMessages (final Set< IMessage > p_messages)
sets the messages to the message-beliefbase
int size ()
void stop ()
void unbind (final String p_bindname)
unbind an object from the binding-beliefbase
void update ()
updates all internal data structures, should be called on the agent cycle
Private Member Functions
Pair< CPath, CLiteral > createPathLiteral (final Literal p_literal)
creates a generic literal with path
Iterator< Literal > getLiteralIterator (final Iterator< ILiteral< Literal >> p_iterator)
get literal iterator
CPath splitLiteralPath (final String p_functor)
splits the literal path
Private Attributes
final CMask m_mask = new CBeliefBase(new CBeliefStorage<>(), c_agentbeliefseparator).createMask(c_beliefbaseroot.getSuffix())
root beliefbase
Static Private Attributes
static final String c_agentbeliefseparator = "_"
path separator of agent belief
static final CPath c_beliefbasebind = new CPath("bind")
name of the binding beliefbase and its mask
static final CPath c_beliefbasemessage = new CPath("message")
name of the message beliefbase and its mask
static final CPath c_beliefbaseroot = new CPath("root")
name of the root beliefbase and its mask
static final String c_beliefbindprefixreplace = "m_"
binding replacing prefix - the prefix will be removed from the binding belief name
Detailed Description
Definition at line 51 of file CTreeBeliefBase.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.CTreeBeliefBase ()
Definition at line 83 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_agentbeliefseparator, de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasebind, de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbindprefixreplace, and de.tu_clausthal.in.mec.common.CPath.getSuffix().
Member Function Documentation
boolean de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.abolish (final PredicateIndicator p_predict)
Definition at line 311 of file CTreeBeliefBase.java.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.add (final CPath p_path, final IBeliefBaseMask< Literal > p_mask)
Definition at line 160 of file CTreeBeliefBase.java.
boolean de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.add (final Literal p_literal)
Definition at line 232 of file CTreeBeliefBase.java.
boolean de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.add (final int p_index, final Literal p_literal)
Definition at line 238 of file CTreeBeliefBase.java.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.bind (final String p_bindname, final Object p_bind)
Parameters
p_bindname bind name
p_bind bind object
Definition at line 121 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasebind.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.clear ()
Definition at line 226 of file CTreeBeliefBase.java.
BeliefBase de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.clone ()
Todo:
define a full deep-copy
Definition at line 330 of file CTreeBeliefBase.java.
Literal de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.contains (final Literal p_literal)
Definition at line 281 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.m_mask.
IBeliefBaseMask<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.createBeliefbase (final String p_name)
Definition at line 208 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_agentbeliefseparator.
Pair<CPath, CLiteral> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.createPathLiteral (final Literal p_literal) private
Parameters
p_literal input literal
Returns
pair of literal path and generic literal
Definition at line 341 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.common.CPath.getSuffix().
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.generateTreeStructure (final Literal p_literal, final boolean p_addliteral)
Parameters
p_literal literal with prefix
p_addliteral adds the literal to the created structure
Definition at line 196 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CAgent< T >.performtemplate().
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getAll ()
Definition at line 252 of file CTreeBeliefBase.java.
Element de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getAsDOM (final Document p_document)
Definition at line 317 of file CTreeBeliefBase.java.
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getCandidateBeliefs (final PredicateIndicator p_predict)
Definition at line 259 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getLiteralIterator().
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getCandidateBeliefs (final Literal p_literal, final Unifier p_unify)
Definition at line 267 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getLiteralIterator().
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getLiteralIterator (final Iterator< ILiteral< Literal >> p_iterator) private
Returns
iterator
Definition at line 376 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getCandidateBeliefs().
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getPercepts ()
Definition at line 298 of file CTreeBeliefBase.java.
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getRelevant (final Literal p_literal)
Definition at line 274 of file CTreeBeliefBase.java.
IBeliefBaseMask<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getRootMask ()
Returns
root mask
Definition at line 141 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.m_mask.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.init (final Agent ag, final String[] args)
Definition at line 214 of file CTreeBeliefBase.java.
Iterator<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.iterator ()
Definition at line 246 of file CTreeBeliefBase.java.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.remove (final CPath p_path)
Parameters
p_path item path
Definition at line 152 of file CTreeBeliefBase.java.
boolean de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.remove (final Literal p_literal)
Definition at line 304 of file CTreeBeliefBase.java.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessageBeliefbase (final Agent p_agent, final String p_agentnameseparator)
Parameters
p_agent agent which will be connected with the beliefbase
p_agentnameseparator agent name seperator used by the message beliefbase
Definition at line 102 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_agentbeliefseparator, de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasemessage, de.tu_clausthal.in.mec.common.CPath.getSuffix(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.m_mask.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessages (final Set< IMessage > p_messages)
Parameters
p_messages set of messages
Definition at line 171 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasemessage, and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.m_mask.
int de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.size ()
Definition at line 292 of file CTreeBeliefBase.java.
CPath de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.splitLiteralPath (final String p_functor) private
Parameters
p_functor input literal functor
Returns
path
Definition at line 360 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_agentbeliefseparator, de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbaseroot, de.tu_clausthal.in.mec.common.CPath.remove(), de.tu_clausthal.in.mec.common.CPath.size(), and de.tu_clausthal.in.mec.common.CPath.startsWith().
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.stop ()
Definition at line 220 of file CTreeBeliefBase.java.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.unbind (final String p_bindname)
Parameters
p_bindname bind name
Definition at line 131 of file CTreeBeliefBase.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasebind.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.update ()
Definition at line 184 of file CTreeBeliefBase.java.
Member Data Documentation
final String de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_agentbeliefseparator = "_" static private
Definition at line 57 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.createBeliefbase(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.CTreeBeliefBase(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessageBeliefbase(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.splitLiteralPath().
final CPath de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasebind = new CPath("bind") static private
Definition at line 69 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.bind(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.CTreeBeliefBase(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.unbind().
final CPath de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbasemessage = new CPath("message") static private
Definition at line 73 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessageBeliefbase(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessages().
final CPath de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbaseroot = new CPath("root") static private
Definition at line 65 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.splitLiteralPath().
final String de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.c_beliefbindprefixreplace = "m_" static private
Definition at line 61 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.CTreeBeliefBase().
final CMask de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.m_mask = new CBeliefBase(new CBeliefStorage<>(), c_agentbeliefseparator).createMask(c_beliefbaseroot.getSuffix()) private
Definition at line 77 of file CTreeBeliefBase.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.contains(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.getRootMask(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessageBeliefbase(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessages().