MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral Class Reference
de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral Class Reference
class for literals
Inherits CLiteral< Literal >.
Public Member Functions
CLiteral (final Literal p_literal)
ctor for Jason literals
CLiteral (final String p_functor, final Literal p_literal)
ctor to create a literal with a new functor
ILiteral< Literal > clone (final CPath p_prefix)
Private Member Functions
void addAdditionals (final Literal p_literal)
modifies the interal literal representations
Detailed Description
Definition at line 38 of file jason/belief/CLiteral.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.CLiteral (final Literal p_literal)
Parameters
p_literal Jason literal
Definition at line 46 of file jason/belief/CLiteral.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.clone().
de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.CLiteral (final String p_functor, final Literal p_literal)
Parameters
p_functor functor name
p_literal input literal
Definition at line 58 of file jason/belief/CLiteral.java.
Member Function Documentation
void de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.addAdditionals (final Literal p_literal) private
Parameters
p_literal literal
Definition at line 84 of file jason/belief/CLiteral.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric().
ILiteral<Literal> de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.clone (final CPath p_prefix)
Definition at line 66 of file jason/belief/CLiteral.java.
References de.tu_clausthal.in.mec.common.CPath.append(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.CLiteral().