MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CConsole Class Reference
de.tu_clausthal.in.mec.ui.CConsole Class Reference
stream to create stream access
Inherits ByteArrayOutputStream.
Public Member Functions
void flush () throws IOException
Static Public Member Functions
static CConsole getError (final String p_baseuri)
factor method to set error stream
static CConsole getOutput (final String p_baseuri)
factor method to set output stream
Private Member Functions
CConsole (final String p_baseuri)
ctor
void web_dynamic_log (final CWebSocket.EAction p_action, final CWebSocket.CCommunicator p_communicator, final CWebSocket.CFrame p_frame)
UI method - show log.
String web_uribase ()
UI method - register sockets.
Private Attributes
final String m_baseuri
base URI *
final CSocketStorage m_communicator = new CSocketStorage()
set with all communicators
Detailed Description
Note
log messages can be written with System.out or System.err
Definition at line 40 of file CConsole.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.CConsole.CConsole (final String p_baseuri) private
Definition at line 54 of file CConsole.java.
References de.tu_clausthal.in.mec.ui.CConsole.m_baseuri.
Referenced by de.tu_clausthal.in.mec.ui.CConsole.getError(), and de.tu_clausthal.in.mec.ui.CConsole.getOutput().
Member Function Documentation
void de.tu_clausthal.in.mec.ui.CConsole.flush () throws IOException
Definition at line 86 of file CConsole.java.
static CConsole de.tu_clausthal.in.mec.ui.CConsole.getError (final String p_baseuri) static
Parameters
p_baseuri base uri
Returns
console stream
Definition at line 65 of file CConsole.java.
References de.tu_clausthal.in.mec.ui.CConsole.CConsole().
static CConsole de.tu_clausthal.in.mec.ui.CConsole.getOutput (final String p_baseuri) static
Parameters
p_baseuri base uri
Returns
console stream
Definition at line 78 of file CConsole.java.
References de.tu_clausthal.in.mec.ui.CConsole.CConsole().
void de.tu_clausthal.in.mec.ui.CConsole.web_dynamic_log (final CWebSocket.EAction p_action, final CWebSocket.CCommunicator p_communicator, final CWebSocket.CFrame p_frame) private
Definition at line 99 of file CConsole.java.
String de.tu_clausthal.in.mec.ui.CConsole.web_uribase () private
Returns
base URI
Definition at line 109 of file CConsole.java.
References de.tu_clausthal.in.mec.ui.CConsole.m_baseuri.
Member Data Documentation
final String de.tu_clausthal.in.mec.ui.CConsole.m_baseuri private
Definition at line 45 of file CConsole.java.
Referenced by de.tu_clausthal.in.mec.ui.CConsole.CConsole(), and de.tu_clausthal.in.mec.ui.CConsole.web_uribase().
final CSocketStorage de.tu_clausthal.in.mec.ui.CConsole.m_communicator = new CSocketStorage() private
Definition at line 49 of file CConsole.java.