MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T > Class Reference
de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T > Class Reference
mask of a beliefbase
Inherits IBeliefBaseMask< T >.
Public Member Functions
CMask (final String p_name, final IBeliefBase< T > p_beliefbase)
ctor
CMask (final String p_name, final IBeliefBase< T > p_beliefbase, final IBeliefBaseMask< T > p_parent)
private ctor
void add (final CPath p_path, final ILiteral< T > p_literal)
IBeliefBaseMask< T > add (final CPath p_path, final IBeliefBaseMask< T > p_mask)
IBeliefBaseMask< T > add (final CPath p_path, final IGenerator< T > p_generator)
IBeliefBaseMask< T > add (final CPath p_path, final IBeliefBaseMask< T > p_mask, final IGenerator< T > p_generator)
void add (final CPath p_path, final ILiteral< T > p_literal, final IGenerator< T > p_generator)
void add (final ILiteral< T > p_literal)
IBeliefBaseMask< T > add (final IBeliefBaseMask< T > p_mask)
void clear ()
IBeliefBaseMask< T > clone (final IBeliefBaseMask< T > p_parent)
boolean containsLiteral (final CPath p_path)
boolean containsMask (final CPath p_path)
CPath getFQNPath ()
Set< ILiteral< T > > getLiteral (final CPath p_path)
Map< CPath, Set< ILiteral< T > > > getLiterals (final CPath p_path)
Map< CPath, Set< ILiteral< T > > > getLiterals ()
IBeliefBaseMask< T > getMask (final CPath p_path)
Map< CPath, IBeliefBaseMask< T > > getMasks (final CPath p_path)
Map< CPath, IBeliefBaseMask< T > > getMasks ()
String getName ()
IBeliefBaseMask< T > getParent ()
int hashCode ()
boolean hasParent ()
boolean isEmpty ()
Iterator< IBeliefBaseMask< T > > iteratorBeliefBaseMask ()
Iterator< ILiteral< T > > iteratorLiteral ()
boolean remove (final CPath p_path, final ILiteral< T > p_literal)
boolean remove (final CPath p_path, final IBeliefBaseMask< T > p_mask)
boolean remove (final CPath p_path)
boolean remove (final IBeliefBaseMask< T > p_mask)
boolean remove (final ILiteral< T > p_literal)
boolean remove (final String p_name)
IBeliefBaseMask< T > setPathSeparator (final String p_separator)
int size ()
int sizeLiteral ()
int sizeMask ()
String toString ()
void update ()
Protected Attributes
final IBeliefBase< T > m_beliefbase
reference to the beliefbase context
final String m_name
mask name
String m_pathseparator = CPath.DEFAULTSEPERATOR
path separator
Package Functions
public< E extends
IBeliefBaseMask< T > > E createMask (final String p_name)
public< L extends IStorage
< ILiteral< T >
, IBeliefBaseMask< T > > > L getStorage ()
Static Private Member Functions
static< Q > CPath getFQNPath (final IBeliefBaseMask< Q > p_mask, final CPath p_path)
static method to generate FQN path
static< Q > IBeliefBaseMask< Q > walk (final CPath p_path, final IBeliefBaseMask< Q > p_root, final IGenerator< Q > p_generator)
returns a mask on the recursive descend
Private Attributes
final IBeliefBaseMask< T > m_parent
parent name
Detailed Description
Template Parameters
P type of the beliefbase element
Definition at line 48 of file generic/implementation/CMask.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.CMask (final String p_name, final IBeliefBase< T > p_beliefbase)
Parameters
p_name name of the mask
p_beliefbase reference to the beliefbase context
Definition at line 73 of file generic/implementation/CMask.java.
de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.CMask (final String p_name, final IBeliefBase< T > p_beliefbase, final IBeliefBaseMask< T > p_parent)
Parameters
p_name name of the mask
p_beliefbase reference to the beliefbase context
p_parent reference to the parent mask
Definition at line 85 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Member Function Documentation
void de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final CPath p_path, final ILiteral< T > p_literal)
Definition at line 98 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final CPath p_path, final IBeliefBaseMask< T > p_mask)
Definition at line 104 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final CPath p_path, final IGenerator< T > p_generator)
Definition at line 110 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final CPath p_path, final IBeliefBaseMask< T > p_mask, final IGenerator< T > p_generator)
Definition at line 116 of file generic/implementation/CMask.java.
void de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final CPath p_path, final ILiteral< T > p_literal, final IGenerator< T > p_generator)
Definition at line 123 of file generic/implementation/CMask.java.
void de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final ILiteral< T > p_literal)
Definition at line 286 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add (final IBeliefBaseMask< T > p_mask)
Definition at line 292 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseMask< T >.getName(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage().
void de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.clear ()
Definition at line 307 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.clone (final IBeliefBaseMask< T > p_parent)
Definition at line 172 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsLiteral (final CPath p_path)
Definition at line 142 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage(), de.tu_clausthal.in.mec.common.CPath.getSubPath(), de.tu_clausthal.in.mec.common.CPath.isEmpty(), and de.tu_clausthal.in.mec.common.CPath.size().
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsMask (final CPath p_path)
Definition at line 130 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage(), de.tu_clausthal.in.mec.common.CPath.getSubPath(), de.tu_clausthal.in.mec.common.CPath.isEmpty(), and de.tu_clausthal.in.mec.common.CPath.size().
public<E extends IBeliefBaseMask<T> > E de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.createMask (final String p_name) package
Definition at line 313 of file generic/implementation/CMask.java.
CPath de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getFQNPath ()
Definition at line 241 of file generic/implementation/CMask.java.
static <Q> CPath de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getFQNPath (final IBeliefBaseMask< Q > p_mask, final CPath p_path) static private
Parameters
p_mask curretn path
p_path current path
Returns
path
Template Parameters
Q type of the beliefbase elements
Definition at line 452 of file generic/implementation/CMask.java.
Set<ILiteral<T> > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getLiteral (final CPath p_path)
Definition at line 210 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.common.CPath.getSubPath().
Map<CPath, Set<ILiteral<T> > > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getLiterals (final CPath p_path)
Definition at line 178 of file generic/implementation/CMask.java.
Map<CPath, Set<ILiteral<T> > > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getLiterals ()
Definition at line 184 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage().
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getMask (final CPath p_path)
Definition at line 216 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.common.CPath.getSubPath().
Map<CPath, IBeliefBaseMask<T> > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getMasks (final CPath p_path)
Definition at line 222 of file generic/implementation/CMask.java.
Map<CPath, IBeliefBaseMask<T> > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getMasks ()
Definition at line 228 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseMask< T >.getFQNPath(), and de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage().
String de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getName ()
Definition at line 256 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getParent ()
Definition at line 262 of file generic/implementation/CMask.java.
public<L extends IStorage<ILiteral<T>, IBeliefBaseMask<T> > > L de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getStorage () package
Definition at line 319 of file generic/implementation/CMask.java.
int de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.hashCode ()
Definition at line 274 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.hasParent ()
Definition at line 268 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.isEmpty ()
Definition at line 325 of file generic/implementation/CMask.java.
Iterator<IBeliefBaseMask<T> > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.iteratorBeliefBaseMask ()
stack with iterator
Definition at line 411 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage().
Iterator<ILiteral<T> > de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.iteratorLiteral ()
stack with iterators
Definition at line 373 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage().
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.remove (final CPath p_path, final ILiteral< T > p_literal)
Definition at line 154 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.remove (final CPath p_path, final IBeliefBaseMask< T > p_mask)
Definition at line 160 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.remove (final CPath p_path)
Definition at line 166 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.remove (final IBeliefBaseMask< T > p_mask)
Definition at line 331 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.remove (final ILiteral< T > p_literal)
Definition at line 337 of file generic/implementation/CMask.java.
boolean de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.remove (final String p_name)
Definition at line 343 of file generic/implementation/CMask.java.
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.setPathSeparator (final String p_separator)
Definition at line 249 of file generic/implementation/CMask.java.
int de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.size ()
Definition at line 367 of file generic/implementation/CMask.java.
int de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.sizeLiteral ()
Definition at line 361 of file generic/implementation/CMask.java.
int de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.sizeMask ()
Definition at line 355 of file generic/implementation/CMask.java.
String de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.toString ()
Definition at line 280 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage().
void de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.update ()
Definition at line 349 of file generic/implementation/CMask.java.
static <Q> IBeliefBaseMask<Q> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.walk (final CPath p_path, final IBeliefBaseMask< Q > p_root, final IGenerator< Q > p_generator) static private
Parameters
p_path path
p_root start / root node
p_generator generator object for new masks
Returns
mask
Note
a path can contains ".." to use the parent object
Template Parameters
Q literal type
Definition at line 469 of file generic/implementation/CMask.java.
References de.tu_clausthal.in.mec.common.CPath.get(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.common.CPath.getSubPath(), and de.tu_clausthal.in.mec.common.CPath.isEmpty().
Member Data Documentation
final IBeliefBase<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.m_beliefbase protected
Definition at line 61 of file generic/implementation/CMask.java.
final String de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.m_name protected
Definition at line 57 of file generic/implementation/CMask.java.
final IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.m_parent private
Definition at line 65 of file generic/implementation/CMask.java.
String de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.m_pathseparator = CPath.DEFAULTSEPERATOR protected
Definition at line 53 of file generic/implementation/CMask.java.