MecSim - Traffic Simulation: de.tu_clausthal.in.mec.runtime.core.CMainLoop Class Reference
de.tu_clausthal.in.mec.runtime.core.CMainLoop Class Reference
main simulation thread
Inherits Runnable.
Public Member Functions
CMainLoop (final int p_sleeptime)
ctor
final int getSimulationstep ()
returns the simulation step
int getSleepTime ()
returns the thread-sleep time
final boolean isPaused ()
checks if the thread is paused
final void pause ()
sets pause state
final void reset ()
resets the thread
final void resume ()
resume state
final void resume (final int p_steps)
resumes thread and shut down thread after
final void run ()
void setSleepTime (final int p_sleeptime)
changes the thread-sleep time
final void stop ()
thread is shut down
Protected Member Functions
final void invokeTasks (final ILayer p_layer, final Collection< ISteppable > p_tasksource) throws InterruptedException
invokes all defined data
Private Member Functions
void processLayer (final List< ILayer > p_layer) throws InterruptedException
process layer
void processObjects (final List< ILayer > p_layer)
process layer object
Static Private Member Functions
static Callable< Object > createTask (final int p_iteration, final ISteppable p_object, final ILayer p_layer)
returns a runnable object of the steppable input
Private Attributes
boolean m_pause = true
boolean to pause/resume the thread
final ExecutorService m_pool = Executors.newWorkStealingPool()
thread-pool for handling all objects
int m_shutdownstep = Integer.MAX_VALUE
number of threads for running *
int m_simulationcount
simulation counter
volatile int m_sleeptime
thread sleep time
Detailed Description
Definition at line 52 of file CMainLoop.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.runtime.core.CMainLoop.CMainLoop (final int p_sleeptime)
Parameters
p_sleeptime thread-sleep time
Definition at line 80 of file CMainLoop.java.
Member Function Documentation
static Callable<Object> de.tu_clausthal.in.mec.runtime.core.CMainLoop.createTask (final int p_iteration, final ISteppable p_object, final ILayer p_layer) static private
Parameters
p_iteration iteration
p_object steppable object
p_layer layer
Returns
runnable object
Definition at line 244 of file CMainLoop.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Referenced by de.tu_clausthal.in.mec.runtime.core.CMainLoop.invokeTasks(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.processLayer().
final int de.tu_clausthal.in.mec.runtime.core.CMainLoop.getSimulationstep ()
Returns
step number
Definition at line 110 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.generateObjectName().
int de.tu_clausthal.in.mec.runtime.core.CMainLoop.getSleepTime ()
Returns
thread-sleep time
Definition at line 90 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_sleeptime.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.web_static_setthreadsleep().
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.invokeTasks (final ILayer p_layer, final Collection< ISteppable > p_tasksource) throws InterruptedException protected
Parameters
p_layer layer
p_tasksource invoking tasks
Exceptions
InterruptedException is throws on task error
Definition at line 226 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.createTask(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount.
final boolean de.tu_clausthal.in.mec.runtime.core.CMainLoop.isPaused ()
Returns
boolean for pause
Definition at line 120 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause.
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.pause ()
Definition at line 128 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause.
void de.tu_clausthal.in.mec.runtime.core.CMainLoop.processLayer (final List< ILayer > p_layer) throws InterruptedException private
Parameters
p_layer ordered layer list
Exceptions
InterruptedException thrown on thread error
Definition at line 263 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.createTask(), de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount.
void de.tu_clausthal.in.mec.runtime.core.CMainLoop.processObjects (final List< ILayer > p_layer) private
Parameters
p_layer ordered layer list
Note
only multi-, evaluate- & network layer can store other objects
Definition at line 281 of file CMainLoop.java.
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.reset ()
Definition at line 136 of file CMainLoop.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause, and de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount.
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.resume ()
Definition at line 148 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause.
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.resume (final int p_steps)
Parameters
p_steps number of steps which are performtemplate
Definition at line 158 of file CMainLoop.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause, de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_shutdownstep, and de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount.
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.run ()
Definition at line 168 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause, de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_shutdownstep, de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount, and de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_sleeptime.
void de.tu_clausthal.in.mec.runtime.core.CMainLoop.setSleepTime (final int p_sleeptime)
Parameters
p_sleeptime thread-sleep time
Definition at line 100 of file CMainLoop.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_sleeptime.
final void de.tu_clausthal.in.mec.runtime.core.CMainLoop.stop ()
Definition at line 214 of file CMainLoop.java.
Member Data Documentation
boolean de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pause = true private
Definition at line 57 of file CMainLoop.java.
Referenced by de.tu_clausthal.in.mec.runtime.core.CMainLoop.isPaused(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.pause(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.reset(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.resume(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.run().
final ExecutorService de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_pool = Executors.newWorkStealingPool() private
Definition at line 61 of file CMainLoop.java.
int de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_shutdownstep = Integer.MAX_VALUE private
Definition at line 65 of file CMainLoop.java.
Referenced by de.tu_clausthal.in.mec.runtime.core.CMainLoop.resume(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.run().
int de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_simulationcount private
Definition at line 69 of file CMainLoop.java.
Referenced by de.tu_clausthal.in.mec.runtime.core.CMainLoop.getSimulationstep(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.invokeTasks(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.processLayer(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.reset(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.resume(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.run().
volatile int de.tu_clausthal.in.mec.runtime.core.CMainLoop.m_sleeptime private
Definition at line 73 of file CMainLoop.java.
Referenced by de.tu_clausthal.in.mec.runtime.core.CMainLoop.getSleepTime(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.run(), and de.tu_clausthal.in.mec.runtime.core.CMainLoop.setSleepTime().