MecSim - Traffic Simulation: de.tu_clausthal.in.mec.CBootstrap Class Reference
de.tu_clausthal.in.mec.CBootstrap Class Reference
class to create the bootstrap of the program
Static Public Member Functions
static void afterOSMViewerInit (final COSMViewer p_viewer)
is called after the OSM viewer is initialize
static void afterServerInit (final CServer p_server)
is called after the webserver is started
static void afterSimulationInit (final CSimulation p_simulation)
is called after the simulation is initialize
static void afterStageInit (final CUI p_ui)
is called after the frame is initialize and before the UI configuration is load
static void beforeStageShutdown (final CUI p_ui)
is called at UI shutdown
static void configurationIsLoaded (final CConfiguration p_configuration)
is called after configuration is loaded
static void onApplicationClose ()
is called on application closed
static void onSimulationReset (final CSimulation p_simulation)
is called on simulation reset
Private Member Functions
CBootstrap ()
private ctor - avoid instantiation
Detailed Description
Definition at line 59 of file CBootstrap.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.CBootstrap.CBootstrap () private
Definition at line 65 of file CBootstrap.java.
Member Function Documentation
static void de.tu_clausthal.in.mec.CBootstrap.afterOSMViewerInit (final COSMViewer p_viewer) static
Parameters
p_viewer viewer object
Definition at line 74 of file CBootstrap.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance().
static void de.tu_clausthal.in.mec.CBootstrap.afterServerInit (final CServer p_server) static
Parameters
p_server webserver
Definition at line 88 of file CBootstrap.java.
References de.tu_clausthal.in.mec.object.mas.EAgentLanguages.Jason.
static void de.tu_clausthal.in.mec.CBootstrap.afterSimulationInit (final CSimulation p_simulation) static
Parameters
p_simulation simulation
Definition at line 124 of file CBootstrap.java.
static void de.tu_clausthal.in.mec.CBootstrap.afterStageInit (final CUI p_ui) static
Parameters
p_ui UI Object
Definition at line 143 of file CBootstrap.java.
static void de.tu_clausthal.in.mec.CBootstrap.beforeStageShutdown (final CUI p_ui) static
Parameters
p_ui UI object
Definition at line 154 of file CBootstrap.java.
static void de.tu_clausthal.in.mec.CBootstrap.configurationIsLoaded (final CConfiguration p_configuration) static
Parameters
p_configuration configuration
Definition at line 165 of file CBootstrap.java.
static void de.tu_clausthal.in.mec.CBootstrap.onApplicationClose () static
Definition at line 187 of file CBootstrap.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), and de.tu_clausthal.in.mec.CConfiguration.getInstance().
static void de.tu_clausthal.in.mec.CBootstrap.onSimulationReset (final CSimulation p_simulation) static
Parameters
p_simulation simulation object
Definition at line 177 of file CBootstrap.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getStorage().