MecSim - Traffic Simulation: de.tu_clausthal.in.mec.runtime.message.CMessage< T > Class Reference
de.tu_clausthal.in.mec.runtime.message.CMessage< T > Class Reference
default event message
Public Member Functions
CMessage (final CPath p_source, final String p_title)
ctor - creates a message with data and name
CMessage (final CPath p_source, final String p_title, final T p_data)
ctor - creates a message with data and name
final T getData ()
the data of the message
final CPath getSource ()
returns the source of the message
final String getTitle ()
a name if the message
final int ttl ()
decrements the time-to-live value and returns the decrement value and on zero the message is discarded
Private Attributes
final T m_data
data of the message
final CPath m_source
source of the message
final String m_title
title of the message
int m_ttl = 10
time-to-live value *
Detailed Description
Template Parameters
T type of the message data
Definition at line 37 of file runtime/message/CMessage.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.runtime.message.CMessage< T >.CMessage (final CPath p_source, final String p_title)
Parameters
p_source path of the source
p_title title of the message
Definition at line 62 of file runtime/message/CMessage.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.common.CPath.isEmpty().
de.tu_clausthal.in.mec.runtime.message.CMessage< T >.CMessage (final CPath p_source, final String p_title, final T p_data)
Parameters
p_source path of the source
p_title title of the message
p_data data of the message
Definition at line 81 of file runtime/message/CMessage.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.common.CPath.isEmpty().
Member Function Documentation
final T de.tu_clausthal.in.mec.runtime.message.CMessage< T >.getData ()
Returns
data
Implements de.tu_clausthal.in.mec.runtime.message.IMessage< T >.
Definition at line 94 of file runtime/message/CMessage.java.
final CPath de.tu_clausthal.in.mec.runtime.message.CMessage< T >.getSource ()
Implements de.tu_clausthal.in.mec.runtime.message.IMessage< T >.
Definition at line 100 of file runtime/message/CMessage.java.
final String de.tu_clausthal.in.mec.runtime.message.CMessage< T >.getTitle ()
Returns
name
Implements de.tu_clausthal.in.mec.runtime.message.IMessage< T >.
Definition at line 106 of file runtime/message/CMessage.java.
final int de.tu_clausthal.in.mec.runtime.message.CMessage< T >.ttl ()
Returns
current value
Implements de.tu_clausthal.in.mec.runtime.message.IMessage< T >.
Definition at line 112 of file runtime/message/CMessage.java.
Member Data Documentation
final T de.tu_clausthal.in.mec.runtime.message.CMessage< T >.m_data private
Definition at line 42 of file runtime/message/CMessage.java.
final CPath de.tu_clausthal.in.mec.runtime.message.CMessage< T >.m_source private
Definition at line 46 of file runtime/message/CMessage.java.
final String de.tu_clausthal.in.mec.runtime.message.CMessage< T >.m_title private
Definition at line 50 of file runtime/message/CMessage.java.
int de.tu_clausthal.in.mec.runtime.message.CMessage< T >.m_ttl = 10 private
Definition at line 54 of file runtime/message/CMessage.java.