MecSim - Traffic Simulation: de.tu_clausthal.in.mec.CLogger Class Reference
de.tu_clausthal.in.mec.CLogger Class Reference
Logger class with additional Log4j support.
Static Public Member Functions
static void create (final Level p_level, final String p_filename)
creates the logger with properties
static void debug ()
adds a debug message
static< T > T debug (final T p_data, final boolean p_write)
adds a debug message
static void debug (final boolean p_write)
adds a debug message
static< T > T debug (final T p_data)
adds a debug message
static void error ()
adds a error message
static< T > T error (final T p_data, final boolean p_write)
adds a error message
static void error (final boolean p_write)
adds a error message
static< T > T error (final T p_data)
adds a error message
static CLogger getInstance ()
returns logger instance
static void info ()
adds an info message
static< T > T info (final T p_data, final boolean p_write)
adds an info message
static void info (final boolean p_write)
adds an info message
static< T > T info (final T p_data)
adds an info message
static void out ()
adds a output message
static< T > T out (final T p_data, final boolean p_write)
adds a output message
static void out (final boolean p_write)
adds a output message
static< T > T out (final T p_data)
adds a output message
static void warn ()
adds a warn message
static< T > T warn (final T p_data, final boolean p_write)
adds a warn message
static void warn (final boolean p_write)
adds a warn message *
static< T > T warn (final T p_data)
adds a warn message
Static Package Functions
[static initializer]
initialization
Private Member Functions
CLogger ()
private ctor - avoid instantiation
Map< String, Object > web_static_configuration ()
UI method - returns the loger definition.
void web_static_debug (final Map< String, Object > p_data)
UI method - log debug.
void web_static_error (final Map< String, Object > p_data)
UI method - log error.
void web_static_info (final Map< String, Object > p_data)
UI method - log info.
void web_static_out (final Map< String, Object > p_data)
UI method - log info.
void web_static_warn (final Map< String, Object > p_data)
UI method - log warn.
Static Private Member Functions
static String createLogData (final Level p_status, final Object p_add)
creates a full log item
static String getCurrentClassName (final int p_offset)
gets the current class name
static int getCurrentLineNumber (final int p_offset)
gets the current line number
static String getCurrentMethodName (final int p_offset)
gets the current method name
static String getCurrentMethodNameFqn (final int p_offset)
gets the current FQN method name
static String getInvokingClassName (final int p_offset)
gets the current invoker class name
static String getInvokingMethodName (final int p_offset)
gets the current invoker method name
static String getInvokingMethodNameFqn (final int p_offset)
gets the current invoker FQN method name
static String padCut (final String p_input, final char p_filler, final int p_length)
pad / cut string of a define length
Static Private Attributes
static final int c_stackindex
stack index of traces
static final CLogger s_instance = new CLogger()
object instance to bind web UI calls *
static Level s_level = Level.OFF
defines the global log level
static boolean s_logoutput = false
define ths flag, that the log is passend to the output
Detailed Description
Definition at line 42 of file CLogger.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.CLogger.CLogger () private
Definition at line 83 of file CLogger.java.
Member Function Documentation
de.tu_clausthal.in.mec.CLogger.[static initializer] () static package
static void de.tu_clausthal.in.mec.CLogger.create (final Level p_level, final String p_filename) static
Parameters
p_level log level
p_filename p_filename
Definition at line 93 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.s_level, and de.tu_clausthal.in.mec.CLogger.s_logoutput.
static String de.tu_clausthal.in.mec.CLogger.createLogData (final Level p_status, final Object p_add) static private
Parameters
p_status status name
p_add additional log data
Definition at line 368 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.getCurrentLineNumber(), de.tu_clausthal.in.mec.CLogger.getCurrentMethodNameFqn(), de.tu_clausthal.in.mec.CLogger.getInvokingMethodNameFqn(), and de.tu_clausthal.in.mec.CLogger.padCut().
Referenced by de.tu_clausthal.in.mec.CLogger.debug(), de.tu_clausthal.in.mec.CLogger.error(), de.tu_clausthal.in.mec.CLogger.info(), de.tu_clausthal.in.mec.CLogger.out(), and de.tu_clausthal.in.mec.CLogger.warn().
static void de.tu_clausthal.in.mec.CLogger.debug () static
Definition at line 110 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.debug().
static <T> T de.tu_clausthal.in.mec.CLogger.debug (final T p_data, final boolean p_write) static
Parameters
p_data log data
p_write boolean on true message is written
Returns
input data
Template Parameters
input data type
Definition at line 124 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.createLogData().
static void de.tu_clausthal.in.mec.CLogger.debug (final boolean p_write) static
Parameters
p_write boolean on true message is written
Definition at line 136 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.debug().
static <T> T de.tu_clausthal.in.mec.CLogger.debug (final T p_data) static
Parameters
p_data log data
Returns
input data
Template Parameters
input data type
Definition at line 149 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.debug().
static void de.tu_clausthal.in.mec.CLogger.error () static
Definition at line 158 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.error(), and de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRoutes().
static <T> T de.tu_clausthal.in.mec.CLogger.error (final T p_data, final boolean p_write) static
Parameters
p_data log data
p_write boolean on true message is written
Returns
input data
Template Parameters
input data type
Definition at line 172 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.createLogData().
static void de.tu_clausthal.in.mec.CLogger.error (final boolean p_write) static
Parameters
p_write boolean on true message is written
Definition at line 184 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.error().
static <T> T de.tu_clausthal.in.mec.CLogger.error (final T p_data) static
Parameters
p_data log data
Returns
input data
Template Parameters
input data type
Definition at line 197 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.error().
static String de.tu_clausthal.in.mec.CLogger.getCurrentClassName (final int p_offset) static private
Returns
class name
Definition at line 425 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.c_stackindex.
Referenced by de.tu_clausthal.in.mec.CLogger.getCurrentMethodNameFqn(), and de.tu_clausthal.in.mec.CLogger.getInvokingClassName().
static int de.tu_clausthal.in.mec.CLogger.getCurrentLineNumber (final int p_offset) static private
Returns
number
Definition at line 435 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.c_stackindex.
Referenced by de.tu_clausthal.in.mec.CLogger.createLogData().
static String de.tu_clausthal.in.mec.CLogger.getCurrentMethodName (final int p_offset) static private
Returns
method name
Definition at line 445 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.c_stackindex.
Referenced by de.tu_clausthal.in.mec.CLogger.getCurrentMethodNameFqn(), and de.tu_clausthal.in.mec.CLogger.getInvokingMethodName().
static String de.tu_clausthal.in.mec.CLogger.getCurrentMethodNameFqn (final int p_offset) static private
Returns
FQN method name
Definition at line 455 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.getCurrentClassName(), and de.tu_clausthal.in.mec.CLogger.getCurrentMethodName().
Referenced by de.tu_clausthal.in.mec.CLogger.createLogData().
static CLogger de.tu_clausthal.in.mec.CLogger.getInstance () static
Returns
logger instance
Definition at line 208 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.s_instance.
static String de.tu_clausthal.in.mec.CLogger.getInvokingClassName (final int p_offset) static private
Returns
class name
Definition at line 468 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.getCurrentClassName().
Referenced by de.tu_clausthal.in.mec.CLogger.getInvokingMethodNameFqn().
static String de.tu_clausthal.in.mec.CLogger.getInvokingMethodName (final int p_offset) static private
Returns
method name
Definition at line 478 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.getCurrentMethodName().
Referenced by de.tu_clausthal.in.mec.CLogger.getInvokingMethodNameFqn().
static String de.tu_clausthal.in.mec.CLogger.getInvokingMethodNameFqn (final int p_offset) static private
Returns
FQN method name
Definition at line 488 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.getInvokingClassName(), and de.tu_clausthal.in.mec.CLogger.getInvokingMethodName().
Referenced by de.tu_clausthal.in.mec.CLogger.createLogData().
static void de.tu_clausthal.in.mec.CLogger.info () static
Definition at line 216 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.IDatabase.createTable(), and de.tu_clausthal.in.mec.CLogger.info().
static <T> T de.tu_clausthal.in.mec.CLogger.info (final T p_data, final boolean p_write) static
Parameters
p_data log data
p_write boolean on true message is written
Returns
input data
Template Parameters
input data type
Definition at line 230 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.createLogData().
static void de.tu_clausthal.in.mec.CLogger.info (final boolean p_write) static
Parameters
p_write boolean on true message is written
Definition at line 242 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.info().
static <T> T de.tu_clausthal.in.mec.CLogger.info (final T p_data) static
Parameters
p_data log data
Returns
input data
Template Parameters
input data type
Definition at line 255 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.info().
static void de.tu_clausthal.in.mec.CLogger.out () static
Definition at line 264 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CMain.main(), and de.tu_clausthal.in.mec.CLogger.out().
static <T> T de.tu_clausthal.in.mec.CLogger.out (final T p_data, final boolean p_write) static
Parameters
p_data log data
p_write boolean on true message is written
Returns
input data
Template Parameters
input data type
Definition at line 278 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.createLogData(), and de.tu_clausthal.in.mec.CLogger.s_level.
static void de.tu_clausthal.in.mec.CLogger.out (final boolean p_write) static
Parameters
p_write boolean on true message is written
Definition at line 295 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.out().
static <T> T de.tu_clausthal.in.mec.CLogger.out (final T p_data) static
Parameters
p_data log data
Returns
input data
Template Parameters
input data type
Definition at line 308 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.out().
static String de.tu_clausthal.in.mec.CLogger.padCut (final String p_input, final char p_filler, final int p_length) static private
Parameters
p_input input string
p_filler fill character
p_length max string length
Returns
modified string
Definition at line 504 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.createLogData().
static void de.tu_clausthal.in.mec.CLogger.warn () static
Definition at line 317 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.warn().
static <T> T de.tu_clausthal.in.mec.CLogger.warn (final T p_data, final boolean p_write) static
Parameters
p_data log data
p_write boolean on true message is written
Returns
input data
Template Parameters
input data type
Definition at line 331 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.createLogData().
static void de.tu_clausthal.in.mec.CLogger.warn (final boolean p_write) static
Parameters
p_write boolean on true message is written
Definition at line 343 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.warn().
static <T> T de.tu_clausthal.in.mec.CLogger.warn (final T p_data) static
Parameters
p_data log data
Returns
input data
Template Parameters
input data type
Definition at line 356 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.warn().
Map<String, Object> de.tu_clausthal.in.mec.CLogger.web_static_configuration () private
Returns
map with definition
Definition at line 519 of file CLogger.java.
References de.tu_clausthal.in.mec.CLogger.s_level, and de.tu_clausthal.in.mec.CLogger.s_logoutput.
void de.tu_clausthal.in.mec.CLogger.web_static_debug (final Map< String, Object > p_data) private
Parameters
p_data UI input data
Definition at line 529 of file CLogger.java.
void de.tu_clausthal.in.mec.CLogger.web_static_error (final Map< String, Object > p_data) private
Parameters
p_data UI input data
Definition at line 539 of file CLogger.java.
void de.tu_clausthal.in.mec.CLogger.web_static_info (final Map< String, Object > p_data) private
Parameters
p_data UI input data
Definition at line 549 of file CLogger.java.
void de.tu_clausthal.in.mec.CLogger.web_static_out (final Map< String, Object > p_data) private
Parameters
p_data UI input data
Definition at line 559 of file CLogger.java.
void de.tu_clausthal.in.mec.CLogger.web_static_warn (final Map< String, Object > p_data) private
Parameters
p_data UI input data
Definition at line 569 of file CLogger.java.
Member Data Documentation
final int de.tu_clausthal.in.mec.CLogger.c_stackindex static private
Definition at line 47 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.getCurrentClassName(), de.tu_clausthal.in.mec.CLogger.getCurrentLineNumber(), and de.tu_clausthal.in.mec.CLogger.getCurrentMethodName().
final CLogger de.tu_clausthal.in.mec.CLogger.s_instance = new CLogger() static private
Definition at line 51 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.getInstance().
Level de.tu_clausthal.in.mec.CLogger.s_level = Level.OFF static private
Definition at line 55 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.create(), de.tu_clausthal.in.mec.CLogger.out(), and de.tu_clausthal.in.mec.CLogger.web_static_configuration().
boolean de.tu_clausthal.in.mec.CLogger.s_logoutput = false static private
Definition at line 59 of file CLogger.java.
Referenced by de.tu_clausthal.in.mec.CLogger.create(), and de.tu_clausthal.in.mec.CLogger.web_static_configuration().