MecSim - Traffic Simulation: de.tu_clausthal.in.mec.CConfiguration Class Reference
de.tu_clausthal.in.mec.CConfiguration Class Reference
singleton class for configuration with a Json file
Classes
class CClassType
class type check
class CCollectionNotEmpty
collection empty check
class CContains< T >
collection contains check
class CGreater
numeric greater check
class CInRange
numeric in range check
class CStringNotContains
string not-allowed char check
class CStringNotEmpty
string empty check
class ICheck< T >
check class
class UTF8Control
class to read UTF-8 encoded property file
Public Member Functions
void delete ()
deletes the configuration filename
CNameHashMap.CImmutable get ()
returns the data items of the configuration
File getLocation (final String p_name, final String...p_varargs)
returns the location of a directory
BigInteger getProcessID ()
returns the current process id (a signed big integer value)
ResourceBundle getResourceBundle ()
returns the property bundle
ResourceBundle getResourceBundle (final String p_language)
returns the property bundle
boolean read ()
reads the configuration within the directory
void setConfigDir (final File p_dir)
sets the config dir
void write ()
write method of the configuration
Static Public Member Functions
static CConfiguration getInstance ()
singleton get instance method
static String getPackage ()
returns the main package name
Private Member Functions
CConfiguration ()
private Ctor to avoid manual instantiation with manifest reading
void createDirectories () throws IOException
creates the configuration directories
File getBasePath (final String...p_dir)
returns a path relative to the root directory
void setConfiguration (final CNameHashMap p_input) throws IOException, ClassNotFoundException, IllegalArgumentException
sets the configuration values with semantic check
void setDefaultDirectories ()
creates the default directories relative to the root dir
void web_static_deletegraph (final Map< String, Object > p_data)
UI method - set data.
CNameHashMap.CImmutable web_static_get ()
UI method - read configuration.
void web_static_set (final Map< String, Object > p_data, final Map< String, String > p_header) throws IOException, ClassNotFoundException
UI method - set data.
Map< String, Object > web_static_startupchecks ()
UI method - performtemplate startup checks.
Private Attributes
final CNameHashMap.CImmutable m_configuration
configuration map
Map< String, List< ICheck > > m_configurationchecks
map with path and check-item for the value
final Map< String, File > m_location
location map
final BigInteger m_processid = new BigInteger(UUID.randomUUID().toString().replace("-", ""), 16)
UUID of the current process.
ResourceBundle.Control m_reader = new UTF8Control()
UTF-8 property reader.
Static Private Attributes
static final String[] c_externalfiles = new String[]{"benchmark.r", "inconsistency.r"}
list if external files for extracting
static final String c_filename = "config.json"
name of the configuration file
static final CConfiguration c_instance = new CConfiguration()
singleton instance variable
static final String c_mainpackage = "de.tu_clausthal.in.mec"
name of the main package
static final String[] c_masfiles = new String[]{"carDefault.asl", "carEmergency.asl", "carScramble.asl"}
list of MAS files for extracting
Detailed Description
Definition at line 65 of file CConfiguration.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.CConfiguration.CConfiguration () private
Note
IO-Exception is thrown on non-existing jar / NPE is thrown on Benchmarking
Definition at line 407 of file CConfiguration.java.
Member Function Documentation
void de.tu_clausthal.in.mec.CConfiguration.createDirectories () throws IOException private
Definition at line 632 of file CConfiguration.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
void de.tu_clausthal.in.mec.CConfiguration.delete ()
Definition at line 624 of file CConfiguration.java.
CNameHashMap.CImmutable de.tu_clausthal.in.mec.CConfiguration.get ()
Returns
configuration map
Definition at line 453 of file CConfiguration.java.
File de.tu_clausthal.in.mec.CConfiguration.getBasePath (final String... p_dir) private
Parameters
p_dir directories
Returns
full file
Definition at line 645 of file CConfiguration.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static CConfiguration de.tu_clausthal.in.mec.CConfiguration.getInstance () static
Returns
configuration instance
Definition at line 427 of file CConfiguration.java.
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.CGraphHopper(), de.tu_clausthal.in.mec.Test_CLanguageLabels.MyMethodVisitor.checkLabel(), de.tu_clausthal.in.mec.ui.COSMViewer.COSMViewer(), de.tu_clausthal.in.mec.ui.web.CWorkspace.CWorkspace(), de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.getAgentFiles(), de.tu_clausthal.in.mec.CMain.main(), de.tu_clausthal.in.mec.CBootstrap.onApplicationClose(), de.tu_clausthal.in.mec.ui.web.CMarkdownRenderer.render(), and de.tu_clausthal.in.mec.Test_CLanguageLabels.testResourceString().
File de.tu_clausthal.in.mec.CConfiguration.getLocation (final String p_name, final String... p_varargs)
Parameters
p_name name of the location
p_varargs path components after the directory
Returns
full directory
Definition at line 465 of file CConfiguration.java.
static String de.tu_clausthal.in.mec.CConfiguration.getPackage () static
Definition at line 435 of file CConfiguration.java.
Referenced by de.tu_clausthal.in.mec.runtime.benchmark.CInjection.inject().
BigInteger de.tu_clausthal.in.mec.CConfiguration.getProcessID ()
Definition at line 443 of file CConfiguration.java.
ResourceBundle de.tu_clausthal.in.mec.CConfiguration.getResourceBundle ()
Returns
resource bundle
Definition at line 478 of file CConfiguration.java.
ResourceBundle de.tu_clausthal.in.mec.CConfiguration.getResourceBundle (final String p_language)
Parameters
p_language language code
Returns
resource bundle
Definition at line 489 of file CConfiguration.java.
boolean de.tu_clausthal.in.mec.CConfiguration.read ()
Returns
boolean on correct read
Definition at line 510 of file CConfiguration.java.
References de.tu_clausthal.in.mec.common.CCommon.fromJson().
void de.tu_clausthal.in.mec.CConfiguration.setConfigDir (final File p_dir)
Parameters
p_dir directory
Definition at line 586 of file CConfiguration.java.
void de.tu_clausthal.in.mec.CConfiguration.setConfiguration (final CNameHashMap p_input) throws IOException, ClassNotFoundException, IllegalArgumentException private
Parameters
p_input input map
Definition at line 658 of file CConfiguration.java.
void de.tu_clausthal.in.mec.CConfiguration.setDefaultDirectories () private
Definition at line 705 of file CConfiguration.java.
void de.tu_clausthal.in.mec.CConfiguration.web_static_deletegraph (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 740 of file CConfiguration.java.
References de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.deleteGraph().
CNameHashMap.CImmutable de.tu_clausthal.in.mec.CConfiguration.web_static_get () private
Returns
data
Definition at line 716 of file CConfiguration.java.
void de.tu_clausthal.in.mec.CConfiguration.web_static_set (final Map< String, Object > p_data, final Map< String, String > p_header) throws IOException, ClassNotFoundException private
Parameters
p_data input data
p_header header data - configuration changeable only from localhost
Definition at line 727 of file CConfiguration.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Map<String, Object> de.tu_clausthal.in.mec.CConfiguration.web_static_startupchecks () private
Returns
error / warning messages
Definition at line 751 of file CConfiguration.java.
void de.tu_clausthal.in.mec.CConfiguration.write ()
Definition at line 603 of file CConfiguration.java.
References de.tu_clausthal.in.mec.common.CCommon.toJson().
Member Data Documentation
final String [] de.tu_clausthal.in.mec.CConfiguration.c_externalfiles = new String[]{"benchmark.r", "inconsistency.r"} static private
Definition at line 87 of file CConfiguration.java.
final String de.tu_clausthal.in.mec.CConfiguration.c_filename = "config.json" static private
Definition at line 70 of file CConfiguration.java.
final CConfiguration de.tu_clausthal.in.mec.CConfiguration.c_instance = new CConfiguration() static private
Definition at line 74 of file CConfiguration.java.
final String de.tu_clausthal.in.mec.CConfiguration.c_mainpackage = "de.tu_clausthal.in.mec" static private
Warning
package name is also used within the injection benchmark class
Definition at line 79 of file CConfiguration.java.
final String [] de.tu_clausthal.in.mec.CConfiguration.c_masfiles = new String[]{"carDefault.asl", "carEmergency.asl", "carScramble.asl"} static private
Definition at line 83 of file CConfiguration.java.
final CNameHashMap.CImmutable de.tu_clausthal.in.mec.CConfiguration.m_configuration private
Definition at line 91 of file CConfiguration.java.
Map<String, List<ICheck> > de.tu_clausthal.in.mec.CConfiguration.m_configurationchecks private
Definition at line 239 of file CConfiguration.java.
final Map<String, File> de.tu_clausthal.in.mec.CConfiguration.m_location private
Initial value:
= new HashMap<String, File>()
    {{
        put( "root", new File( System.getProperty( "user.home" ) + File.separator + ".mecsim" ) );
    }}
Definition at line 389 of file CConfiguration.java.
final BigInteger de.tu_clausthal.in.mec.CConfiguration.m_processid = new BigInteger(UUID.randomUUID().toString().replace("-", ""), 16) private
Definition at line 400 of file CConfiguration.java.
ResourceBundle.Control de.tu_clausthal.in.mec.CConfiguration.m_reader = new UTF8Control() private
Definition at line 396 of file CConfiguration.java.