MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.world.CWorld Class Reference
de.tu_clausthal.in.mec.object.world.CWorld Class Reference
world layer collection
Inherits Map< String, ILayer >.
Public Member Functions
final void clear ()
final boolean containsKey (final Object p_key)
final boolean containsValue (final Object p_value)
final Set< Entry< String,
ILayer > > entrySet ()
final ILayer get (final Object p_key)
final List< ILayer > getOrderedLayer ()
creates a list with the layer objects depends on the ordering value
final< T extends ILayer > T getTyped (final Object p_key)
returns a type-casted object
final boolean isEmpty ()
final Set< String > keySet ()
final ILayer put (final String p_key, final ILayer p_value)
final void putAll (final Map<?extends String,?extends ILayer > p_value)
final ILayer remove (final Object p_key)
final int size ()
final Collection< ILayer > values ()
Private Attributes
final Map< String, ILayer > m_layer = new HashMap<>()
map with layer
Detailed Description
Definition at line 45 of file CWorld.java.
Member Function Documentation
final void de.tu_clausthal.in.mec.object.world.CWorld.clear ()
Definition at line 145 of file CWorld.java.
final boolean de.tu_clausthal.in.mec.object.world.CWorld.containsKey (final Object p_key)
Definition at line 107 of file CWorld.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.getLayerName().
final boolean de.tu_clausthal.in.mec.object.world.CWorld.containsValue (final Object p_value)
Definition at line 113 of file CWorld.java.
final Set<Entry<String, ILayer> > de.tu_clausthal.in.mec.object.world.CWorld.entrySet ()
Definition at line 163 of file CWorld.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.web_static_listlayer().
final ILayer de.tu_clausthal.in.mec.object.world.CWorld.get (final Object p_key)
Definition at line 119 of file CWorld.java.
final List<ILayer> de.tu_clausthal.in.mec.object.world.CWorld.getOrderedLayer ()
Returns
list of layer
Definition at line 59 of file CWorld.java.
References de.tu_clausthal.in.mec.object.world.CWorld.m_layer.
final<T extends ILayer> T de.tu_clausthal.in.mec.object.world.CWorld.getTyped (final Object p_key)
Parameters
p_key key
Returns
casted value
Template Parameters
T value type
Definition at line 87 of file CWorld.java.
final boolean de.tu_clausthal.in.mec.object.world.CWorld.isEmpty ()
Definition at line 101 of file CWorld.java.
final Set<String> de.tu_clausthal.in.mec.object.world.CWorld.keySet ()
Definition at line 151 of file CWorld.java.
final ILayer de.tu_clausthal.in.mec.object.world.CWorld.put (final String p_key, final ILayer p_value)
Definition at line 127 of file CWorld.java.
final void de.tu_clausthal.in.mec.object.world.CWorld.putAll (final Map<?extends String,?extends ILayer > p_value)
Definition at line 139 of file CWorld.java.
final ILayer de.tu_clausthal.in.mec.object.world.CWorld.remove (final Object p_key)
Definition at line 133 of file CWorld.java.
final int de.tu_clausthal.in.mec.object.world.CWorld.size ()
Definition at line 95 of file CWorld.java.
final Collection<ILayer> de.tu_clausthal.in.mec.object.world.CWorld.values ()
Definition at line 157 of file CWorld.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.callLayerReset(), de.tu_clausthal.in.mec.runtime.CSimulation.callLayerStart(), and de.tu_clausthal.in.mec.runtime.CSimulation.callLayerStop().
Member Data Documentation
final Map<String, ILayer> de.tu_clausthal.in.mec.object.world.CWorld.m_layer = new HashMap<>() private
Definition at line 50 of file CWorld.java.
Referenced by de.tu_clausthal.in.mec.object.world.CWorld.getOrderedLayer().