MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.COSMMouseListener Class Reference
de.tu_clausthal.in.mec.ui.COSMMouseListener Class Reference
mouse listener for JxViewer
Inherits PanMouseInputListener.
Public Member Functions
COSMMouseListener (final JXMapViewer p_viewer)
ctor
void mouseClicked (final MouseEvent p_event)
void mouseMoved (final MouseEvent p_event)
Static Private Member Functions
static boolean isinBall (final Point p_click, final Point2D p_center)
checks if a point is in a radius around another
Static Private Attributes
static final int s_clickradius = 10
size of the click radius *
Detailed Description
Definition at line 47 of file COSMMouseListener.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.COSMMouseListener.COSMMouseListener (final JXMapViewer p_viewer)
Parameters
p_viewer OSM viewer reference
Definition at line 59 of file COSMMouseListener.java.
Member Function Documentation
static boolean de.tu_clausthal.in.mec.ui.COSMMouseListener.isinBall (final Point p_click, final Point2D p_center) static private
Parameters
p_click point of the click
p_center point of the center
Returns
bool if the click is within the radius
Definition at line 145 of file COSMMouseListener.java.
References de.tu_clausthal.in.mec.ui.COSMMouseListener.s_clickradius.
Referenced by de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseClicked().
void de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseClicked (final MouseEvent p_event)
Definition at line 65 of file COSMMouseListener.java.
References de.tu_clausthal.in.mec.ui.COSMViewer.getCurrentClickableLayer(), de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), de.tu_clausthal.in.mec.ui.COSMViewer.getViewpointGeoPosition(), and de.tu_clausthal.in.mec.ui.COSMMouseListener.isinBall().
void de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseMoved (final MouseEvent p_event)
Definition at line 116 of file COSMMouseListener.java.
References de.tu_clausthal.in.mec.ui.COSMViewer.getCurrentClickableLayer().
Member Data Documentation
final int de.tu_clausthal.in.mec.ui.COSMMouseListener.s_clickradius = 10 static private
Definition at line 52 of file COSMMouseListener.java.
Referenced by de.tu_clausthal.in.mec.ui.COSMMouseListener.isinBall().