MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.web.CBrowser Class Reference
de.tu_clausthal.in.mec.ui.web.CBrowser Class Reference
create a plain browser component to show any URL
Classes
enum EMenu
enum to define browser menubar *
Public Member Functions
CBrowser ()
ctor with instantiation a blank engine
CBrowser (final EMenu p_menu)
ctor with instantiation a blank engine
CBrowser (final EMenu p_menu, final String p_url)
ctor with instantiation the engine
final void back ()
navigates one item back
final void forward ()
navigates on item forward
final String getURL ()
returns the current URL
final void load (final String p_url)
loads a URL on the browser
final void reload ()
refresh the current URL
Private Member Functions
int setBackForward (final int p_column)
creates the back- and forward button
int setMenuBar (final EMenu p_menu)
sets the mennubar
int setURLMenu (final int p_column)
create the URL input box
Private Attributes
final WebView m_webview = new WebView()
webkit view
Static Private Attributes
static final String c_http = "http://"
http prefix
static final String c_https = "https://"
https prefix
Detailed Description
Definition at line 44 of file CBrowser.java.
Class Documentation
enum de::tu_clausthal::in::mec::ui::web::CBrowser::EMenu
Definition at line 276 of file CBrowser.java.
Class Members
BackForward value of menu with back-forward-button *
Full value of menu with all option *
None value of no-menu *
URL value of menu with URL-menu *
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.web.CBrowser.CBrowser ()
Definition at line 62 of file CBrowser.java.
References de.tu_clausthal.in.mec.ui.web.CBrowser.EMenu.None.
de.tu_clausthal.in.mec.ui.web.CBrowser.CBrowser (final EMenu p_menu)
Parameters
p_menu menu settings
Definition at line 73 of file CBrowser.java.
References de.tu_clausthal.in.mec.ui.web.CBrowser.m_webview.
de.tu_clausthal.in.mec.ui.web.CBrowser.CBrowser (final EMenu p_menu, final String p_url)
Parameters
p_menu menu settings
p_url string with URL
Definition at line 86 of file CBrowser.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.ui.web.CBrowser.load().
Member Function Documentation
final void de.tu_clausthal.in.mec.ui.web.CBrowser.back ()
Definition at line 97 of file CBrowser.java.
References de.tu_clausthal.in.mec.ui.web.CBrowser.m_webview.
final void de.tu_clausthal.in.mec.ui.web.CBrowser.forward ()
Definition at line 108 of file CBrowser.java.
References de.tu_clausthal.in.mec.ui.web.CBrowser.m_webview.
final String de.tu_clausthal.in.mec.ui.web.CBrowser.getURL ()
Returns
string URL
Definition at line 121 of file CBrowser.java.
final void de.tu_clausthal.in.mec.ui.web.CBrowser.load (final String p_url)
Parameters
p_url string with URL
Definition at line 131 of file CBrowser.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CBrowser.CBrowser().
final void de.tu_clausthal.in.mec.ui.web.CBrowser.reload ()
Definition at line 139 of file CBrowser.java.
int de.tu_clausthal.in.mec.ui.web.CBrowser.setBackForward (final int p_column) private
Parameters
p_column number of columns
Returns
number of elements
Definition at line 150 of file CBrowser.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
int de.tu_clausthal.in.mec.ui.web.CBrowser.setMenuBar (final EMenu p_menu) private
Parameters
p_menu menu settings
p_menu menu options
Returns
column number
Definition at line 199 of file CBrowser.java.
int de.tu_clausthal.in.mec.ui.web.CBrowser.setURLMenu (final int p_column) private
Parameters
p_column start column index
Returns
number of elements
Definition at line 232 of file CBrowser.java.
References de.tu_clausthal.in.mec.ui.web.CBrowser.c_http, de.tu_clausthal.in.mec.ui.web.CBrowser.c_https, and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Member Data Documentation
final String de.tu_clausthal.in.mec.ui.web.CBrowser.c_http = "http://" static private
Definition at line 49 of file CBrowser.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CBrowser.setURLMenu().
final String de.tu_clausthal.in.mec.ui.web.CBrowser.c_https = "https://" static private
Definition at line 53 of file CBrowser.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CBrowser.setURLMenu().
final WebView de.tu_clausthal.in.mec.ui.web.CBrowser.m_webview = new WebView() private
Definition at line 57 of file CBrowser.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CBrowser.back(), de.tu_clausthal.in.mec.ui.web.CBrowser.CBrowser(), and de.tu_clausthal.in.mec.ui.web.CBrowser.forward().