MecSim - Traffic Simulation: de.tu_clausthal.in.mec.runtime.CSimulation Class Reference
de.tu_clausthal.in.mec.runtime.CSimulation Class Reference
singleton object to performtemplate the simulation
Classes
class CStorage
peristent storage for any objects
Public Member Functions
final String generateObjectName (final String p_input, final Object p_object)
get a object name, depend on simulation data
CMessageSystem getMessageSystem ()
returns event manager
int getNumberOfRuns ()
returns the number of runs
CStorage getStorage ()
returns the storage
CWorld getWorld ()
returns the simulation world
boolean isRunning ()
checks the running state of the simulation
void load (final File p_input) throws IOException, ClassNotFoundException
loads the simulation from an input stream
void reset ()
resets the simulation data
final void setConfiguration ()
stores the current settings within the configuration
final void shutdown ()
shutdown the main loop
void start (final int p_steps) throws InterruptedException
runs the simulation for n steps
void start ()
runs the simulation of the current step
void stop ()
stops the current simulation
void store (final File p_output) throws IOException
stores the simulation in an output stream
Static Public Member Functions
static CSimulation getInstance ()
returns the singelton instance
Private Member Functions
CSimulation ()
private ctor
void callLayerReset ()
call on simulation reset on each layer
void callLayerStart ()
calls on simulation start on each layer
void callLayerStop ()
calls on simulation stop on each layer
String getLayerName (final Map< String, Object > p_data)
UI method - gets the layer name from the map.
void threadStartUp ()
starts the thread worker *
void web_static_disableenablelayer (final Map< String, Object > p_data)
UI method - disables / enables a layer.
Map< String, Object > web_static_getthreadsleep ()
UI method - set thread-sleep time.
void web_static_hideshowlayer (final Map< String, Object > p_data)
UI method - hide / show a layer.
Map< String, Map< String,
Object > > web_static_listlayer ()
UI method - returns a list with available layers.
void web_static_reset ()
UI method - reset the simulation.
void web_static_setthreadsleep (final Map< String, Object > p_data)
UI method - set thread-sleep time.
void web_static_start ()
UI method - start the simulation.
void web_static_stop ()
UI method - stop the simulation.
Private Attributes
final CMainLoop m_mainloop = new CMainLoop(CConfiguration.getInstance().get().<Integer>get("simulation/threadsleeptime"))
main loop
Thread m_mainloopthread
object of the thread loop *
final CMessageSystem m_messagesystem = new CMessageSystem()
event manager
final AtomicLong m_objectcounter = new AtomicLong(0)
object increment value - thread-safe
final Random m_random = new Random()
random object
int m_runs = 0
performtemplate count - counts each start call
CStorage m_storage = new CStorage()
global object storage
CWorld m_world = new CWorld()
world of the simulation
Static Private Attributes
static final CSimulation c_instance = new CSimulation()
singleton instance
Detailed Description
Definition at line 48 of file CSimulation.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.runtime.CSimulation.CSimulation () private
Definition at line 91 of file CSimulation.java.
Member Function Documentation
void de.tu_clausthal.in.mec.runtime.CSimulation.callLayerReset () private
Definition at line 314 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_world, and de.tu_clausthal.in.mec.object.world.CWorld.values().
void de.tu_clausthal.in.mec.runtime.CSimulation.callLayerStart () private
Definition at line 296 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_world, and de.tu_clausthal.in.mec.object.world.CWorld.values().
void de.tu_clausthal.in.mec.runtime.CSimulation.callLayerStop () private
Definition at line 305 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_world, and de.tu_clausthal.in.mec.object.world.CWorld.values().
final String de.tu_clausthal.in.mec.runtime.CSimulation.generateObjectName (final String p_input, final Object p_object)
Parameters
p_input input string
p_object object for object hash
Returns
string with name
Note
hash% with the object hash or 0, step% with the current simulation step, rand% with a random integer value, inc% increment value
Definition at line 115 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.getSimulationstep(), de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloop, de.tu_clausthal.in.mec.runtime.CSimulation.m_objectcounter, and de.tu_clausthal.in.mec.runtime.CSimulation.m_random.
static CSimulation de.tu_clausthal.in.mec.runtime.CSimulation.getInstance () static
Returns
simulation object
Definition at line 101 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.c_instance.
Referenced by de.tu_clausthal.in.mec.CBootstrap.afterOSMViewerInit(), de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CCarJasonAgent(), de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.CInconsistencyEnvironment(), de.tu_clausthal.in.mec.ui.IUIListener.IUIListener(), de.tu_clausthal.in.mec.ui.COSMMouseListener.mouseClicked(), de.tu_clausthal.in.mec.ui.IUIListener.mousePressed(), de.tu_clausthal.in.mec.CBootstrap.onApplicationClose(), de.tu_clausthal.in.mec.object.waypoint.point.IWayPointBase< T, P extends IFactory< T >, N extends IGenerator >.onClick(), de.tu_clausthal.in.mec.object.ISingleLayer.onSimulationReset(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.processLayer(), de.tu_clausthal.in.mec.object.IMultiLayer< T extends ISteppable &Painter >.repaint(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_remove(), de.tu_clausthal.in.mec.ui.CTrafficEnvironment.web_static_setdrivemodel(), and de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_write().
String de.tu_clausthal.in.mec.runtime.CSimulation.getLayerName (final Map< String, Object > p_data) private
Parameters
p_data input data
Returns
layer name
Definition at line 326 of file CSimulation.java.
References de.tu_clausthal.in.mec.object.world.CWorld.containsKey(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.runtime.CSimulation.m_world.
CMessageSystem de.tu_clausthal.in.mec.runtime.CSimulation.getMessageSystem ()
Definition at line 132 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_messagesystem.
int de.tu_clausthal.in.mec.runtime.CSimulation.getNumberOfRuns ()
Returns
performtemplate number
Definition at line 252 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_runs.
CStorage de.tu_clausthal.in.mec.runtime.CSimulation.getStorage ()
Definition at line 140 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_storage.
Referenced by de.tu_clausthal.in.mec.CBootstrap.onSimulationReset().
CWorld de.tu_clausthal.in.mec.runtime.CSimulation.getWorld ()
Definition at line 148 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_world.
boolean de.tu_clausthal.in.mec.runtime.CSimulation.isRunning ()
Returns
state
Definition at line 158 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.load(), de.tu_clausthal.in.mec.runtime.CSimulation.start(), de.tu_clausthal.in.mec.runtime.CSimulation.stop(), de.tu_clausthal.in.mec.runtime.CSimulation.store(), and de.tu_clausthal.in.mec.runtime.CSimulation.web_static_disableenablelayer().
void de.tu_clausthal.in.mec.runtime.CSimulation.load (final File p_input) throws IOException, ClassNotFoundException
Parameters
p_input input file
Exceptions
IOException throws the exception on file reading error
ClassNotFoundException throws the exception on deserialization
Bug:
incomplete routingmap
Definition at line 171 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.runtime.CSimulation.isRunning().
void de.tu_clausthal.in.mec.runtime.CSimulation.reset ()
Definition at line 185 of file CSimulation.java.
final void de.tu_clausthal.in.mec.runtime.CSimulation.setConfiguration ()
Definition at line 288 of file CSimulation.java.
final void de.tu_clausthal.in.mec.runtime.CSimulation.shutdown ()
Definition at line 240 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloop.
void de.tu_clausthal.in.mec.runtime.CSimulation.start (final int p_steps) throws InterruptedException
Parameters
p_steps number of steps
Exceptions
InterruptedException throws the exception on thread startup
Definition at line 203 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.runtime.CSimulation.isRunning(), de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloopthread, and de.tu_clausthal.in.mec.runtime.CSimulation.m_runs.
void de.tu_clausthal.in.mec.runtime.CSimulation.start ()
Definition at line 224 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.runtime.CSimulation.isRunning(), and de.tu_clausthal.in.mec.runtime.CSimulation.m_runs.
void de.tu_clausthal.in.mec.runtime.CSimulation.stop ()
Definition at line 260 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.runtime.CSimulation.isRunning().
void de.tu_clausthal.in.mec.runtime.CSimulation.store (final File p_output) throws IOException
Parameters
p_output output file
Exceptions
IOException throws the exception on file writing
Bug:
incomplete routing map
Definition at line 277 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.runtime.CSimulation.isRunning().
void de.tu_clausthal.in.mec.runtime.CSimulation.threadStartUp () private
Definition at line 341 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloop, and de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloopthread.
void de.tu_clausthal.in.mec.runtime.CSimulation.web_static_disableenablelayer (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 357 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.runtime.CSimulation.isRunning().
Map<String, Object> de.tu_clausthal.in.mec.runtime.CSimulation.web_static_getthreadsleep () private
Returns
data map
Definition at line 444 of file CSimulation.java.
void de.tu_clausthal.in.mec.runtime.CSimulation.web_static_hideshowlayer (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 372 of file CSimulation.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Map<String, Map<String, Object> > de.tu_clausthal.in.mec.runtime.CSimulation.web_static_listlayer () private
Returns
data map
Definition at line 387 of file CSimulation.java.
References de.tu_clausthal.in.mec.object.world.CWorld.entrySet(), and de.tu_clausthal.in.mec.runtime.CSimulation.m_world.
void de.tu_clausthal.in.mec.runtime.CSimulation.web_static_reset () private
Definition at line 408 of file CSimulation.java.
void de.tu_clausthal.in.mec.runtime.CSimulation.web_static_setthreadsleep (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 434 of file CSimulation.java.
References de.tu_clausthal.in.mec.runtime.core.CMainLoop.getSleepTime(), and de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloop.
void de.tu_clausthal.in.mec.runtime.CSimulation.web_static_start () private
Definition at line 416 of file CSimulation.java.
void de.tu_clausthal.in.mec.runtime.CSimulation.web_static_stop () private
Definition at line 424 of file CSimulation.java.
Member Data Documentation
final CSimulation de.tu_clausthal.in.mec.runtime.CSimulation.c_instance = new CSimulation() static private
Definition at line 54 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.getInstance().
final CMainLoop de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloop = new CMainLoop(CConfiguration.getInstance().get().<Integer>get("simulation/threadsleeptime")) private
Definition at line 58 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.generateObjectName(), de.tu_clausthal.in.mec.runtime.CSimulation.shutdown(), de.tu_clausthal.in.mec.runtime.CSimulation.threadStartUp(), and de.tu_clausthal.in.mec.runtime.CSimulation.web_static_setthreadsleep().
Thread de.tu_clausthal.in.mec.runtime.CSimulation.m_mainloopthread private
Definition at line 62 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.start(), and de.tu_clausthal.in.mec.runtime.CSimulation.threadStartUp().
final CMessageSystem de.tu_clausthal.in.mec.runtime.CSimulation.m_messagesystem = new CMessageSystem() private
Definition at line 66 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.getMessageSystem().
final AtomicLong de.tu_clausthal.in.mec.runtime.CSimulation.m_objectcounter = new AtomicLong(0) private
Definition at line 70 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.generateObjectName().
final Random de.tu_clausthal.in.mec.runtime.CSimulation.m_random = new Random() private
Definition at line 74 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.generateObjectName().
int de.tu_clausthal.in.mec.runtime.CSimulation.m_runs = 0 private
Definition at line 86 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.getNumberOfRuns(), and de.tu_clausthal.in.mec.runtime.CSimulation.start().
CStorage de.tu_clausthal.in.mec.runtime.CSimulation.m_storage = new CStorage() private
Definition at line 78 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.getStorage().
CWorld de.tu_clausthal.in.mec.runtime.CSimulation.m_world = new CWorld() private
Definition at line 82 of file CSimulation.java.
Referenced by de.tu_clausthal.in.mec.runtime.CSimulation.callLayerReset(), de.tu_clausthal.in.mec.runtime.CSimulation.callLayerStart(), de.tu_clausthal.in.mec.runtime.CSimulation.callLayerStop(), de.tu_clausthal.in.mec.runtime.CSimulation.getLayerName(), de.tu_clausthal.in.mec.runtime.CSimulation.getWorld(), and de.tu_clausthal.in.mec.runtime.CSimulation.web_static_listlayer().