MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T > Class Reference
de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T > Class Reference abstract
class of the Jason environment - the task of this class is the communication with outside data (IO with other structure), in this context the environment class encapsulate all behaviour inside, because it will be triggerd from the simulation core thread
Inherits IMultiLayer< CAgent< T > >.
Classes
class CLogger
interal log writer to catch Jason parsing messages
Public Member Functions
final void onSimulationReset ()
final void release ()
final void step (final int p_currentstep, final ILayer p_layer)
Static Public Member Functions
static void checkAgentFileSyntax (final String p_agentname)
checks the syntax of an agent
static File createAgentFile (final String p_agentname) throws IOException
creates an agent filename on an agent name
static File getAgentFile (final String p_agentname)
get from an agent name the storing file name
static String[] getAgentFiles ()
gets a list of all agents file names
Static Public Attributes
static final CAgentTemplateFactory AGENTTEMPLATEFACTORY = new CAgentTemplateFactory()
agent storage for fast instantiation
static final Map< String,
InternalAction > INTERNALACTION
static list of internal overwrite actions
Private Attributes
transient CBrowser m_mindinspector
browser of the mindinspector - binding to the server port can be done after the first agent is exists
Static Private Attributes
static final String c_filesuffix = ".asl"
agent file suffix *
Detailed Description
Template Parameters
T typ of agend binding objects
Warning
Jason binds a WebMindInspector on all network interfaces at the port 3272, without any kind of changing the binding https://sourceforge.net/p/jason/svn/1817/tree/trunk/src/jason/architecture/MindInspectorWeb.java
See Also
http://jason.sourceforge.net/
Definition at line 64 of file IEnvironment.java.
Member Function Documentation
static void de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.checkAgentFileSyntax (final String p_agentname) static
Parameters
p_agentname agent name
Note
should throw exception on syntax error
Warning
exception is not thrown on parsing error, the error is only send to log (see "Agent.parseAS" method), so we pass the log message to a variable, check the parsing result and the variable content for throwing an own exception
Definition at line 106 of file IEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static File de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.createAgentFile (final String p_agentname) throws IOException static
Parameters
p_agentname agent name
Returns
file object
Exceptions
IOException throws IO exception on file creating error
Definition at line 151 of file IEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static File de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.getAgentFile (final String p_agentname) static
Parameters
p_agentname agent name
Returns
existing file object
Note
must support a agent filename as file with extension and without extension
Definition at line 172 of file IEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static String [] de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.getAgentFiles () static
Returns
string list with the filenames only
Definition at line 185 of file IEnvironment.java.
References de.tu_clausthal.in.mec.CConfiguration.getInstance().
final void de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.onSimulationReset ()
Definition at line 195 of file IEnvironment.java.
final void de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.release ()
Definition at line 201 of file IEnvironment.java.
final void de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.step (final int p_currentstep, final ILayer p_layer)
Definition at line 209 of file IEnvironment.java.
Member Data Documentation
final CAgentTemplateFactory de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.AGENTTEMPLATEFACTORY = new CAgentTemplateFactory() static
Definition at line 70 of file IEnvironment.java.
final String de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.c_filesuffix = ".asl" static private
Definition at line 96 of file IEnvironment.java.
final Map<String, InternalAction> de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.INTERNALACTION static
Initial value:
= new HashMap<String, InternalAction>()
    {{
        final CInternalEmpty l_empty13 = new CInternalEmpty( 1, 3 );
        put( "jason.stdlib.clone", new CInternalEmpty() );
        put( "jason.stdlib.wait", l_empty13 );
        put( "jason.stdlib.create_agent", l_empty13 );
        put( "jason.stdlib.kill_agent", new CInternalEmpty( 1, 1 ) );
        put( "jason.stdlib.stopMAS", new CInternalEmpty( 0, 0 ) );
        put( "mecsim_literal2number", new CLiteral2Number() );
        put( "mecsim_removeBelief", new CBeliefRemove() );
        put( "mecsim_getRandom", new CRandom() );
    }}
Definition at line 74 of file IEnvironment.java.
transient CBrowser de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.m_mindinspector private
Definition at line 92 of file IEnvironment.java.