MecSim - Traffic Simulation: de.tu_clausthal.in.mec.common.CReflection Class Reference
de.tu_clausthal.in.mec.common.CReflection Class Reference
boilerplate code of the reflection API
Classes
class CClassIndex
class to represent a class index
class CGetSet
structure for getter and setter method handles
class CMethod
class for storing method access
class CMethodCache< T >
cache class of method invoker structure *
interface IFieldFilter
interface of field filtering
interface IMethodFilter
interface of method filtering
Static Public Member Functions
static CGetSet getClassField (final Class<?> p_class, final String p_field) throws IllegalArgumentException
get a class field of the class or super classes and returns getter / setter handles
static Map< String, CGetSet > getClassFields (final Class<?> p_class)
returns all fields of a class and the super classes
static Map< String, CGetSet > getClassFields (final Class<?> p_class, final IFieldFilter p_filter)
returns filtered fields of a class and the super classes
static CClassIndex getClassIndex ()
retruns the class index
static CMethod getClassMethod (final Class<?> p_class, final String p_method) throws IllegalArgumentException, IllegalAccessException
returns a void-method from a class
static CMethod getClassMethod (final Class<?> p_class, final String p_method, final Class<?>[] p_parameter) throws IllegalArgumentException, IllegalAccessException
returns a void-method from a class
static Map< String, CMethod > getClassMethods (final Class<?> p_class, final IMethodFilter p_filter)
returns filtered methods of a class and the super classes
Private Member Functions
CReflection ()
private ctor - avoid instantiation
Static Private Attributes
static final CClassIndex c_classindex
class index *
Detailed Description
Definition at line 66 of file CReflection.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.common.CReflection.CReflection () private
Definition at line 94 of file CReflection.java.
Member Function Documentation
static CGetSet de.tu_clausthal.in.mec.common.CReflection.getClassField (final Class<?> p_class, final String p_field) throws IllegalArgumentException static
Parameters
p_class class
p_field fieldname
Returns
getter / setter handle object
Definition at line 105 of file CReflection.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static Map<String, CGetSet> de.tu_clausthal.in.mec.common.CReflection.getClassFields (final Class<?> p_class) static
Parameters
p_class class
Returns
map with field name and getter / setter handle
Definition at line 140 of file CReflection.java.
static Map<String, CGetSet> de.tu_clausthal.in.mec.common.CReflection.getClassFields (final Class<?> p_class, final IFieldFilter p_filter) static
Parameters
p_class class
p_filter filtering object
Returns
map with field name and getter / setter handle
Definition at line 152 of file CReflection.java.
static CClassIndex de.tu_clausthal.in.mec.common.CReflection.getClassIndex () static
Returns
class index object
Definition at line 183 of file CReflection.java.
static CMethod de.tu_clausthal.in.mec.common.CReflection.getClassMethod (final Class<?> p_class, final String p_method) throws IllegalArgumentException, IllegalAccessException static
Parameters
p_class class
p_method methodname
Returns
method
Definition at line 195 of file CReflection.java.
static CMethod de.tu_clausthal.in.mec.common.CReflection.getClassMethod (final Class<?> p_class, final String p_method, final Class<?>[] p_parameter) throws IllegalArgumentException, IllegalAccessException static
Parameters
p_class class
p_method methodname
p_parameter array with type-classes to define method parameter e.g. new Class[]{Integer.TYPE, Integer.TYPE};
Returns
method
Definition at line 210 of file CReflection.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static Map<String, CMethod> de.tu_clausthal.in.mec.common.CReflection.getClassMethods (final Class<?> p_class, final IMethodFilter p_filter) static
Parameters
p_class class
p_filter filtering object
Returns
map with method name
Definition at line 238 of file CReflection.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.registerObject().
Member Data Documentation
final CClassIndex de.tu_clausthal.in.mec.common.CReflection.c_classindex static private
Initial value:
= new CClassIndex(CClassIndex.EFilter.WhiteList)
    {{
        filter(
                CConfiguration.getPackage(),
                "org.jxmapviewer",
                "com.graphhopper",
                "org.apache.commons.lang3.tuple",
                "java.lang", "java.util"
        );
        scan();
    }}
Note
use a whitelist for filtering, because it is faster
Definition at line 73 of file CReflection.java.