MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.analysis.CEvaluationStore Class Reference
de.tu_clausthal.in.mec.object.analysis.CEvaluationStore Class Reference
statistic evaluation access
Classes
class CCollectorAgent
worker to get beliefs of the agents
class CCollectorBelief
worker to get beliefs of the agents
class CCollectorFundamentalDiagram
worker to get data for fundamental diagram
class CCollectorInconsistency
worker to collect inconsistency via reflection
Public Member Functions
CEvaluationStore ()
ctor
final String toString ()
Public Member Functions inherited from de.tu_clausthal.in.mec.object.analysis.IDatabase
IDatabase ()
ctor - context initialization
final int getCalculationIndex ()
Protected Member Functions
final PreparedStatement createInsertStatement (final String p_tablename, final int p_fieldnumber) throws SQLException
creates the insert statement
final String createPrimaryKey (final String...p_fields)
builds the primary key SQL call
final String[] createTableFieldList (final String...p_fields)
builds the table field list
Protected Member Functions inherited from de.tu_clausthal.in.mec.object.analysis.IDatabase
final void createTable (final String p_tablename, final String[] p_fields, final String p_alter)
creates the table structure
final void createTable (final String p_tablename, final String[] p_fields, final String[] p_alter)
creates the table structure
final String getTableName (final String p_tablename)
returns the full table name
Private Member Functions
final void updateInsertStatement (final PreparedStatement p_statement, final int p_currentstep) throws SQLException
updates the current statement
Static Private Attributes
static String c_fundamentaldata = "fundamentaldata"
table name of fundamental diagram
static String c_tableagent = "agent"
table name of agent table
static String c_tablebeliefbase = "beliefbase"
table name of beliefbase table
static String c_tableinconsistency = "inconsistency"
table name of inconsistency table
Additional Inherited Members
Static Protected Member Functions inherited from de.tu_clausthal.in.mec.object.analysis.IDatabase
static boolean isConnectable ()
check if database is connectable
Static Protected Attributes inherited from de.tu_clausthal.in.mec.object.analysis.IDatabase
static final BasicDataSource c_datasource
datasource connection pool (static context)
Detailed Description
See Also
http://db.apache.org/ddlutils/
Definition at line 56 of file CEvaluationStore.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.CEvaluationStore ()
Definition at line 79 of file CEvaluationStore.java.
References de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_fundamentaldata, de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_tableagent, de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_tablebeliefbase, de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_tableinconsistency, and de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.createPrimaryKey().
Member Function Documentation
final PreparedStatement de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.createInsertStatement (final String p_tablename, final int p_fieldnumber) throws SQLException protected
Parameters
p_tablename table name
p_fieldnumber number of fields
Returns
prepare statement
Exceptions
SQLException is thrown on error
Note
the first two fields will be set with the instance definition
Definition at line 185 of file CEvaluationStore.java.
References de.tu_clausthal.in.mec.object.analysis.IDatabase.getTableName().
final String de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.createPrimaryKey (final String... p_fields) protected
Parameters
p_fields additional field list
Returns
string with SQL
Definition at line 159 of file CEvaluationStore.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.CEvaluationStore().
final String [] de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.createTableFieldList (final String... p_fields) protected
Parameters
p_fields additional fields
Returns
array with field list
Definition at line 141 of file CEvaluationStore.java.
final String de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.toString ()
Definition at line 130 of file CEvaluationStore.java.
final void de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.updateInsertStatement (final PreparedStatement p_statement, final int p_currentstep) throws SQLException private
Parameters
p_statement statement
p_currentstep current step
Exceptions
SQLException is thrown on error
Note
the second two fields are updates with the step definitions
Definition at line 210 of file CEvaluationStore.java.
Member Data Documentation
String de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_fundamentaldata = "fundamentaldata" static private
Definition at line 73 of file CEvaluationStore.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.CEvaluationStore().
String de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_tableagent = "agent" static private
Definition at line 61 of file CEvaluationStore.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.CEvaluationStore().
String de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_tablebeliefbase = "beliefbase" static private
Definition at line 69 of file CEvaluationStore.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.CEvaluationStore().
String de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.c_tableinconsistency = "inconsistency" static private
Definition at line 65 of file CEvaluationStore.java.
Referenced by de.tu_clausthal.in.mec.object.analysis.CEvaluationStore.CEvaluationStore().