MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T > Interface Reference
de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T > Interface Reference
interface for equal method names on masks and beliefbases
Public Member Functions
void add (final ILiteral< T > p_literal)
adds a literal in the current structure
IBeliefBaseMask< T > add (final IBeliefBaseMask< T > p_mask)
adds a mask into the current structure
void clear ()
clears all elements
< EextendsIBeliefBaseMask< T > E createMask (final String p_name)
returns a new mask of the belief base
< LextendsIStorage< ILiteral
< T >, IBeliefBaseMask< T >> L getStorage ()
returns the storage of the beliefbase
boolean isEmpty ()
checks if the structure empty
Iterator< IBeliefBaseMask< T > > iteratorBeliefBaseMask ()
iterator over all singlelements
Iterator< ILiteral< T > > iteratorLiteral ()
iterator over all multielements
boolean remove (final IBeliefBaseMask< T > p_mask)
removes a mask in the current structure
boolean remove (final ILiteral< T > p_literal)
removes a literal in the current structure
boolean remove (final String p_name)
removes mask and literal at the current structure
int size ()
number of element
int sizeLiteral ()
number of literals
int sizeMask ()
number of masks
void update ()
updates all items
Detailed Description
Definition at line 34 of file IBeliefBaseAction.java.
Member Function Documentation
void de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.add (final ILiteral< T > p_literal)
Parameters
p_literal literal
IBeliefBaseMask<T> de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.add (final IBeliefBaseMask< T > p_mask)
Parameters
p_mask mask
Note
the mask that is put in the method will be cloned, so the returned mask are not equal, the parameter is a template object only
Returns
returns the added mask
void de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.clear ()
<EextendsIBeliefBaseMask<T> E de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.createMask (final String p_name)
Parameters
p_name name of the mask
Returns
mask
<LextendsIStorage<ILiteral<T>,IBeliefBaseMask<T>> L de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.getStorage ()
Returns
storage
Template Parameters
L typecast
Referenced by de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsLiteral(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsMask(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getLiterals(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getMasks(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.iteratorBeliefBaseMask(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.iteratorLiteral(), and de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.toString().
boolean de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.isEmpty ()
Returns
empty boolean
Iterator<IBeliefBaseMask<T> > de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.iteratorBeliefBaseMask ()
Returns
iterator
Iterator<ILiteral<T> > de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.iteratorLiteral ()
Returns
iterator
boolean de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.remove (final IBeliefBaseMask< T > p_mask)
Parameters
p_mask mask
boolean de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.remove (final ILiteral< T > p_literal)
Parameters
p_literal literal
boolean de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.remove (final String p_name)
Parameters
p_name name
int de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.size ()
Returns
size
int de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.sizeLiteral ()
Returns
size
int de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.sizeMask ()
Returns
size
void de.tu_clausthal.in.mec.object.mas.generic.IBeliefBaseAction< T >.update ()
Warning
call update on a storage and on all storage-masks, if exists different masks which are point to the same storage, the update is called more than once, so the storage must limit the number of update calls