MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg Class Reference
de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg Class Reference
class of the Nagel-Schreckenberg drive model
Public Member Functions
void update (final int p_currentstep, final CCarLayer p_layer, final ICar p_car)
updates car
Protected Member Functions
final void checkAccelerationWithEdgeSpeed (final CCarLayer p_layer, final ICar p_car)
checks the acceleration and increment the speed
void checkCollision (final CCarLayer p_layer, final ICar p_car)
checks of a collision and reduce speed
final void checkLinger (final CCarLayer p_layer, final ICar p_car)
checks the linger probability and modify speed
Private Attributes
final Random m_random = new Random()
random object for linger probability *
Static Private Attributes
static final int c_minimalspeed = 15
defines the minimal speed in km/h
Detailed Description
See Also
http://en.wikipedia.org/wiki/Nagel%E2%80%93Schreckenberg_model
Definition at line 39 of file CNagelSchreckenberg.java.
Member Function Documentation
final void de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkAccelerationWithEdgeSpeed (final CCarLayer p_layer, final ICar p_car) protected
Parameters
p_layer car layer
p_car car object
Definition at line 65 of file CNagelSchreckenberg.java.
References de.tu_clausthal.in.mec.object.car.ICar.getAcceleration(), and de.tu_clausthal.in.mec.object.car.ICar.getEdge().
void de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkCollision (final CCarLayer p_layer, final ICar p_car) protected
Parameters
p_layer car layer
p_car car object
Definition at line 81 of file CNagelSchreckenberg.java.
References de.tu_clausthal.in.mec.object.car.ICar.getCurrentSpeed().
final void de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkLinger (final CCarLayer p_layer, final ICar p_car) protected
Parameters
p_layer car layer
p_car car object
Definition at line 101 of file CNagelSchreckenberg.java.
References de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.c_minimalspeed, de.tu_clausthal.in.mec.object.car.ICar.getCurrentSpeed(), de.tu_clausthal.in.mec.object.car.CCarLayer.getUnitConvert(), de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.m_random, and de.tu_clausthal.in.mec.object.car.ICar.setCurrentSpeed().
void de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.update (final int p_currentstep, final CCarLayer p_layer, final ICar p_car)
Parameters
p_currentstep current step number
p_layer car layer
p_car car object
Implements de.tu_clausthal.in.mec.object.car.drivemodel.IDriveModel.
Definition at line 52 of file CNagelSchreckenberg.java.
Member Data Documentation
final int de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.c_minimalspeed = 15 static private
Definition at line 45 of file CNagelSchreckenberg.java.
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkLinger().
final Random de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.m_random = new Random() private
Definition at line 49 of file CNagelSchreckenberg.java.
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkLinger().