MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.web.CServer Class Reference
de.tu_clausthal.in.mec.ui.web.CServer Class Reference
class of the HTTP server *
Inherits NanoHTTPD, and IWebSocketFactory.
Classes
class CWorkerPool
runner with performance optimizing, this runner uses a thread-stealing pool to handle request
Public Member Functions
CServer (final String p_host, final int p_port, final CVirtualDirectory p_default, final int p_websocketheartbeat)
ctor - starts the HTTP server
final CVirtualLocation getVirtualLocation ()
returns the virtual-location object
final WebSocket openWebSocket (final IHTTPSession p_session)
final void registerObject (final Object p_object)
registerObject an object for the UI
final void registerVirtualDirectory (final File p_source, final String p_index, final String p_uri)
adds a new virtual directory to the server with existance checking
final void registerVirtualDirectory (final File p_source, final String p_index, final String p_uri, final CMarkdownRenderer p_markdown)
adds a new virtual directory to the server with existance checking
final void registerVirtualDirectory (final String p_source, final String p_index, final String p_uri)
adds a new virtual directory to the server with existance checking
final void registerVirtualDirectory (final String p_source, final String p_index, final String p_uri, final CMarkdownRenderer p_markdown)
adds a new virtual directory to the server with existance checking
final void registerVirtualFile (final String p_source, final String p_uri)
adds a new virtual file to the server with existance checking
final Response serve (final IHTTPSession p_session)
Private Member Functions
void bindDynamicMethod (final Object p_object, final CReflection.CMethod p_method, final String p_uriclass)
dynamic method binding
void bindStaticMethod (final Object p_object, final CReflection.CMethod p_method, final String p_uriclass)
static method binding
String getMimeType (final URL p_url)
reads the mime-type of an URL - first try to detect a mime-type which has no "application" prefix
String getURIBase (final Object p_object)
returns URI base if exists
Response getVirtualDirFile (final IVirtualLocation p_location, final IHTTPSession p_session) throws Throwable
generates HTTP response of file & directory calls
Response getVirtualStaticMethod (final IVirtualLocation p_location, final IHTTPSession p_session) throws Throwable
generates HTTP response of a static method calls
Response setDefaultHeader (final Response p_response, final IHTTPSession p_session)
set default header items
Static Private Member Functions
static String toURLFormat (final String p_raw)
converts a Java string to the URL specification
Private Attributes
final PegDownProcessor m_markdown = new PegDownProcessor(Extensions.ALL)
markdown processor
final MimeUtil2 m_mimetype = new MimeUtil2()
mimetype detector
final CVirtualLocation m_virtuallocation
virtual-locations
final WebSocketResponseHandler m_websockethandler = new WebSocketResponseHandler(this)
websocket handler
final int m_websocketheartbeat
websocket heartbeat
Static Private Attributes
static final String c_seperator = "/"
seperator
static final String c_webdynamic = "web_dynamic_"
web-dynamic prefix
static final String c_webstatic = "web_static_"
web-static prefix
static final String c_weburibase = "web_uribase"
web-uribase name
Detailed Description
Definition at line 56 of file CServer.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.web.CServer.CServer (final String p_host, final int p_port, final CVirtualDirectory p_default, final int p_websocketheartbeat)
Parameters
p_host bind hostname
p_port bind port
p_default default location
p_websocketheartbeat websocket heartbeat
Definition at line 103 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.m_mimetype, de.tu_clausthal.in.mec.ui.web.CServer.m_virtuallocation, and de.tu_clausthal.in.mec.ui.web.CServer.m_websocketheartbeat.
Member Function Documentation
void de.tu_clausthal.in.mec.ui.web.CServer.bindDynamicMethod (final Object p_object, final CReflection.CMethod p_method, final String p_uriclass) private
Parameters
p_object bind object
p_method method object
p_uriclass class name
Definition at line 324 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.c_webdynamic, de.tu_clausthal.in.mec.ui.web.CServer.getURIBase(), de.tu_clausthal.in.mec.ui.web.CServer.m_websocketheartbeat, and de.tu_clausthal.in.mec.ui.web.CServer.toURLFormat().
void de.tu_clausthal.in.mec.ui.web.CServer.bindStaticMethod (final Object p_object, final CReflection.CMethod p_method, final String p_uriclass) private
Parameters
p_object bind object
p_method method object
p_uriclass class name
Definition at line 349 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.c_webstatic, de.tu_clausthal.in.mec.ui.web.CServer.getURIBase(), and de.tu_clausthal.in.mec.ui.web.CServer.toURLFormat().
String de.tu_clausthal.in.mec.ui.web.CServer.getMimeType (final URL p_url) private
Definition at line 365 of file CServer.java.
String de.tu_clausthal.in.mec.ui.web.CServer.getURIBase (final Object p_object) private
Parameters
p_object object
Returns
empty string or URI
Definition at line 386 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.c_seperator, de.tu_clausthal.in.mec.ui.web.CServer.c_weburibase, and de.tu_clausthal.in.mec.ui.web.CServer.toURLFormat().
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.bindDynamicMethod(), and de.tu_clausthal.in.mec.ui.web.CServer.bindStaticMethod().
Response de.tu_clausthal.in.mec.ui.web.CServer.getVirtualDirFile (final IVirtualLocation p_location, final IHTTPSession p_session) throws Throwable private
Parameters
p_location location object
p_session session object
Returns
response
Exceptions
Throwable on error
Definition at line 420 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.m_markdown.
final CVirtualLocation de.tu_clausthal.in.mec.ui.web.CServer.getVirtualLocation ()
Returns
location
Definition at line 136 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.m_virtuallocation.
Response de.tu_clausthal.in.mec.ui.web.CServer.getVirtualStaticMethod (final IVirtualLocation p_location, final IHTTPSession p_session) throws Throwable private
Parameters
p_location location object
p_session session object
Returns
response
Exceptions
Throwable on error
Definition at line 466 of file CServer.java.
final WebSocket de.tu_clausthal.in.mec.ui.web.CServer.openWebSocket (final IHTTPSession p_session)
Definition at line 142 of file CServer.java.
final void de.tu_clausthal.in.mec.ui.web.CServer.registerObject (final Object p_object)
Parameters
p_object object, all methods with the name "ui_" are registered
Note
a class / object need to implemente methods with the prefix "web_static_" or "web_dynamic_", which is bind to the server with the URL part "/classname/[basepart/]methodname" (without prefix). The methods "String web_uribase" returns the basepart of the URI
Definition at line 164 of file CServer.java.
References de.tu_clausthal.in.mec.ui.web.CServer.c_seperator, de.tu_clausthal.in.mec.ui.web.CServer.c_webdynamic, de.tu_clausthal.in.mec.ui.web.CServer.c_webstatic, and de.tu_clausthal.in.mec.common.CReflection.getClassMethods().
final void de.tu_clausthal.in.mec.ui.web.CServer.registerVirtualDirectory (final File p_source, final String p_index, final String p_uri)
Parameters
p_source source file object
p_index index file
p_uri URI
Definition at line 197 of file CServer.java.
final void de.tu_clausthal.in.mec.ui.web.CServer.registerVirtualDirectory (final File p_source, final String p_index, final String p_uri, final CMarkdownRenderer p_markdown)
Parameters
p_source source file object
p_index index file
p_uri URI
p_markdown markdown renderer
Definition at line 210 of file CServer.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceURL().
final void de.tu_clausthal.in.mec.ui.web.CServer.registerVirtualDirectory (final String p_source, final String p_index, final String p_uri)
Parameters
p_source relative source path
p_index index file
p_uri URI
Definition at line 230 of file CServer.java.
final void de.tu_clausthal.in.mec.ui.web.CServer.registerVirtualDirectory (final String p_source, final String p_index, final String p_uri, final CMarkdownRenderer p_markdown)
Parameters
p_source relative source path
p_index index file
p_uri URI
p_markdown markdown renderer
Definition at line 243 of file CServer.java.
final void de.tu_clausthal.in.mec.ui.web.CServer.registerVirtualFile (final String p_source, final String p_uri)
Parameters
p_source relative source path
p_uri URI
Definition at line 254 of file CServer.java.
final Response de.tu_clausthal.in.mec.ui.web.CServer.serve (final IHTTPSession p_session)
Definition at line 269 of file CServer.java.
Response de.tu_clausthal.in.mec.ui.web.CServer.setDefaultHeader (final Response p_response, final IHTTPSession p_session) private
Parameters
p_response response
p_session session
Returns
modified response
Definition at line 479 of file CServer.java.
static String de.tu_clausthal.in.mec.ui.web.CServer.toURLFormat (final String p_raw) static private
Parameters
p_raw Java raw string
Returns
modfied string
Warning
only lower-case chars, number and underscore are allowed
Definition at line 312 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.bindDynamicMethod(), de.tu_clausthal.in.mec.ui.web.CServer.bindStaticMethod(), and de.tu_clausthal.in.mec.ui.web.CServer.getURIBase().
Member Data Documentation
final String de.tu_clausthal.in.mec.ui.web.CServer.c_seperator = "/" static private
Definition at line 61 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.getURIBase(), and de.tu_clausthal.in.mec.ui.web.CServer.registerObject().
final String de.tu_clausthal.in.mec.ui.web.CServer.c_webdynamic = "web_dynamic_" static private
Definition at line 65 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.bindDynamicMethod(), and de.tu_clausthal.in.mec.ui.web.CServer.registerObject().
final String de.tu_clausthal.in.mec.ui.web.CServer.c_webstatic = "web_static_" static private
Definition at line 69 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.bindStaticMethod(), and de.tu_clausthal.in.mec.ui.web.CServer.registerObject().
final String de.tu_clausthal.in.mec.ui.web.CServer.c_weburibase = "web_uribase" static private
Definition at line 73 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.getURIBase().
final PegDownProcessor de.tu_clausthal.in.mec.ui.web.CServer.m_markdown = new PegDownProcessor(Extensions.ALL) private
Definition at line 77 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.getVirtualDirFile().
final MimeUtil2 de.tu_clausthal.in.mec.ui.web.CServer.m_mimetype = new MimeUtil2() private
Definition at line 81 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.CServer().
final CVirtualLocation de.tu_clausthal.in.mec.ui.web.CServer.m_virtuallocation private
Definition at line 85 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.CServer(), and de.tu_clausthal.in.mec.ui.web.CServer.getVirtualLocation().
final WebSocketResponseHandler de.tu_clausthal.in.mec.ui.web.CServer.m_websockethandler = new WebSocketResponseHandler(this) private
Definition at line 89 of file CServer.java.
final int de.tu_clausthal.in.mec.ui.web.CServer.m_websocketheartbeat private
Definition at line 93 of file CServer.java.
Referenced by de.tu_clausthal.in.mec.ui.web.CServer.bindDynamicMethod(), and de.tu_clausthal.in.mec.ui.web.CServer.CServer().