MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CAgentEnvironment Class Reference
de.tu_clausthal.in.mec.ui.CAgentEnvironment Class Reference
encapsulating class for multi-agent UI components
Public Member Functions
CAgentEnvironment (final EAgentLanguages p_type)
ctor
Private Member Functions
final String getAgentName (final Map< String, Object > p_data)
UI method - gets the agent name from the map.
final void web_static_check (final Map< String, Object > p_data)
UI method - checks the syntax of an agent.
final void web_static_create (final Map< String, Object > p_data) throws IOException
creates a new agent
final Map< String, List< String > > web_static_list ()
UI method - returns a list of all agents.
final Map< String, Object > web_static_read (final Map< String, Object > p_data) throws IOException
UI method - reads the file content of an agent.
final void web_static_remove (final Map< String, Object > p_data)
UI method - delete an agent.
final void web_static_write (final Map< String, Object > p_data) throws IOException
UI method - writes the content to the agent file.
final String web_uribase ()
UI method - returns URI base.
Private Attributes
final String m_baseuri
base URI *
final EAgentLanguages m_type
type of the MAS name *
Detailed Description
Definition at line 44 of file CAgentEnvironment.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.CAgentEnvironment.CAgentEnvironment (final EAgentLanguages p_type)
Parameters
p_type MAS type
Definition at line 61 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_baseuri, and de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
Member Function Documentation
final String de.tu_clausthal.in.mec.ui.CAgentEnvironment.getAgentName (final Map< String, Object > p_data) private
Parameters
p_data input data
Returns
agent name
Definition at line 80 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
final void de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_check (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 93 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
final void de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_create (final Map< String, Object > p_data) throws IOException private
Parameters
p_data input data
Definition at line 110 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
final Map<String, List<String> > de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_list () private
Returns
agent list
Definition at line 126 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
final Map<String, Object> de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_read (final Map< String, Object > p_data) throws IOException private
Parameters
p_data input data
Returns
file content
Definition at line 148 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
final void de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_remove (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 167 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
final void de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_write (final Map< String, Object > p_data) throws IOException private
Parameters
p_data input data
Definition at line 187 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type.
final String de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_uribase () private
Returns
base name
Definition at line 209 of file CAgentEnvironment.java.
References de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_baseuri.
Member Data Documentation
final String de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_baseuri private
Definition at line 50 of file CAgentEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CAgentEnvironment.CAgentEnvironment(), and de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_uribase().
final EAgentLanguages de.tu_clausthal.in.mec.ui.CAgentEnvironment.m_type private
Definition at line 54 of file CAgentEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CAgentEnvironment.CAgentEnvironment(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_check(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_create(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_list(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_read(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_remove(), and de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_write().