MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.car.ICar Interface Reference
de.tu_clausthal.in.mec.object.car.ICar Interface Reference
car interface for defining the car structure
Public Member Functions
int getAcceleration ()
define an individual acceleration
int getCurrentSpeed ()
returns the current speed of the car
int getDeceleration ()
define an individual deceleration
EdgeIteratorState getEdge ()
get current edge object on the graph
GeoPosition getGeoposition ()
returns the current geo position of the car
double getLingerProbability ()
returns a probability for lingering
int getMaximumSpeed ()
returns the maximum speed of the car
Map< Double, ICar > getPredecessor ()
returns the current predecessor of the car and the distance
Map< Double, ICar > getPredecessor (int p_count)
returns the current predecessor of the car and the distance
boolean hasEndReached ()
boolean method, that returns true, if the car has reached its end
void setCurrentSpeed (int p_speed) throws IllegalArgumentException
sets the current speed of the care
Public Member Functions inherited from de.tu_clausthal.in.mec.runtime.IVoidSteppable
void step (final int p_currentstep, final ILayer p_layer) throws Exception
step method
Public Member Functions inherited from de.tu_clausthal.in.mec.runtime.ISteppable
void release ()
release function to remove object *
Detailed Description
Definition at line 39 of file ICar.java.
Member Function Documentation
int de.tu_clausthal.in.mec.object.car.ICar.getAcceleration ()
Returns
number (greater than zero) in m/sec^2
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkAccelerationWithEdgeSpeed().
int de.tu_clausthal.in.mec.object.car.ICar.getCurrentSpeed ()
Returns
speed in km/h
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkCollision(), and de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkLinger().
int de.tu_clausthal.in.mec.object.car.ICar.getDeceleration ()
Returns
number (greater than zero) in m/sec^2
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
EdgeIteratorState de.tu_clausthal.in.mec.object.car.ICar.getEdge ()
Returns
edge
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkAccelerationWithEdgeSpeed().
GeoPosition de.tu_clausthal.in.mec.object.car.ICar.getGeoposition ()
Returns
geoposition
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
double de.tu_clausthal.in.mec.object.car.ICar.getLingerProbability ()
Returns
double value in [0,1]
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
int de.tu_clausthal.in.mec.object.car.ICar.getMaximumSpeed ()
Returns
speed value in km/h
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
Map<Double, ICar> de.tu_clausthal.in.mec.object.car.ICar.getPredecessor ()
Returns
predecessor car object and its distance in m
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.getPredecessorWithName().
Map<Double, ICar> de.tu_clausthal.in.mec.object.car.ICar.getPredecessor (int p_count)
Parameters
p_count number of predecessors
Returns
predecessor car object and its distance in meter
boolean de.tu_clausthal.in.mec.object.car.ICar.hasEndReached ()
Returns
boolean for reaching the end
Implemented in de.tu_clausthal.in.mec.object.car.CDefaultCar.
Referenced by de.tu_clausthal.in.mec.object.car.CCarLayer.afterStepObject().
void de.tu_clausthal.in.mec.object.car.ICar.setCurrentSpeed (int p_speed) throws IllegalArgumentException
Parameters
p_speed speed value in km/h
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkLinger().