MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage Class Reference
de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage Class Reference
beliefbase structure for message beliefs
Inherits IOneTimeStorage< ILiteral< Literal >, IBeliefBaseMask< Literal > >.
Public Member Functions
CMessageStorage (final TransitionSystem p_transitionSystem, final String p_pathseparator)
ctor - with transition system specified
final void receiveMessage (final Set< IMessage > p_messages)
method for registering incoming messages
Protected Member Functions
void updating ()
Private Member Functions
void addElement (final ILiteral< Literal > p_literal)
adds an literal to the element
Private Attributes
final Set< IMessage > m_receivedmessages = new HashSet<>()
set with received messages
final String m_seperator
path seperator
final TransitionSystem m_transitionSystem
transition system for agent cycle
Detailed Description
Definition at line 50 of file CMessageStorage.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.CMessageStorage (final TransitionSystem p_transitionSystem, final String p_pathseparator)
Parameters
p_transitionSystem agent transition system
p_pathseparator path separator
Definition at line 71 of file CMessageStorage.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_seperator, and de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_transitionSystem.
Member Function Documentation
void de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.addElement (final ILiteral< Literal > p_literal) private
Parameters
p_literal
Definition at line 142 of file CMessageStorage.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.updating().
final void de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.receiveMessage (final Set< IMessage > p_messages)
Parameters
p_messages current incoming messages
Definition at line 83 of file CMessageStorage.java.
void de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.updating () protected
Todo:
untell should iterator over all BB
Definition at line 93 of file CMessageStorage.java.
References de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.addElement(), de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_receivedmessages, and de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_seperator.
Member Data Documentation
final Set<IMessage> de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_receivedmessages = new HashSet<>() private
Definition at line 55 of file CMessageStorage.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.updating().
final String de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_seperator private
Definition at line 59 of file CMessageStorage.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.CMessageStorage(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.updating().
final TransitionSystem de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.m_transitionSystem private
Definition at line 63 of file CMessageStorage.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CMessageStorage.CMessageStorage().