MecSim - Traffic Simulation: de.tu_clausthal.in.mec.common.CTreeNode< T > Class Reference
de.tu_clausthal.in.mec.common.CTreeNode< T > Class Reference
tree structure
Public Member Functions
CTreeNode (final String p_identifier)
ctor
CTreeNode (final String p_identifier, final CTreeNode< T > p_parent)
ctor
final void addChild (final Collection< String > p_names)
adds a list of path to the current node
final CTreeNode< T > addChild (final String p_name)
adds all childs of the path to the current node
final CTreeNode< T > getChild (final String p_name)
returns a child under the current node
final Collection< CTreeNode< T > > getChilds ()
returns all child nodes
final T getData ()
returns the data of the current node
final CPath getFQN ()
get the full path to the node
final String getID ()
get ID of the node
final CTreeNode< T > getNode (final String p_path)
returns the node
final CTreeNode< T > getNode (final CPath p_path)
returns the node
final Set< CPath > getTree ()
returns a set of all sub nodes
final Set< CPath > getTree (final boolean p_withroot)
returns a set of all sub nodes
final List< T > getTreeData ()
gets all data of all subnodes
final List< T > getTreeData (final boolean p_withroot)
gets all data of all subnodes
final boolean hasParent ()
check if a parent exists
final boolean isDataNull ()
checks if the data is null
final boolean pathExist (final String p_path)
checks the existing of a path
final boolean pathExist (final CPath p_path)
checks the existing of a path
final CTreeNode< T > removeChild (final String p_name)
remove a child node
final void setData (final Collection< Pair< CPath, T >> p_data)
adds a collection of pair with path and data
final void setData (final T p_data)
sets the data to the current node
final String toString ()
in-order traversing
Protected Member Functions
final CPath getFQN (final CTreeNode< T > p_node)
traverse up to root node
final CTreeNode< T > getNode (final CTreeNode< T > p_node, final CPath p_path, final int p_index)
returns the node
final void getTree (final CPath p_path, final CTreeNode< T > p_node, final Set< CPath > p_set)
traversing of the nodes
Private Attributes
final Map< String, CTreeNode< T > > m_childs = new HashMap<>()
map with child names and nodes *
T m_data
data of the node *
final String m_id
ID / name of the node *.
final CTreeNode< T > m_parent
reference to the parent node *
Detailed Description
Definition at line 42 of file CTreeNode.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.common.CTreeNode< T >.CTreeNode (final String p_identifier)
Parameters
p_identifier name of the node
Definition at line 67 of file CTreeNode.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
de.tu_clausthal.in.mec.common.CTreeNode< T >.CTreeNode (final String p_identifier, final CTreeNode< T > p_parent)
Parameters
p_identifier name of the node
p_parent parent node
Definition at line 82 of file CTreeNode.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Member Function Documentation
final void de.tu_clausthal.in.mec.common.CTreeNode< T >.addChild (final Collection< String > p_names)
Parameters
p_names collections of names
Definition at line 97 of file CTreeNode.java.
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.addChild (final String p_name)
Parameters
p_name name of the child
Returns
tree node
Definition at line 109 of file CTreeNode.java.
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.getChild (final String p_name)
Parameters
p_name name
Returns
node
Definition at line 123 of file CTreeNode.java.
final Collection<CTreeNode<T> > de.tu_clausthal.in.mec.common.CTreeNode< T >.getChilds ()
Returns
collection of child nodes
Definition at line 133 of file CTreeNode.java.
final T de.tu_clausthal.in.mec.common.CTreeNode< T >.getData ()
Returns
data
Definition at line 143 of file CTreeNode.java.
final CPath de.tu_clausthal.in.mec.common.CTreeNode< T >.getFQN ()
Returns
full path to this node
Definition at line 174 of file CTreeNode.java.
final CPath de.tu_clausthal.in.mec.common.CTreeNode< T >.getFQN (final CTreeNode< T > p_node) protected
Parameters
p_node node
Returns
ID
Definition at line 348 of file CTreeNode.java.
References de.tu_clausthal.in.mec.common.CTreeNode< T >.hasParent(), de.tu_clausthal.in.mec.common.CTreeNode< T >.m_id, de.tu_clausthal.in.mec.common.CTreeNode< T >.m_parent, and de.tu_clausthal.in.mec.common.CPath.pushfront().
final String de.tu_clausthal.in.mec.common.CTreeNode< T >.getID ()
Returns
ID
Definition at line 184 of file CTreeNode.java.
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.getNode (final String p_path)
Parameters
p_path path of the node
Returns
node
Definition at line 195 of file CTreeNode.java.
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.getNode (final CPath p_path)
Parameters
p_path path of the node
Returns
node
Definition at line 206 of file CTreeNode.java.
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.getNode (final CTreeNode< T > p_node, final CPath p_path, final int p_index) protected
Parameters
p_node current node
p_path path
p_index current path index
Returns
node
Definition at line 366 of file CTreeNode.java.
References de.tu_clausthal.in.mec.common.CPath.get(), de.tu_clausthal.in.mec.common.CTreeNode< T >.m_childs, and de.tu_clausthal.in.mec.common.CPath.size().
final Set<CPath> de.tu_clausthal.in.mec.common.CTreeNode< T >.getTree ()
Returns
set of nodes
Definition at line 216 of file CTreeNode.java.
final Set<CPath> de.tu_clausthal.in.mec.common.CTreeNode< T >.getTree (final boolean p_withroot)
Parameters
p_withroot with root node
Returns
set of nodes
Definition at line 227 of file CTreeNode.java.
final void de.tu_clausthal.in.mec.common.CTreeNode< T >.getTree (final CPath p_path, final CTreeNode< T > p_node, final Set< CPath > p_set) protected
Parameters
p_path start node path
p_node start node
p_set return set
Definition at line 384 of file CTreeNode.java.
References de.tu_clausthal.in.mec.common.CPath.isEmpty().
final List<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.getTreeData ()
Returns
list of data
Definition at line 242 of file CTreeNode.java.
final List<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.getTreeData (final boolean p_withroot)
Parameters
p_withroot list with the root node
Returns
list of data
Definition at line 253 of file CTreeNode.java.
final boolean de.tu_clausthal.in.mec.common.CTreeNode< T >.hasParent ()
Returns
bool for parent exists
Definition at line 271 of file CTreeNode.java.
Referenced by de.tu_clausthal.in.mec.common.CTreeNode< T >.getFQN().
final boolean de.tu_clausthal.in.mec.common.CTreeNode< T >.isDataNull ()
Returns
null flag
Definition at line 281 of file CTreeNode.java.
final boolean de.tu_clausthal.in.mec.common.CTreeNode< T >.pathExist (final String p_path)
Parameters
p_path path
Returns
existing flag
Definition at line 292 of file CTreeNode.java.
final boolean de.tu_clausthal.in.mec.common.CTreeNode< T >.pathExist (final CPath p_path)
Parameters
p_path path
Returns
existing flag
Definition at line 303 of file CTreeNode.java.
References de.tu_clausthal.in.mec.common.CTreeNode< T >.m_childs.
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.removeChild (final String p_name)
Parameters
p_name ID
Returns
removed node
Definition at line 324 of file CTreeNode.java.
final void de.tu_clausthal.in.mec.common.CTreeNode< T >.setData (final Collection< Pair< CPath, T >> p_data)
Parameters
p_data collection of pair with path and data
Definition at line 153 of file CTreeNode.java.
final void de.tu_clausthal.in.mec.common.CTreeNode< T >.setData (final T p_data)
Parameters
p_data data
Definition at line 164 of file CTreeNode.java.
final String de.tu_clausthal.in.mec.common.CTreeNode< T >.toString ()
Returns
tree structure
Definition at line 334 of file CTreeNode.java.
Member Data Documentation
final Map<String, CTreeNode<T> > de.tu_clausthal.in.mec.common.CTreeNode< T >.m_childs = new HashMap<>() private
Definition at line 48 of file CTreeNode.java.
Referenced by de.tu_clausthal.in.mec.common.CTreeNode< T >.getNode(), and de.tu_clausthal.in.mec.common.CTreeNode< T >.pathExist().
T de.tu_clausthal.in.mec.common.CTreeNode< T >.m_data private
Definition at line 52 of file CTreeNode.java.
final String de.tu_clausthal.in.mec.common.CTreeNode< T >.m_id private
Definition at line 56 of file CTreeNode.java.
Referenced by de.tu_clausthal.in.mec.common.CTreeNode< T >.getFQN().
final CTreeNode<T> de.tu_clausthal.in.mec.common.CTreeNode< T >.m_parent private
Definition at line 60 of file CTreeNode.java.
Referenced by de.tu_clausthal.in.mec.common.CTreeNode< T >.getFQN().