MecSim - Traffic Simulation: de.tu_clausthal.in.mec.Test_CLanguageLabels Class Reference
de.tu_clausthal.in.mec.Test_CLanguageLabels Class Reference
test all resource strings
Classes
class MyMethodVisitor
AST visitor class.
Public Member Functions
void testResourceString ()
test-case all resource strings
Private Member Functions
void checkFile (final Path p_file) throws IOException
checks all labels within a Java file
Static Private Member Functions
static String getPackagePath (String...p_names)
method to build a package path
Private Attributes
final Set< String > m_labels = new HashSet<>()
set with all labels *
final Pattern m_language = Pattern.compile(m_translatemethod + ".+\\)")
reg expression to extract label data *
final String m_translatemethod = "CCommon.getResourceString"
method to translate strings
Static Private Attributes
static final Set< String > c_searchpackages
list of all project packages for searching classes
Detailed Description
Definition at line 59 of file Test_CLanguageLabels.java.
Member Function Documentation
void de.tu_clausthal.in.mec.Test_CLanguageLabels.checkFile (final Path p_file) throws IOException private
Parameters
p_file
Definition at line 142 of file Test_CLanguageLabels.java.
static String de.tu_clausthal.in.mec.Test_CLanguageLabels.getPackagePath (String... p_names) static private
Parameters
p_names list of package parts
Returns
full-qualified string
Definition at line 129 of file Test_CLanguageLabels.java.
Referenced by de.tu_clausthal.in.mec.Test_CLanguageLabels.MyMethodVisitor.getClass().
void de.tu_clausthal.in.mec.Test_CLanguageLabels.testResourceString ()
Definition at line 91 of file Test_CLanguageLabels.java.
References de.tu_clausthal.in.mec.CConfiguration.getInstance(), and de.tu_clausthal.in.mec.Test_CLanguageLabels.m_labels.
Member Data Documentation
final Set<String> de.tu_clausthal.in.mec.Test_CLanguageLabels.c_searchpackages static private
Initial value:
= new HashSet<String>()
    {{
        for ( String l_package : new String[]{
                getPackagePath( "object", "mas", "inconsistency" )
        } )
            add( getPackagePath( CConfiguration.getPackage(), l_package ) );
    }}
Note
is needed on finding class-calls within other classes e.g. class a.b.c uses y.x.class
Definition at line 66 of file Test_CLanguageLabels.java.
Referenced by de.tu_clausthal.in.mec.Test_CLanguageLabels.MyMethodVisitor.getClass().
final Set<String> de.tu_clausthal.in.mec.Test_CLanguageLabels.m_labels = new HashSet<>() private
Definition at line 77 of file Test_CLanguageLabels.java.
Referenced by de.tu_clausthal.in.mec.Test_CLanguageLabels.testResourceString().
final Pattern de.tu_clausthal.in.mec.Test_CLanguageLabels.m_language = Pattern.compile(m_translatemethod + ".+\\)") private
Definition at line 85 of file Test_CLanguageLabels.java.
final String de.tu_clausthal.in.mec.Test_CLanguageLabels.m_translatemethod = "CCommon.getResourceString" private
Definition at line 81 of file Test_CLanguageLabels.java.
Referenced by de.tu_clausthal.in.mec.Test_CLanguageLabels.MyMethodVisitor.getParameter().