MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.IUIListener Class Reference
de.tu_clausthal.in.mec.ui.IUIListener Class Reference abstract
class to handle UI events with encapsulate the default lister structures
Public Member Functions
IUIListener ()
ctor to registerObject component on the viewer
final void mouseClicked (final MouseEvent p_event)
final void mouseEntered (final MouseEvent p_event)
final void mouseExited (final MouseEvent p_event)
final void mousePressed (final MouseEvent p_event)
final void mouseReleased (final MouseEvent p_event)
void onClick (final MouseEvent p_event, final JXMapViewer p_viewer)
click method which is called by a click on the object
void release ()
release of the event handler
Protected Member Functions
final double iconscale (final JXMapViewer p_viewer)
returns the normalized zoom level
final int iconsize (final JXMapViewer p_viewer)
returns the icon size
Static Protected Attributes
static final int c_maxzoom = 9
maximum zoom value *
static final int c_miniconsize = 3
minimum icon size *
Detailed Description
Definition at line 38 of file IUIListener.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.IUIListener.IUIListener ()
Definition at line 54 of file IUIListener.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance().
Member Function Documentation
final double de.tu_clausthal.in.mec.ui.IUIListener.iconscale (final JXMapViewer p_viewer) protected
Parameters
p_viewer viewer object
Returns
value in [0,1] with scale of the current zoom level
Definition at line 111 of file IUIListener.java.
References de.tu_clausthal.in.mec.ui.IUIListener.c_maxzoom, and de.tu_clausthal.in.mec.ui.IUIListener.c_miniconsize.
final int de.tu_clausthal.in.mec.ui.IUIListener.iconsize (final JXMapViewer p_viewer) protected
Parameters
p_viewer viewer object
Returns
circle size
Definition at line 122 of file IUIListener.java.
References de.tu_clausthal.in.mec.ui.IUIListener.c_maxzoom, and de.tu_clausthal.in.mec.ui.IUIListener.c_miniconsize.
final void de.tu_clausthal.in.mec.ui.IUIListener.mouseClicked (final MouseEvent p_event)
Definition at line 61 of file IUIListener.java.
final void de.tu_clausthal.in.mec.ui.IUIListener.mouseEntered (final MouseEvent p_event)
Definition at line 78 of file IUIListener.java.
final void de.tu_clausthal.in.mec.ui.IUIListener.mouseExited (final MouseEvent p_event)
Definition at line 83 of file IUIListener.java.
final void de.tu_clausthal.in.mec.ui.IUIListener.mousePressed (final MouseEvent p_event)
Definition at line 66 of file IUIListener.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), and de.tu_clausthal.in.mec.ui.IUIListener.onClick().
final void de.tu_clausthal.in.mec.ui.IUIListener.mouseReleased (final MouseEvent p_event)
Definition at line 73 of file IUIListener.java.
void de.tu_clausthal.in.mec.ui.IUIListener.onClick (final MouseEvent p_event, final JXMapViewer p_viewer)
Parameters
p_event mouse event
p_viewer viewer
Definition at line 93 of file IUIListener.java.
Referenced by de.tu_clausthal.in.mec.ui.IUIListener.mousePressed().
void de.tu_clausthal.in.mec.ui.IUIListener.release ()
Definition at line 100 of file IUIListener.java.
Member Data Documentation
final int de.tu_clausthal.in.mec.ui.IUIListener.c_maxzoom = 9 static protected
Definition at line 44 of file IUIListener.java.
Referenced by de.tu_clausthal.in.mec.ui.IUIListener.iconscale(), and de.tu_clausthal.in.mec.ui.IUIListener.iconsize().
final int de.tu_clausthal.in.mec.ui.IUIListener.c_miniconsize = 3 static protected
Definition at line 48 of file IUIListener.java.
Referenced by de.tu_clausthal.in.mec.ui.IUIListener.iconscale(), and de.tu_clausthal.in.mec.ui.IUIListener.iconsize().