MecSim - Traffic Simulation: de.tu_clausthal.in.mec.common.CPath Class Reference
de.tu_clausthal.in.mec.common.CPath Class Reference
class to create a path structure
Inherits Iterable< CPath >, and Comparable< CPath >.
Public Member Functions
CPath (final CPath p_path, final String...p_varargs)
copy-ctor with arguments
CPath (final CPath p_path)
copy-ctor
CPath (final String...p_varargs)
ctor
CPath (final Collection< String > p_collection)
ctor
final CPath append (final CPath p_path)
appends a path at the current and returns a new object
final CPath append (final String p_path)
appends a string at the current path and returns the new object
final int compareTo (final CPath p_path)
final boolean endsWith (final CPath p_path)
check of a path ends with another path
final boolean equals (final Object p_object)
final String get (final int p_index)
returns an part of the path
final String getPath (final String p_separator)
returns the full path as string with an individual separator
final String getPath ()
returns the full path as string
final String getSeparator ()
returns the separator
final CPath getSubPath (final int p_fromIndex)
creates a path of the start index until the end
final CPath getSubPath (final int p_fromIndex, final int p_toIndex)
creates a path of the indices
final String getSuffix ()
returns the last part of the path
final int hashCode ()
final boolean isEmpty ()
check if the path is empty
final Iterator< CPath > iterator ()
final CPath normalize ()
normalizes the path (remove dot and dot-dot elements)
final Stream< String > parallelStream ()
parallel stream over elements
final CPath pushback (final CPath p_path)
adds a path at the end
final CPath pushback (final String p_path)
adds a path at the end
final CPath pushfront (final String p_path)
adds a path at the front
final CPath pushfront (final CPath p_path)
adds a path to the front of the path
final CPath remove (final int p_index)
removes an element
final CPath remove (final int p_start, final int p_end)
removes all elements from start index until end index (exclusive)
final String removeSuffix ()
remove the suffix from the path
final CPath reverse ()
reverse path
final CPath setSeparator (final String p_separator)
sets the separator
final int size ()
returns the number of path elements
final boolean startsWith (final CPath p_path)
check of a path starts with another path
final boolean startsWith (final String p_path)
check of a path starts with another path
final Stream< String > stream ()
stream over elements
final CPath toLower ()
changes all elements to lower-case
final String toString ()
final CPath toUpper ()
changes all elements to uppercase
Static Public Member Functions
static CPath createPath (final String...p_varargs)
creates a path object from different items
static CPath createSplitPath (final String...p_varargs)
creates a path object by splitting a string
static CPath from (final String p_string)
factor method to build path
Static Public Attributes
static final String DEFAULTSEPERATOR = "/"
static final CPath EMPTY = new CPath()
empty path
Private Member Functions
void initialize (final String p_fqn)
splits the string data
Private Attributes
List< String > m_path = new ArrayList<>()
list with path parts *
String m_separator = DEFAULTSEPERATOR
separator of the path elements *
Detailed Description
Definition at line 44 of file CPath.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.common.CPath.CPath (final CPath p_path, final String... p_varargs)
Parameters
p_path path object
p_varargs string arguments
Definition at line 66 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.append(), de.tu_clausthal.in.mec.common.CPath.createPath(), de.tu_clausthal.in.mec.common.CPath.createSplitPath(), de.tu_clausthal.in.mec.common.CPath.getSubPath(), de.tu_clausthal.in.mec.common.CPath.iterator(), de.tu_clausthal.in.mec.common.CPath.pushback(), de.tu_clausthal.in.mec.common.CPath.pushfront(), and de.tu_clausthal.in.mec.common.CPath.startsWith().
de.tu_clausthal.in.mec.common.CPath.CPath (final CPath p_path)
Parameters
p_path path object
Definition at line 77 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_separator.
de.tu_clausthal.in.mec.common.CPath.CPath (final String... p_varargs)
Parameters
p_varargs path component
Definition at line 88 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_separator.
de.tu_clausthal.in.mec.common.CPath.CPath (final Collection< String > p_collection)
Parameters
p_collection string collection
Definition at line 99 of file CPath.java.
Member Function Documentation
final CPath de.tu_clausthal.in.mec.common.CPath.append (final CPath p_path)
Parameters
p_path path
Returns
new path
Definition at line 143 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath().
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.clone(), and de.tu_clausthal.in.mec.object.mas.generic.implementation.CLiteral< T >.clone().
final CPath de.tu_clausthal.in.mec.common.CPath.append (final String p_path)
Parameters
p_path string with path
Returns
new path
Definition at line 167 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath().
final int de.tu_clausthal.in.mec.common.CPath.compareTo (final CPath p_path)
Definition at line 546 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.hashCode().
static CPath de.tu_clausthal.in.mec.common.CPath.createPath (final String... p_varargs) static
Parameters
p_varargs list of strings
Returns
path object
Definition at line 111 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath(), and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static CPath de.tu_clausthal.in.mec.common.CPath.createSplitPath (final String... p_varargs) static
Parameters
p_varargs list of string (first element is the seperator)
Returns
path object
Definition at line 125 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.common.CPath.stream().
Referenced by de.tu_clausthal.in.mec.common.CPath.from().
final boolean de.tu_clausthal.in.mec.common.CPath.endsWith (final CPath p_path)
Parameters
p_path path
Returns
boolean
Definition at line 205 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.equals(), de.tu_clausthal.in.mec.common.CPath.get(), and de.tu_clausthal.in.mec.common.CPath.size().
final boolean de.tu_clausthal.in.mec.common.CPath.equals (final Object p_object)
Definition at line 339 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.getPath().
Referenced by de.tu_clausthal.in.mec.common.CPath.endsWith().
static CPath de.tu_clausthal.in.mec.common.CPath.from (final String p_string) static
Parameters
p_string input string
Returns
path
Definition at line 156 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.createSplitPath(), de.tu_clausthal.in.mec.common.CPath.DEFAULTSEPERATOR, and de.tu_clausthal.in.mec.common.CPath.EMPTY.
final String de.tu_clausthal.in.mec.common.CPath.get (final int p_index)
Parameters
p_index index position (negativ index is element from the end)
Returns
element
Definition at line 223 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.endsWith(), de.tu_clausthal.in.mec.common.CTreeNode< T >.getNode(), and de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.walk().
final String de.tu_clausthal.in.mec.common.CPath.getPath (final String p_separator)
Parameters
p_separator separator
Returns
string path
Definition at line 234 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
final String de.tu_clausthal.in.mec.common.CPath.getPath ()
Returns
string path
Definition at line 244 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path, and de.tu_clausthal.in.mec.common.CPath.m_separator.
Referenced by de.tu_clausthal.in.mec.common.CPath.equals().
final String de.tu_clausthal.in.mec.common.CPath.getSeparator ()
Returns
separator
Definition at line 254 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_separator.
final CPath de.tu_clausthal.in.mec.common.CPath.getSubPath (final int p_fromIndex)
Parameters
p_fromIndex start index
Returns
path
Definition at line 302 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsLiteral(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsMask(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getLiteral(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.getMask(), and de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.walk().
final CPath de.tu_clausthal.in.mec.common.CPath.getSubPath (final int p_fromIndex, final int p_toIndex)
Parameters
p_fromIndex start index
p_toIndex end index (exclusive) / negative values from the end
Returns
path
Definition at line 314 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath(), and de.tu_clausthal.in.mec.common.CPath.m_separator.
final String de.tu_clausthal.in.mec.common.CPath.getSuffix ()
Returns
string
Definition at line 327 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.createPathLiteral(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.CTreeBeliefBase(), and de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.setMessageBeliefbase().
final int de.tu_clausthal.in.mec.common.CPath.hashCode ()
Definition at line 333 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.compareTo().
void de.tu_clausthal.in.mec.common.CPath.initialize (final String p_fqn) private
Parameters
p_fqn full path
Definition at line 557 of file CPath.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.common.CPath.m_path, and de.tu_clausthal.in.mec.common.CPath.m_separator.
final boolean de.tu_clausthal.in.mec.common.CPath.isEmpty ()
Returns
empty flag
Definition at line 360 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.runtime.message.CMessage< T >.CMessage(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsLiteral(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsMask(), de.tu_clausthal.in.mec.common.CTreeNode< T >.getTree(), de.tu_clausthal.in.mec.runtime.message.CMessageSystem.pushMessage(), de.tu_clausthal.in.mec.common.CPath.removeSuffix(), de.tu_clausthal.in.mec.common.Test_CPath.testEmpty(), de.tu_clausthal.in.mec.runtime.message.CMessageSystem.unregister(), and de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.walk().
final Iterator<CPath> de.tu_clausthal.in.mec.common.CPath.iterator ()
Definition at line 366 of file CPath.java.
References de.tu_clausthal.in.mec.common.CCommon.convertCollectionToArray(), de.tu_clausthal.in.mec.common.CPath.CPath(), and de.tu_clausthal.in.mec.common.CPath.m_path.
final CPath de.tu_clausthal.in.mec.common.CPath.normalize ()
Returns
self reference
Definition at line 529 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
final Stream<String> de.tu_clausthal.in.mec.common.CPath.parallelStream ()
Returns
parallel stream
Definition at line 518 of file CPath.java.
final CPath de.tu_clausthal.in.mec.common.CPath.pushback (final CPath p_path)
Parameters
p_path path
Returns
return the changed object
Definition at line 392 of file CPath.java.
final CPath de.tu_clausthal.in.mec.common.CPath.pushback (final String p_path)
Parameters
p_path string path
Returns
return the changed object
Definition at line 404 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath().
final CPath de.tu_clausthal.in.mec.common.CPath.pushfront (final String p_path)
Parameters
p_path string path
Returns
return the changed object
Definition at line 416 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath().
Referenced by de.tu_clausthal.in.mec.common.CTreeNode< T >.getFQN().
final CPath de.tu_clausthal.in.mec.common.CPath.pushfront (final CPath p_path)
Parameters
p_path path
Returns
return the changed object
Definition at line 428 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
final CPath de.tu_clausthal.in.mec.common.CPath.remove (final int p_index)
Parameters
p_index index position
Returns
return the changed object
Definition at line 180 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.splitLiteralPath().
final CPath de.tu_clausthal.in.mec.common.CPath.remove (final int p_start, final int p_end)
Parameters
p_start start index
p_end end index (exclusive)
Returns
return the changed object
Definition at line 193 of file CPath.java.
final String de.tu_clausthal.in.mec.common.CPath.removeSuffix ()
Returns
last item of the path
Definition at line 441 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.isEmpty(), and de.tu_clausthal.in.mec.common.CPath.m_path.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CAgent< T >.CJasonArchitecture.broadcast().
final CPath de.tu_clausthal.in.mec.common.CPath.reverse ()
Returns
return the changed object
Definition at line 457 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
final CPath de.tu_clausthal.in.mec.common.CPath.setSeparator (final String p_separator)
Parameters
p_separator separator
Returns
path object
Definition at line 265 of file CPath.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.common.CPath.m_separator.
final int de.tu_clausthal.in.mec.common.CPath.size ()
Returns
size
Definition at line 468 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CAgent< T >.CJasonArchitecture.broadcast(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsLiteral(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.containsMask(), de.tu_clausthal.in.mec.common.CPath.endsWith(), de.tu_clausthal.in.mec.common.CTreeNode< T >.getNode(), de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.splitLiteralPath(), de.tu_clausthal.in.mec.common.CPath.startsWith(), and de.tu_clausthal.in.mec.common.Test_CPath.testEmpty().
final boolean de.tu_clausthal.in.mec.common.CPath.startsWith (final CPath p_path)
Parameters
p_path path
Returns
boolean
Definition at line 479 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.size().
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CTreeBeliefBase.splitLiteralPath().
final boolean de.tu_clausthal.in.mec.common.CPath.startsWith (final String p_path)
Parameters
p_path path
Returns
boolean
Definition at line 497 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.CPath().
final Stream<String> de.tu_clausthal.in.mec.common.CPath.stream ()
Returns
sequential stream
Definition at line 508 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.createSplitPath().
final CPath de.tu_clausthal.in.mec.common.CPath.toLower ()
Returns
object
Definition at line 279 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
final String de.tu_clausthal.in.mec.common.CPath.toString ()
Definition at line 350 of file CPath.java.
final CPath de.tu_clausthal.in.mec.common.CPath.toUpper ()
Returns
object
Definition at line 290 of file CPath.java.
References de.tu_clausthal.in.mec.common.CPath.m_path.
Member Data Documentation
final String de.tu_clausthal.in.mec.common.CPath.DEFAULTSEPERATOR = "/" static
Definition at line 46 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.from().
final CPath de.tu_clausthal.in.mec.common.CPath.EMPTY = new CPath() static
Definition at line 50 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.from().
List<String> de.tu_clausthal.in.mec.common.CPath.m_path = new ArrayList<>() private
Definition at line 54 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.getPath(), de.tu_clausthal.in.mec.common.CPath.getSuffix(), de.tu_clausthal.in.mec.common.CPath.initialize(), de.tu_clausthal.in.mec.common.CPath.iterator(), de.tu_clausthal.in.mec.common.CPath.normalize(), de.tu_clausthal.in.mec.common.CPath.pushfront(), de.tu_clausthal.in.mec.common.CPath.removeSuffix(), de.tu_clausthal.in.mec.common.CPath.reverse(), de.tu_clausthal.in.mec.common.CPath.toLower(), and de.tu_clausthal.in.mec.common.CPath.toUpper().
String de.tu_clausthal.in.mec.common.CPath.m_separator = DEFAULTSEPERATOR private
Definition at line 58 of file CPath.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.CPath(), de.tu_clausthal.in.mec.common.CPath.getPath(), de.tu_clausthal.in.mec.common.CPath.getSeparator(), de.tu_clausthal.in.mec.common.CPath.getSubPath(), de.tu_clausthal.in.mec.common.CPath.initialize(), and de.tu_clausthal.in.mec.common.CPath.setSeparator().