MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric Enum Reference
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric Enum Reference
enum with metric values
Public Member Functions
IMetric<?, CPath > get (final Collection< CPath > p_paths)
returns a metric instance
String toString ()
Static Public Member Functions
static EMetric isa (final IMetric<?, CPath > p_metric)
returns the enum type of a metric object
Public Attributes
Discrete =(CCommon.getResourceString(EMetric.class, "discrete"))
discrete metric
SymmetricDifference =(CCommon.getResourceString(EMetric.class, "symmetricdifference"))
symmetric difference metric
WeightedDifference =(CCommon.getResourceString(EMetric.class, "weighteddifference"))
weighted difference metric
Private Member Functions
EMetric (final String p_text)
ctor
Private Attributes
final String m_text
language based name of the metric
Detailed Description
Definition at line 144 of file CInconsistencyEnvironment.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.EMetric (final String p_text) private
Parameters
p_text language based metric name
Definition at line 169 of file CInconsistencyEnvironment.java.
Member Function Documentation
IMetric<?, CPath> de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.get (final Collection< CPath > p_paths)
Parameters
p_paths collection of path
Returns
metric
Definition at line 200 of file CInconsistencyEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static EMetric de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.isa (final IMetric<?, CPath > p_metric) static
Parameters
p_metric metric
Returns
enum type
Definition at line 180 of file CInconsistencyEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Referenced by de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.web_static_getMetric().
String de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.toString ()
Definition at line 219 of file CInconsistencyEnvironment.java.
Member Data Documentation
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.Discrete =(CCommon.getResourceString(EMetric.class, "discrete"))
Definition at line 149 of file CInconsistencyEnvironment.java.
final String de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.m_text private
Definition at line 162 of file CInconsistencyEnvironment.java.
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.SymmetricDifference =(CCommon.getResourceString(EMetric.class, "symmetricdifference"))
Definition at line 153 of file CInconsistencyEnvironment.java.
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.WeightedDifference =(CCommon.getResourceString(EMetric.class, "weighteddifference"))
Definition at line 157 of file CInconsistencyEnvironment.java.