MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment Class Reference
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment Class Reference
environment for inconsistency layer and metric
Classes
enum EMetric
enum with metric values
Public Member Functions
CInconsistencyEnvironment (final String p_layername)
ctor
Private Member Functions
final Map< String, Object > web_static_getMetric ()
UI method - get the current metric.
final Map< String, String > web_static_label ()
returns all static label information for main menu
final void web_static_setMetric (final Map< String, Object > p_data)
UI method - sets the metric on the current layer.
final String web_uribase ()
UI method - returns URI base.
Private Attributes
final Map< String, String > m_label
map for default labels
final String m_layername
layer name
Detailed Description
Definition at line 47 of file CInconsistencyEnvironment.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.CInconsistencyEnvironment (final String p_layername)
Parameters
p_layername layer name within the simulation world
Definition at line 66 of file CInconsistencyEnvironment.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Member Function Documentation
final Map<String, Object> de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.web_static_getMetric () private
Returns
metric value
Definition at line 84 of file CInconsistencyEnvironment.java.
References de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.isa().
final Map<String, String> de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.web_static_label () private
Returns
map with static labels
Definition at line 106 of file CInconsistencyEnvironment.java.
final void de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.web_static_setMetric (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 116 of file CInconsistencyEnvironment.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
final String de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.web_uribase () private
Returns
base name
Definition at line 136 of file CInconsistencyEnvironment.java.
Member Data Documentation
final Map<String, String> de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.m_label private
Initial value:
= new HashMap<String, String>()
    {{
        put( "title_dialog", CCommon.getResourceString( CInconsistencyEnvironment.class, "dialogtitle" ) );
    }}
Definition at line 52 of file CInconsistencyEnvironment.java.
final String de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.m_layername private
Definition at line 59 of file CInconsistencyEnvironment.java.