MecSim - Traffic Simulation: de.tu_clausthal.in.mec.runtime.benchmark.CTimer Class Reference
de.tu_clausthal.in.mec.runtime.benchmark.CTimer Class Reference
timer class for benchmarking
Public Member Functions
CTimer start ()
start timer
CTimer stop (final String p_label)
stop time
Private Member Functions
long getTime ()
returns the current time
Private Attributes
long m_start = -1
start time
Detailed Description
Definition at line 33 of file CTimer.java.
Member Function Documentation
long de.tu_clausthal.in.mec.runtime.benchmark.CTimer.getTime () private
Returns
time value
Definition at line 76 of file CTimer.java.
Referenced by de.tu_clausthal.in.mec.runtime.benchmark.CTimer.stop().
CTimer de.tu_clausthal.in.mec.runtime.benchmark.CTimer.start ()
Returns
timer object
Definition at line 46 of file CTimer.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), and de.tu_clausthal.in.mec.runtime.benchmark.CTimer.m_start.
CTimer de.tu_clausthal.in.mec.runtime.benchmark.CTimer.stop (final String p_label)
Parameters
p_label label of the timer value
Returns
timer object
Definition at line 61 of file CTimer.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.runtime.benchmark.CTimer.getTime(), and de.tu_clausthal.in.mec.runtime.benchmark.CTimer.m_start.
Member Data Documentation
long de.tu_clausthal.in.mec.runtime.benchmark.CTimer.m_start = -1 private
Definition at line 38 of file CTimer.java.
Referenced by de.tu_clausthal.in.mec.runtime.benchmark.CTimer.start(), and de.tu_clausthal.in.mec.runtime.benchmark.CTimer.stop().