MecSim - Traffic Simulation: de.tu_clausthal.in.mec.common.CReflection.CClassIndex Class Reference
de.tu_clausthal.in.mec.common.CReflection.CClassIndex Class Reference
class to represent a class index
Classes
enum EFilter
enum to define the filter *
Public Member Functions
CClassIndex (final EFilter p_filter)
ctor
void filter (final String...p_startwith)
adds an element to the filter list
Class<?> get (final String p_class)
returns the first entry of the name
Collection< Class<?> > getAll (final String p_class)
returns the collection of all classes
void scan ()
scans the defined packages
void scanDirectory (final File p_path)
scans a directory for classes
void scanJar (final File p_jar)
scans a Jar for classes
Private Member Functions
String getClassnameFromFile (String p_file)
replaces a file name with path to a class name
boolean startsIgnoreWith (final String p_classname)
checks a string class name with the ignore list
Private Attributes
final MultiValueMap< String,
Class<?> > m_classname = new MultiValueMap<>()
map with classname and class object *
final Set< String > m_filter = new HashSet<>()
parts (start-with) for ignores *
final EFilter m_filterdefinition
filter type
Static Private Attributes
static final String c_classextension = "class"
extension of the class files (without dot) *
Detailed Description
Definition at line 295 of file CReflection.java.
Class Documentation
enum de::tu_clausthal::in::mec::common::CReflection::CClassIndex::EFilter
Definition at line 491 of file CReflection.java.
Class Members
BlackList blacklisting items *
WhiteList whitelisting items *
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.common.CReflection.CClassIndex.CClassIndex (final EFilter p_filter)
Parameters
p_filter filter type
Definition at line 319 of file CReflection.java.
Member Function Documentation
void de.tu_clausthal.in.mec.common.CReflection.CClassIndex.filter (final String... p_startwith)
Parameters
p_startwith class part name
Definition at line 329 of file CReflection.java.
Class<?> de.tu_clausthal.in.mec.common.CReflection.CClassIndex.get (final String p_class)
Parameters
p_class simple class name
Returns
first match
Definition at line 340 of file CReflection.java.
Collection<Class<?> > de.tu_clausthal.in.mec.common.CReflection.CClassIndex.getAll (final String p_class)
Parameters
p_class simple class name
Returns
collection of classes objects
Definition at line 354 of file CReflection.java.
String de.tu_clausthal.in.mec.common.CReflection.CClassIndex.getClassnameFromFile (String p_file) private
Parameters
p_file filename
Returns
class name
Definition at line 468 of file CReflection.java.
void de.tu_clausthal.in.mec.common.CReflection.CClassIndex.scan ()
Definition at line 362 of file CReflection.java.
References de.tu_clausthal.in.mec.common.CReflection.CClassIndex.EFilter.BlackList, and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
void de.tu_clausthal.in.mec.common.CReflection.CClassIndex.scanDirectory (final File p_path)
Parameters
p_path path
Definition at line 392 of file CReflection.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
void de.tu_clausthal.in.mec.common.CReflection.CClassIndex.scanJar (final File p_jar)
Parameters
p_jar Jar file
Definition at line 423 of file CReflection.java.
References de.tu_clausthal.in.mec.common.CReflection.CClassIndex.EFilter.BlackList, and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
boolean de.tu_clausthal.in.mec.common.CReflection.CClassIndex.startsIgnoreWith (final String p_classname) private
Parameters
p_classname class string name
Returns
true on existsing of the ignore list
Definition at line 479 of file CReflection.java.
Member Data Documentation
final String de.tu_clausthal.in.mec.common.CReflection.CClassIndex.c_classextension = "class" static private
Definition at line 300 of file CReflection.java.
final MultiValueMap<String, Class<?> > de.tu_clausthal.in.mec.common.CReflection.CClassIndex.m_classname = new MultiValueMap<>() private
Definition at line 304 of file CReflection.java.
final Set<String> de.tu_clausthal.in.mec.common.CReflection.CClassIndex.m_filter = new HashSet<>() private
Definition at line 308 of file CReflection.java.
final EFilter de.tu_clausthal.in.mec.common.CReflection.CClassIndex.m_filterdefinition private
Definition at line 312 of file CReflection.java.