MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.mas.jason.CCommon Class Reference
de.tu_clausthal.in.mec.object.mas.jason.CCommon Class Reference
common method for Jason
Static Public Member Functions
static String clearString (final String p_input)
Jason creates quoted string, so we need to clean the string to create corrected Java strings.
static CStringAtom convertGeneric (final Atom p_atom)
converts an atom into a string atom
static CStringAtom convertGeneric (final StringTerm p_term)
converts a StringTerm into a string atom
static Set< ILiteral< Literal > > convertGeneric (final List< Literal > p_literals)
converts a jason specific set of literals to a generic one
static CNumberAtom convertGeneric (final NumberTerm p_number)
converts a NumberTerm into a Double Atom
static ITerm convertGeneric (final Term p_term)
converts a term into a generic ITerm
static Object getJavaValue (final Term p_term, final Class<?> p_type) throws NoValueException
converts Jason Term to Java types to complex types e.g.
static Object getJavaValue (final Term p_term) throws NoValueException
Jason does not support Java-type binding, so an explicit converting of Jason types to the corresponding Java type is needed.
static Literal getLiteral (final String p_name, final Object...p_data)
creates a Jason literal with optional data
static Literal getLiteral (final String p_atom)
returns an atom
Static Public Attributes
static final Literal DEFAULTANNOTATION = de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteral("source", "self")
default source annotation "source(self)"
Private Member Functions
CCommon ()
private ctor - avoid instantiation
Static Private Member Functions
static Number getJavaValue (final Double p_value, final Class<?> p_class)
converts a Double into a number object with correct type structure
static String getLiteralName (final String p_name)
checks a literal name and convert it to the correct syntax
static Term getTerm (final Object p_data)
convert data type into Jason term
Detailed Description
Definition at line 60 of file object/mas/jason/CCommon.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.object.mas.jason.CCommon.CCommon () private
Definition at line 71 of file object/mas/jason/CCommon.java.
Member Function Documentation
static String de.tu_clausthal.in.mec.object.mas.jason.CCommon.clearString (final String p_input) static
Parameters
p_input input Jason string
Returns
cleanup Java String
Definition at line 81 of file object/mas/jason/CCommon.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric(), and de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue().
static CStringAtom de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric (final Atom p_atom) static
Parameters
p_atom atom to convert
Returns
string atom
Definition at line 92 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.clearString().
Referenced by de.tu_clausthal.in.mec.object.mas.jason.belief.CLiteral.addAdditionals(), and de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric().
static CStringAtom de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric (final StringTerm p_term) static
Parameters
p_term string term to convert
Returns
string atom
Definition at line 103 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.clearString().
static Set<ILiteral<Literal> > de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric (final List< Literal > p_literals) static
Parameters
p_literals set of jason-specific literals
Returns
converted Set of generic literals
Definition at line 114 of file object/mas/jason/CCommon.java.
static CNumberAtom de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric (final NumberTerm p_number) static
Parameters
p_number NumberTerm
Returns
Double Atom
Definition at line 130 of file object/mas/jason/CCommon.java.
static ITerm de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric (final Term p_term) static
Parameters
p_term original term
Returns
converted generic term
Definition at line 151 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.convertGeneric().
static Object de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue (final Term p_term, final Class<?> p_type) throws NoValueException static
List -> Geoposition
Parameters
p_term Jason term
p_type type list with the target type
Returns
Java value
Definition at line 196 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue().
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue().
static Object de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue (final Term p_term) throws NoValueException static
Parameters
p_term Jason term
Returns
Java type
Exceptions
NoValueException on empty value
Definition at line 231 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.clearString(), and de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue().
static Number de.tu_clausthal.in.mec.object.mas.jason.CCommon.getJavaValue (final Double p_value, final Class<?> p_class) static private
Parameters
p_value double value
p_class class that is the target type
Returns
converted boxed-type
Definition at line 288 of file object/mas/jason/CCommon.java.
static Literal de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteral (final String p_name, final Object... p_data) static
Parameters
p_name name of the literal
p_data data of the literal
Returns
literal object
Definition at line 261 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.getTerm().
static Literal de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteral (final String p_atom) static
Parameters
p_atom name of the atom
Returns
literal object
Definition at line 276 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteralName().
static String de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteralName (final String p_name) static private
Parameters
p_name name of the literal
Returns
converted literal name
Note
note the precendence of the data types
Definition at line 314 of file object/mas/jason/CCommon.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteral().
static Term de.tu_clausthal.in.mec.object.mas.jason.CCommon.getTerm (final Object p_data) static private
Parameters
p_data Jason Term value
Returns
Jason term
Definition at line 338 of file object/mas/jason/CCommon.java.
References de.tu_clausthal.in.mec.object.mas.jason.CCommon.getTerm().
Referenced by de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteral(), and de.tu_clausthal.in.mec.object.mas.jason.CCommon.getTerm().
Member Data Documentation
final Literal de.tu_clausthal.in.mec.object.mas.jason.CCommon.DEFAULTANNOTATION = de.tu_clausthal.in.mec.object.mas.jason.CCommon.getLiteral("source", "self") static
Definition at line 65 of file object/mas/jason/CCommon.java.