MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.IInspectorDefault Class Reference
de.tu_clausthal.in.mec.ui.IInspectorDefault Class Reference abstract
global default implementation to get information about a simulation object
Public Member Functions
Map< String, Object > inspect ()
returns a map to inspect current data of the car
Public Member Functions inherited from de.tu_clausthal.in.mec.ui.IUIListener
IUIListener ()
ctor to registerObject component on the viewer
final void mouseClicked (final MouseEvent p_event)
final void mouseEntered (final MouseEvent p_event)
final void mouseExited (final MouseEvent p_event)
final void mousePressed (final MouseEvent p_event)
final void mouseReleased (final MouseEvent p_event)
void onClick (final MouseEvent p_event, final JXMapViewer p_viewer)
click method which is called by a click on the object
void release ()
release of the event handler
Private Attributes
final Map< String, Object > m_inspect = new HashMap<>()
inspect variable *
Additional Inherited Members
Protected Member Functions inherited from de.tu_clausthal.in.mec.ui.IUIListener
final double iconscale (final JXMapViewer p_viewer)
returns the normalized zoom level
final int iconsize (final JXMapViewer p_viewer)
returns the icon size
Static Protected Attributes inherited from de.tu_clausthal.in.mec.ui.IUIListener
static final int c_maxzoom = 9
maximum zoom value *
static final int c_miniconsize = 3
minimum icon size *
Detailed Description
Definition at line 38 of file IInspectorDefault.java.
Member Function Documentation
Map<String, Object> de.tu_clausthal.in.mec.ui.IInspectorDefault.inspect ()
Returns
map with name and value
Implements de.tu_clausthal.in.mec.ui.IInspector.
Definition at line 48 of file IInspectorDefault.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.ui.IInspectorDefault.m_inspect, and de.tu_clausthal.in.mec.common.CCommon.removePackageName().
Member Data Documentation
final Map<String, Object> de.tu_clausthal.in.mec.ui.IInspectorDefault.m_inspect = new HashMap<>() private
Definition at line 44 of file IInspectorDefault.java.
Referenced by de.tu_clausthal.in.mec.ui.IInspectorDefault.inspect().