MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.car.CUnitConvert Class Reference
de.tu_clausthal.in.mec.object.car.CUnitConvert Class Reference
converting driving units
Public Member Functions
final double getAccelerationToSpeed (final double p_acceleration)
returns the speed change in one timestep
final int getCellSize ()
returns the cell size
final double getCellToKiloMeter (final int p_cells)
returns cell number to distance in kilometer
final double getCellToMeter (final int p_cells)
returns cell number to distance in meter
final int getSpeedOfDistance (final double p_distance)
returns the speed for traveling the given distance in one timestep
final int getSpeedToCell (final int p_speed)
returns the speed in cell positions at one timestep
final double getSpeedToDistance (final int p_speed)
returns the distance in meter which can moved in one timestep
final int getTime ()
returns the timestep in seconds
final int getTime (final int p_step)
returns the time in seconds for n steps
final double getTimeInMinutes (final int p_step)
returns the time in minutes for n steps
Private Attributes
final int m_cellsize = CConfiguration.getInstance().get().<Integer>get("simulation/traffic/cellsampling")
cell size in meter
final int m_celltimestep = (int) Math.floor(m_distancetimestep / m_cellsize)
number of cells which can be moved at one timestep
final double m_distancetimestep = c_kmhInMs * m_timestep
meter which can be moved at one timestep
final int m_timestep = CConfiguration.getInstance().get().<Integer>get("simulation/traffic/timesampling")
timestep in seconds
Static Private Attributes
static final double c_kmhInMs = 1000.0 / 3600.0
constant value to scale km/h in m/s
static final double c_MsInKmh = 1 / c_kmhInMs
constant value to scale m/s in km/h
Detailed Description
Note
[speed in meter/sec] * [timesampling in second] = [moved length in m] / ]cellsampling in meter] = moved cells (km/h = 1000 / 3600 m/s)
Definition at line 35 of file CUnitConvert.java.
Member Function Documentation
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.getAccelerationToSpeed (final double p_acceleration)
Parameters
p_acceleration acceleration or deceleration in m/sec^2
Returns
speed change in km/h
Definition at line 70 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.c_MsInKmh, and de.tu_clausthal.in.mec.object.car.CUnitConvert.m_timestep.
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.getCellSize ()
Returns
cell size in meter
Definition at line 80 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.m_cellsize.
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.getCellToKiloMeter (final int p_cells)
Parameters
p_cells cell number
Returns
kilometer value
Definition at line 102 of file CUnitConvert.java.
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.getCellToMeter (final int p_cells)
Parameters
p_cells cell number
Returns
meter value
Definition at line 91 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.m_cellsize.
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedOfDistance (final double p_distance)
Parameters
p_distance distance in meter
Returns
speed in km/h
Definition at line 113 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.c_MsInKmh, and de.tu_clausthal.in.mec.object.car.CUnitConvert.m_timestep.
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedToCell (final int p_speed)
Parameters
p_speed speed in km/h
Returns
amount of cells / timestep
Definition at line 124 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.m_celltimestep.
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedToDistance (final int p_speed)
Parameters
p_speed speed in km/h
Returns
meter
Definition at line 136 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.c_kmhInMs, and de.tu_clausthal.in.mec.object.car.CUnitConvert.m_timestep.
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.getTime ()
Returns
timestep
Definition at line 146 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.m_timestep.
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.getTime (final int p_step)
Parameters
p_step step number
Returns
time in seconds
Definition at line 157 of file CUnitConvert.java.
References de.tu_clausthal.in.mec.object.car.CUnitConvert.m_timestep.
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.getTimeInMinutes (final int p_step)
Parameters
p_step step number
Returns
time in minutes
Definition at line 168 of file CUnitConvert.java.
Member Data Documentation
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.c_kmhInMs = 1000.0 / 3600.0 static private
Definition at line 41 of file CUnitConvert.java.
Referenced by de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedToDistance().
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.c_MsInKmh = 1 / c_kmhInMs static private
Definition at line 45 of file CUnitConvert.java.
Referenced by de.tu_clausthal.in.mec.object.car.CUnitConvert.getAccelerationToSpeed(), and de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedOfDistance().
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.m_cellsize = CConfiguration.getInstance().get().<Integer>get("simulation/traffic/cellsampling") private
Definition at line 49 of file CUnitConvert.java.
Referenced by de.tu_clausthal.in.mec.object.car.CUnitConvert.getCellSize(), and de.tu_clausthal.in.mec.object.car.CUnitConvert.getCellToMeter().
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.m_celltimestep = (int) Math.floor(m_distancetimestep / m_cellsize) private
Definition at line 61 of file CUnitConvert.java.
Referenced by de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedToCell().
final double de.tu_clausthal.in.mec.object.car.CUnitConvert.m_distancetimestep = c_kmhInMs * m_timestep private
Definition at line 57 of file CUnitConvert.java.
final int de.tu_clausthal.in.mec.object.car.CUnitConvert.m_timestep = CConfiguration.getInstance().get().<Integer>get("simulation/traffic/timesampling") private
Definition at line 53 of file CUnitConvert.java.
Referenced by de.tu_clausthal.in.mec.object.car.CUnitConvert.getAccelerationToSpeed(), de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedOfDistance(), de.tu_clausthal.in.mec.object.car.CUnitConvert.getSpeedToDistance(), and de.tu_clausthal.in.mec.object.car.CUnitConvert.getTime().