MecSim - Traffic Simulation: de.tu_clausthal.in.mec.ui.CTrafficEnvironment Class Reference
de.tu_clausthal.in.mec.ui.CTrafficEnvironment Class Reference
encapsulating class for traffic UI components
Private Member Functions
final Map< String, Object > web_static_listdrivemodel ()
UI method - lists all driving model.
final void web_static_setdrivemodel (final Map< String, Object > p_data)
UI method - sets the driving model.
Private Attributes
final Map< String, Object > m_drivingmodel = new HashMap<>()
map with drivingmodels
Detailed Description
Definition at line 38 of file CTrafficEnvironment.java.
Member Function Documentation
final Map<String, Object> de.tu_clausthal.in.mec.ui.CTrafficEnvironment.web_static_listdrivemodel () private
Returns
list wir driving models
Definition at line 51 of file CTrafficEnvironment.java.
References de.tu_clausthal.in.mec.ui.CTrafficEnvironment.m_drivingmodel.
final void de.tu_clausthal.in.mec.ui.CTrafficEnvironment.web_static_setdrivemodel (final Map< String, Object > p_data) private
Parameters
p_data input data
Definition at line 66 of file CTrafficEnvironment.java.
References de.tu_clausthal.in.mec.runtime.CSimulation.getInstance(), and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Member Data Documentation
final Map<String, Object> de.tu_clausthal.in.mec.ui.CTrafficEnvironment.m_drivingmodel = new HashMap<>() private
Definition at line 43 of file CTrafficEnvironment.java.
Referenced by de.tu_clausthal.in.mec.ui.CTrafficEnvironment.web_static_listdrivemodel().