MecSim - Traffic Simulation: de.tu_clausthal.in.mec.object.car.CCarLayer Class Reference
de.tu_clausthal.in.mec.object.car.CCarLayer Class Reference
defines the layer for cars
Inherits IMultiLayer< ICar >, and IReturnSteppableTarget< ICar >.
Classes
enum EDrivingModel
enum for representating a driving model
Public Member Functions
final void afterStepObject (final int p_currentstep, final ICar p_object)
final void beforeStepObject (final int p_currentstep, final ICar p_object)
final int getCalculationIndex ()
final EDrivingModel getDrivingModel ()
returns the name of the driving model
final CGraphHopper getGraph ()
returns the graph of the layer
CUnitConvert getUnitConvert ()
returns the unit converting object
final void push (final Collection< ICar > p_data)
final void release ()
final void setDriveModel (final EDrivingModel p_model)
sets the drive model
final void step (final int p_currentstep, final ILayer p_layer)
final String toString ()
Private Attributes
final transient List< ICar > m_data = new LinkedList<>()
data structure
EDrivingModel m_drivemodel = EDrivingModel.AgentNagelSchreckenberg
driving model
transient CGraphHopper m_graph = new CGraphHopper(m_unit.getCellSize())
graph
final transient CUnitConvert m_unit = new CUnitConvert()
unit converting for traffic structure
Detailed Description
Definition at line 44 of file CCarLayer.java.
Member Function Documentation
final void de.tu_clausthal.in.mec.object.car.CCarLayer.afterStepObject (final int p_currentstep, final ICar p_object)
Definition at line 64 of file CCarLayer.java.
References de.tu_clausthal.in.mec.object.car.ICar.hasEndReached().
final void de.tu_clausthal.in.mec.object.car.CCarLayer.beforeStepObject (final int p_currentstep, final ICar p_object)
Definition at line 78 of file CCarLayer.java.
final int de.tu_clausthal.in.mec.object.car.CCarLayer.getCalculationIndex ()
Definition at line 84 of file CCarLayer.java.
final EDrivingModel de.tu_clausthal.in.mec.object.car.CCarLayer.getDrivingModel ()
Returns
name
Definition at line 107 of file CCarLayer.java.
References de.tu_clausthal.in.mec.object.car.CCarLayer.m_drivemodel.
final CGraphHopper de.tu_clausthal.in.mec.object.car.CCarLayer.getGraph ()
Returns
graph object
Definition at line 117 of file CCarLayer.java.
References de.tu_clausthal.in.mec.object.car.CCarLayer.m_graph.
CUnitConvert de.tu_clausthal.in.mec.object.car.CCarLayer.getUnitConvert ()
Returns
unit converter
Definition at line 128 of file CCarLayer.java.
References de.tu_clausthal.in.mec.object.car.CCarLayer.m_unit.
Referenced by de.tu_clausthal.in.mec.object.car.drivemodel.CNagelSchreckenberg.checkLinger(), and de.tu_clausthal.in.mec.object.car.CCarJasonAgent.CTrafficStorage.updating().
final void de.tu_clausthal.in.mec.object.car.CCarLayer.push (final Collection< ICar > p_data)
Definition at line 135 of file CCarLayer.java.
final void de.tu_clausthal.in.mec.object.car.CCarLayer.release ()
Definition at line 90 of file CCarLayer.java.
final void de.tu_clausthal.in.mec.object.car.CCarLayer.setDriveModel (final EDrivingModel p_model)
Parameters
p_model model
Definition at line 145 of file CCarLayer.java.
References de.tu_clausthal.in.mec.object.car.CCarLayer.m_drivemodel.
final void de.tu_clausthal.in.mec.object.car.CCarLayer.step (final int p_currentstep, final ILayer p_layer)
Definition at line 97 of file CCarLayer.java.
final String de.tu_clausthal.in.mec.object.car.CCarLayer.toString ()
Definition at line 151 of file CCarLayer.java.
Member Data Documentation
final transient List<ICar> de.tu_clausthal.in.mec.object.car.CCarLayer.m_data = new LinkedList<>() private
Definition at line 49 of file CCarLayer.java.
EDrivingModel de.tu_clausthal.in.mec.object.car.CCarLayer.m_drivemodel = EDrivingModel.AgentNagelSchreckenberg private
Definition at line 53 of file CCarLayer.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarLayer.getDrivingModel(), and de.tu_clausthal.in.mec.object.car.CCarLayer.setDriveModel().
transient CGraphHopper de.tu_clausthal.in.mec.object.car.CCarLayer.m_graph = new CGraphHopper(m_unit.getCellSize()) private
Definition at line 61 of file CCarLayer.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarLayer.getGraph().
final transient CUnitConvert de.tu_clausthal.in.mec.object.car.CCarLayer.m_unit = new CUnitConvert() private
Definition at line 57 of file CCarLayer.java.
Referenced by de.tu_clausthal.in.mec.object.car.CCarLayer.getUnitConvert().