MecSim - Traffic Simulation: de.tu_clausthal.in.mec.common.CCommon Class Reference
de.tu_clausthal.in.mec.common.CCommon Class Reference
class for any helper calls
Static Public Member Functions
static File addFileExtension (final File p_file, final String p_suffix)
adds a file extension if necessary
static URL concatURL (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException
concats an URL with a path
static< T > T[] convertCollectionToArray (final Class< T[]> p_class, final Collection< T > p_collection)
converts any collection type into a typed array
static Object convertValue (final String p_value, final Class[] p_types, final TypeParser p_parser)
converts a value into class
static< T > T deepCopy (final T p_object) throws IOException, ClassNotFoundException
create a deep-copy of a serializable object
static Map< String, Object > fromJson (final String p_data)
converts a Json string data into a raw map
static< T > T fromJson (final String p_data, final Class< T > p_class)
converts a Json string into any class object
static< T > T getCheckedValue (final T p_input, final T p_default, final Collection< T > p_allowedvalues)
checks a value and returns the checkd value or the default value
static String getHash (final String p_string, final String p_hash)
returns the hash of a string
static String getHash (final File p_file, final String p_hash)
static Map< String, Object > getMap (final Object...p_objects)
creates a map from parameters
static String getNonEmptyValue (final String p_input, final String p_default)
returns a default value of an empty string
static String getResourceString (final Class<?> p_class, final String p_label, final Object...p_parameter)
returns a default string of the resource file
static String getResourceString (final String p_language, final Class<?> p_class, final String p_label, final Object...p_parameter)
returns a string of the resource file
static String getResourceString (final Object p_object, final String p_label, final Object...p_parameter)
returns a default string of the resource file
static String getResourceString (final String p_language, final Object p_object, final String p_label, final Object...p_parameter)
returns a string of the resource file
static String getResourceStringLabel (final Class<?> p_class, final String p_label)
returns the label of a class and string to get access to the resource
static URL getResourceURL ()
returns root path of the resource
static URL getResourceURL (final String p_file)
returns a file from a resource e.g.
static URL getResourceURL (final File p_file)
returns a file from a resource e.g.
static String removePackageName (final String p_package)
remove from a string the system package name
static List< String > startupchecks ()
checkes the VM structures on startup
static String toJson (final Object p_data)
convert any object data into Json
Private Member Functions
CCommon ()
private ctor - avoid instantiation
Static Private Member Functions
static String getBytes2Hex (final byte[] p_bytes)
returns a string with hexadecimal bytes
Static Private Attributes
static final long c_gigabyte = 1024 * 1024 * 1024
gigabyte multiplier
static final float c_neededmemory = 3f
needed memory in gigabyte
Detailed Description
Definition at line 60 of file common/CCommon.java.
Constructor & Destructor Documentation
de.tu_clausthal.in.mec.common.CCommon.CCommon () private
Definition at line 75 of file common/CCommon.java.
Member Function Documentation
static File de.tu_clausthal.in.mec.common.CCommon.addFileExtension (final File p_file, final String p_suffix) static
Parameters
p_file file object
p_suffix suffix
Returns
file with extension
Definition at line 118 of file common/CCommon.java.
static URL de.tu_clausthal.in.mec.common.CCommon.concatURL (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException static
Parameters
p_base base URL
p_string additional path
Returns
new URL
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 133 of file common/CCommon.java.
static <T> T [] de.tu_clausthal.in.mec.common.CCommon.convertCollectionToArray (final Class< T[]> p_class, final Collection< T > p_collection) static
Parameters
p_class class array
p_collection collection
Returns
typed array
Template Parameters
T collection / array type
Definition at line 147 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.common.CPath.iterator().
static Object de.tu_clausthal.in.mec.common.CCommon.convertValue (final String p_value, final Class[] p_types, final TypeParser p_parser) static
Parameters
p_value string input class
p_types type classes
p_parser type parser
Returns
converted type
Definition at line 162 of file common/CCommon.java.
static <T> T de.tu_clausthal.in.mec.common.CCommon.deepCopy (final T p_object) throws IOException, ClassNotFoundException static
Parameters
p_object input object
Returns
deep-copy of object
Exceptions
IOException throws on serializing error
ClassNotFoundException throws on derserialzing error
Template Parameters
T object type
Definition at line 186 of file common/CCommon.java.
static Map<String, Object> de.tu_clausthal.in.mec.common.CCommon.fromJson (final String p_data) static
Returns
raw map data
Definition at line 203 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.CConfiguration.read().
static <T> T de.tu_clausthal.in.mec.common.CCommon.fromJson (final String p_data, final Class< T > p_class) static
Parameters
p_data string data
p_class class type
Returns
deserialized type
Template Parameters
T type parameter
Definition at line 217 of file common/CCommon.java.
static String de.tu_clausthal.in.mec.common.CCommon.getBytes2Hex (final byte[] p_bytes) static private
Parameters
p_bytes input bytes
Returns
hexadecimal string
Definition at line 488 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.common.CCommon.getHash().
static <T> T de.tu_clausthal.in.mec.common.CCommon.getCheckedValue (final T p_input, final T p_default, final Collection< T > p_allowedvalues) static
Parameters
p_input unchecked value
p_default default value
p_allowedvalues allowed values
Returns
checked value
Template Parameters
T value type
Definition at line 241 of file common/CCommon.java.
static String de.tu_clausthal.in.mec.common.CCommon.getHash (final String p_string, final String p_hash) static
Parameters
p_string input string
p_hash hash algorithm
Returns
hexadecimal hash value
Definition at line 260 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getBytes2Hex().
Referenced by de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getGraphLocation().
static String de.tu_clausthal.in.mec.common.CCommon.getHash (final File p_file, final String p_hash) static
Parameters
p_file input file
p_hash hash algorithm
Returns
hexadecimal hash value
Definition at line 278 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getBytes2Hex().
static Map<String, Object> de.tu_clausthal.in.mec.common.CCommon.getMap (final Object... p_objects) static
Parameters
p_objects list with pairs of string and object
Returns
map with data
Definition at line 297 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
Referenced by de.tu_clausthal.in.mec.object.car.CCarJasonAgent.getPredecessorWithName().
static String de.tu_clausthal.in.mec.common.CCommon.getNonEmptyValue (final String p_input, final String p_default) static
Parameters
p_input input value
p_default default value
Returns
string
Definition at line 322 of file common/CCommon.java.
static String de.tu_clausthal.in.mec.common.CCommon.getResourceString (final Class<?> p_class, final String p_label, final Object... p_parameter) static
Parameters
p_class class for static calls
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 335 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.object.mas.jason.action.CPropertyBind.act(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CBeliefBaseStorage< T >.add(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.add(), de.tu_clausthal.in.mec.runtime.CSimulation.CStorage.add(), de.tu_clausthal.in.mec.object.waypoint.factory.CAgentCarFactory.CAgentCarFactory(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CBeliefBase< T >.CBeliefBase(), de.tu_clausthal.in.mec.ui.web.CBrowser.CBrowser(), de.tu_clausthal.in.mec.object.waypoint.generator.CConstant.CConstant(), de.tu_clausthal.in.mec.object.car.CDefaultCar.CDefaultCar(), de.tu_clausthal.in.mec.object.waypoint.factory.CDefaultCarFactory.CDefaultCarFactory(), de.tu_clausthal.in.mec.common.CReflection.CGetSet.CGetSet(), de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.checkAgentFileSyntax(), de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.CInconsistencyEnvironment(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.CMask(), de.tu_clausthal.in.mec.object.mas.jason.CMessage.CMessage(), de.tu_clausthal.in.mec.runtime.message.CMessage< T >.CMessage(), de.tu_clausthal.in.mec.runtime.message.CParticipant.CParticipant(), de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.createAgentFile(), de.tu_clausthal.in.mec.CConfiguration.createDirectories(), de.tu_clausthal.in.mec.common.CPath.createPath(), de.tu_clausthal.in.mec.common.CPath.createSplitPath(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.createTask(), de.tu_clausthal.in.mec.ui.CSwingWrapper< T extends JComponent >.CSwingWrapper(), de.tu_clausthal.in.mec.common.CTreeNode< T >.CTreeNode(), de.tu_clausthal.in.mec.ui.web.CVirtualDirectory.CVirtualDirectory(), de.tu_clausthal.in.mec.ui.web.CVirtualFile.CVirtualFile(), de.tu_clausthal.in.mec.object.mas.jason.action.CRandom.execute(), de.tu_clausthal.in.mec.object.mas.jason.action.CRandom.EOption.get(), de.tu_clausthal.in.mec.ui.web.CVirtualStaticMethod.get(), de.tu_clausthal.in.mec.common.EDistribution.get(), de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.get(), de.tu_clausthal.in.mec.ui.CWaypointEnvironment.EFactory.get(), de.tu_clausthal.in.mec.ui.CWaypointEnvironment.EGenerator.get(), de.tu_clausthal.in.mec.ui.CWaypointEnvironment.EWaypoint.get(), de.tu_clausthal.in.mec.common.CReflection.CMethodCache< T >.get(), de.tu_clausthal.in.mec.object.mas.jason.IEnvironment< T >.getAgentFile(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.getAgentName(), de.tu_clausthal.in.mec.CConfiguration.getBasePath(), de.tu_clausthal.in.mec.common.CReflection.getClassField(), de.tu_clausthal.in.mec.common.CReflection.getClassMethod(), de.tu_clausthal.in.mec.common.EDistribution.getExpectation(), de.tu_clausthal.in.mec.runtime.CSimulation.getLayerName(), de.tu_clausthal.in.mec.common.CCommon.getMap(), de.tu_clausthal.in.mec.common.CCommon.getResourceString(), de.tu_clausthal.in.mec.object.car.graph.CGraphHopper.getRoutes(), de.tu_clausthal.in.mec.object.mas.inconsistency.CInconsistencyLayer< T extends IAgent >.getStationaryDistribution(), de.tu_clausthal.in.mec.common.CPath.initialize(), de.tu_clausthal.in.mec.ui.IInspectorDefault.inspect(), de.tu_clausthal.in.mec.runtime.core.IRunnable< T >.IRunnable(), de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.EMetric.isa(), de.tu_clausthal.in.mec.runtime.CSimulation.load(), de.tu_clausthal.in.mec.CMain.main(), de.tu_clausthal.in.mec.object.car.graph.CEdge< N, T >.PointListArray.PointListArray(), de.tu_clausthal.in.mec.common.CAdjacencyMatrix< T, N >.remove(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.reset(), de.tu_clausthal.in.mec.runtime.core.CMainLoop.resume(), de.tu_clausthal.in.mec.common.CReflection.CClassIndex.scan(), de.tu_clausthal.in.mec.common.CReflection.CClassIndex.scanDirectory(), de.tu_clausthal.in.mec.common.CReflection.CClassIndex.scanJar(), de.tu_clausthal.in.mec.common.CNameHashMap.set(), de.tu_clausthal.in.mec.ui.web.CBrowser.setBackForward(), de.tu_clausthal.in.mec.object.car.graph.CEdge< N, T >.setObject(), de.tu_clausthal.in.mec.common.CPath.setSeparator(), de.tu_clausthal.in.mec.ui.web.CBrowser.setURLMenu(), de.tu_clausthal.in.mec.ui.CWaypointEnvironment.setWaypoint(), de.tu_clausthal.in.mec.runtime.benchmark.CTimer.start(), de.tu_clausthal.in.mec.runtime.CSimulation.start(), de.tu_clausthal.in.mec.runtime.benchmark.CTimer.stop(), de.tu_clausthal.in.mec.runtime.CSimulation.stop(), de.tu_clausthal.in.mec.runtime.CSimulation.store(), de.tu_clausthal.in.mec.object.mas.generic.implementation.CMask< T >.walk(), de.tu_clausthal.in.mec.runtime.CSimulation.web_static_disableenablelayer(), de.tu_clausthal.in.mec.runtime.CSimulation.web_static_hideshowlayer(), de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_remove(), de.tu_clausthal.in.mec.CConfiguration.web_static_set(), de.tu_clausthal.in.mec.ui.COSMViewer.web_static_setClickableLayer(), de.tu_clausthal.in.mec.ui.CTrafficEnvironment.web_static_setdrivemodel(), de.tu_clausthal.in.mec.ui.CInconsistencyEnvironment.web_static_setMetric(), and de.tu_clausthal.in.mec.ui.CAgentEnvironment.web_static_write().
static String de.tu_clausthal.in.mec.common.CCommon.getResourceString (final String p_language, final Class<?> p_class, final String p_label, final Object... p_parameter) static
Parameters
p_language language code / empty for default
p_class class for static calls
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 349 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceStringLabel().
static String de.tu_clausthal.in.mec.common.CCommon.getResourceString (final Object p_object, final String p_label, final Object... p_parameter) static
Parameters
p_object object for label
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 371 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static String de.tu_clausthal.in.mec.common.CCommon.getResourceString (final String p_language, final Object p_object, final String p_label, final Object... p_parameter) static
Parameters
p_language language code / empty for default
p_object object for label
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 385 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static String de.tu_clausthal.in.mec.common.CCommon.getResourceStringLabel (final Class<?> p_class, final String p_label) static
Parameters
p_class class for static calls
p_label label name of the object
Returns
label name
Definition at line 397 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.removePackageName().
Referenced by de.tu_clausthal.in.mec.Test_CLanguageLabels.MyMethodVisitor.checkLabel(), and de.tu_clausthal.in.mec.common.CCommon.getResourceString().
static URL de.tu_clausthal.in.mec.common.CCommon.getResourceURL () static
Returns
URL of file or null
Definition at line 409 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.common.CCommon.getResourceURL(), and de.tu_clausthal.in.mec.ui.web.CServer.registerVirtualDirectory().
static URL de.tu_clausthal.in.mec.common.CCommon.getResourceURL (final String p_file) static
Jar file
Parameters
p_file file
Returns
URL of file or null
Definition at line 420 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.getResourceURL().
static URL de.tu_clausthal.in.mec.common.CCommon.getResourceURL (final File p_file) static
Jar file
Parameters
p_file file relative to the CMain
Returns
URL of file or null
Definition at line 431 of file common/CCommon.java.
static String de.tu_clausthal.in.mec.common.CCommon.removePackageName (final String p_package) static
Parameters
p_package package / class path
Returns
path without main package name
Definition at line 453 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.common.CCommon.getResourceStringLabel(), and de.tu_clausthal.in.mec.ui.IInspectorDefault.inspect().
static List<String> de.tu_clausthal.in.mec.common.CCommon.startupchecks () static
Returns
list with all error / warning information
Definition at line 84 of file common/CCommon.java.
References de.tu_clausthal.in.mec.common.CCommon.c_gigabyte, and de.tu_clausthal.in.mec.common.CCommon.c_neededmemory.
Referenced by de.tu_clausthal.in.mec.CMain.main().
static String de.tu_clausthal.in.mec.common.CCommon.toJson (final Object p_data) static
Returns
Json object
Definition at line 463 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.CConfiguration.write().
Member Data Documentation
final long de.tu_clausthal.in.mec.common.CCommon.c_gigabyte = 1024 * 1024 * 1024 static private
Definition at line 65 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.common.CCommon.startupchecks().
final float de.tu_clausthal.in.mec.common.CCommon.c_neededmemory = 3f static private
Definition at line 69 of file common/CCommon.java.
Referenced by de.tu_clausthal.in.mec.common.CCommon.startupchecks().